### ISSUE TITLE
使用docker部署的话，我要怎么设置http模式并且用accessToken登录，而不是使用邮箱密码登录

### ISSUE THREAD

**Issue by huangbh1024** [zhile-io/pandora#10]
![image](https://github.com/zhile-io/pandora/assets/72372968/9c34414e-2ab3-4a0f-8fd3-2d1446c715c8)

**Comment by Joackk** [comment]
docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？

**Comment by Joackk** [comment]
http模式似乎是要这样：PANDORA_SERVER=ip:port

**Comment by huangbh1024** [comment]
> docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？

我一直都是第三方谷歌登录，没有账号密码，只能使用accessToken登录才行，现在卡在这不知道要咋搞

**Comment by Joackk** [comment]
> > docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？
> 
> 我一直都是第三方谷歌登录，没有账号密码，只能使用accessToken登录才行，现在卡在这不知道要咋搞

文档里有介绍这个，PANDORA_ACCESS_TOKEN 指定Access Token字符串

**Comment by Joackk** [comment]
> > docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？
> 
> 我一直都是第三方谷歌登录，没有账号密码，只能使用accessToken登录才行，现在卡在这不知道要咋搞

你可以调用启动后的api吗？我一直不行，不知道怎么才能用api

**Comment by huangbh1024** [comment]
> > > docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？
> > 
> > 
> > 我一直都是第三方谷歌登录，没有账号密码，只能使用accessToken登录才行，现在卡在这不知道要咋搞
> 
> 你可以调用启动后的api吗？我一直不行，不知道怎么才能用api

啊这，我现在跑都没跑起来

**Comment by Joackk** [comment]
> > > > docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？
> > > 
> > > 
> > > 我一直都是第三方谷歌登录，没有账号密码，只能使用accessToken登录才行，现在卡在这不知道要咋搞
> > 
> > 
> > 文档里有介绍这个，PANDORA_ACCESS_TOKEN 指定Access Token字符串
> 
> ![image](https://user-images.githubusercontent.com/72372968/267585244-b19ce0db-b1d3-488a-9183-a1f789ea97d1.png) 这样子还是要用邮箱和密码才能登录

那就不晓得了，等作者大佬来康康吧

**Comment by huangbh1024** [comment]
> 

跑起来了，api看着挺正常的
![image](https://github.com/zhile-io/pandora/assets/72372968/47d251fb-94b9-4bcf-8a1c-b1eff9330edf)

**Comment by huangbh1024** [comment]
> > > > > docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？
> > > > 
> > > > 
> > > > 我一直都是第三方谷歌登录，没有账号密码，只能使用accessToken登录才行，现在卡在这不知道要咋搞
> > > 
> > > 
> > > 文档里有介绍这个，PANDORA_ACCESS_TOKEN 指定Access Token字符串
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/72372968/267585244-b19ce0db-b1d3-488a-9183-a1f789ea97d1.png) 这样子还是要用邮箱和密码才能登录
> 
> 那就不晓得了，等作者大佬来康康吧

跑起来了，api调用看着挺正常的
![image](https://github.com/zhile-io/pandora/assets/72372968/ceed5431-22e9-4be0-8293-d4f1bb23cd5d)

**Comment by Joackk** [comment]
> > 
> 
> 跑起来了，api看着挺正常的 ![image](https://user-images.githubusercontent.com/72372968/267588071-47d251fb-94b9-4bcf-8a1c-b1eff9330edf.png)

再给其他需要用api的软件里能正常用吗？key的话应该不用填吧

**Comment by Joackk** [comment]
> > > > > > docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？
> > > > > 
> > > > > 
> > > > > 我一直都是第三方谷歌登录，没有账号密码，只能使用accessToken登录才行，现在卡在这不知道要咋搞
> > > > 
> > > > 
> > > > 文档里有介绍这个，PANDORA_ACCESS_TOKEN 指定Access Token字符串
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/72372968/267585244-b19ce0db-b1d3-488a-9183-a1f789ea97d1.png) 这样子还是要用邮箱和密码才能登录
> > 
> > 
> > 那就不晓得了，等作者大佬来康康吧
> 
> 跑起来了，api调用看着挺正常的 ![image](https://user-images.githubusercontent.com/72372968/267588492-ceed5431-22e9-4be0-8293-d4f1bb23cd5d.png)

我看了文档里的介绍，应该使用/api/conversation/talk这个接口，但是在软件里用这个接口的话，会出一堆异常，然后500报错

**Comment by huangbh1024** [comment]
> > > > > > > docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？
> > > > > > 
> > > > > > 
> > > > > > 我一直都是第三方谷歌登录，没有账号密码，只能使用accessToken登录才行，现在卡在这不知道要咋搞
> > > > > 
> > > > > 
> > > > > 文档里有介绍这个，PANDORA_ACCESS_TOKEN 指定Access Token字符串
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/72372968/267585244-b19ce0db-b1d3-488a-9183-a1f789ea97d1.png) 这样子还是要用邮箱和密码才能登录
> > > 
> > > 
> > > 那就不晓得了，等作者大佬来康康吧
> > 
> > 
> > 跑起来了，api调用看着挺正常的 ![image](https://user-images.githubusercontent.com/72372968/267588492-ceed5431-22e9-4be0-8293-d4f1bb23cd5d.png)
> 
> 我看了文档里的介绍，应该使用/api/conversation/talk这个接口，但是在软件里用这个接口的话，会出一堆异常，然后500报错

我在网页使用talk正常，但是使用postman或者自己起服务去调用的话，也是报500
![image](https://github.com/zhile-io/pandora/assets/72372968/8a412bc1-5a24-4242-8903-e6dde74ded51)

**Comment by Joackk** [comment]
> > > > > > > > docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 我一直都是第三方谷歌登录，没有账号密码，只能使用accessToken登录才行，现在卡在这不知道要咋搞
> > > > > > 
> > > > > > 
> > > > > > 文档里有介绍这个，PANDORA_ACCESS_TOKEN 指定Access Token字符串
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/72372968/267585244-b19ce0db-b1d3-488a-9183-a1f789ea97d1.png) 这样子还是要用邮箱和密码才能登录
> > > > 
> > > > 
> > > > 那就不晓得了，等作者大佬来康康吧
> > > 
> > > 
> > > 跑起来了，api调用看着挺正常的 ![image](https://user-images.githubusercontent.com/72372968/267588492-ceed5431-22e9-4be0-8293-d4f1bb23cd5d.png)
> > 
> > 
> > 我看了文档里的介绍，应该使用/api/conversation/talk这个接口，但是在软件里用这个接口的话，会出一堆异常，然后500报错
> 
> 我在网页使用talk正常，但是使用postman或者自己起服务去调用的话，也是报500 ![image](https://user-images.githubusercontent.com/72372968/267595280-8a412bc1-5a24-4242-8903-e6dde74ded51.png)

对的就是这个问题，想要api主要就是给其他软件用

**Comment by ICLiuLi** [comment]
> > > > > > docker部署的话，可以直接在docker-compose文件里填写好账号密码吗？
> > > > > 
> > > > > 
> > > > > 我一直都是第三方谷歌登录，没有账号密码，只能使用accessToken登录才行，现在卡在这不知道要咋搞
> > > > 
> > > > 
> > > > 文档里有介绍这个，PANDORA_ACCESS_TOKEN 指定Access Token字符串
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/72372968/267585244-b19ce0db-b1d3-488a-9183-a1f789ea97d1.png) 这样子还是要用邮箱和密码才能登录
> > 
> > 
> > 那就不晓得了，等作者大佬来康康吧
> 
> 跑起来了，api调用看着挺正常的 ![image](https://user-images.githubusercontent.com/72372968/267588492-ceed5431-22e9-4be0-8293-d4f1bb23cd5d.png)

请问是怎么跑起来的，我也是要输google账号但是要输邮箱
