### ISSUE TITLE
ChatGPT2023年9月28日更新，增加了Browse with Bing功能，能否在Pandora里面增加Browse with Bing功能

### ISSUE THREAD

**Issue by lugaochao** [zhile-io/pandora#100]
ChatGPT2023年9月28日更新，增加了Browse with Bing功能，能否在Pandora里面增加
Browse with Bing
Try a version of ChatGPT that knows when and how to browse the internet to answer questions about recent topics and events.
我不知道增加这个功能是否有价值添加，只是建议。
<img width="1029" alt="iShot_2023-09-28_12 22 38" src="https://github.com/zhile-io/pandora/assets/30764488/ade91a5c-4700-413a-a0b4-ebdbcc99e235">

**Comment by huangzhitian** [comment]
问一下官网这个功能需要PLUS吗

**Comment by lugaochao** [comment]
> 问一下官网这个功能需要PLUS吗

需要

**Comment by huangzhitian** [comment]
> > 问一下官网这个功能需要PLUS吗
> 
> 需要

那和之前的联网模式有啥区别

**Comment by lugaochao** [comment]
> > > 问一下官网这个功能需要PLUS吗
> > 
> > 
> > 需要
> 
> 那和之前的联网模式有啥区别

应该更安全了吧，之前好像是泄露了windows的激活码被禁用了，现在估计修复了这些漏洞

**Comment by RoyRao2333** [comment]
@lugaochao 

问一下已经添加了吗？今天登录后在设置里也没发现`Browse with Bing`开关（是Plus用户）

**Comment by lugaochao** [comment]
更新了，beta features里面还是没有，但是主页有直接就有。







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月7日(星期六) 上午10:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhile-io/pandora] ChatGPT2023年9月28日更新，增加了Browse with Bing功能，能否在Pandora里面增加Browse with Bing功能 (Issue #100)





 
@lugaochao
 
问一下已经添加了吗？今天登录后在设置里也没发现Browse with Bing开关（是Plus用户）
