### ISSUE TITLE
Cloud模式怎么免登录部署

### ISSUE THREAD

**Issue by sw586** [zhile-io/pandora#101]
docker run -e PANDORA_CLOUD=cloud -e PANDORA_ACCESS_TOKEN=56495464645646adasdasdadsadsasdasdasfafasfasfasfa -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora

以上无效，Cloud模式是否支持携带ACCESS_TOKEN启动容器？

**Comment by PlayMcBKuwu** [comment]
> docker run -e PANDORA_CLOUD=cloud -e PANDORA_ACCESS_TOKEN=56495464645646adasdasdadsadsasdasdasfafasfasfasfa -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora
> 
> 以上无效，Cloud模式是否支持携带ACCESS_TOKEN启动容器？

## 无解
- 你只能给用户你的 Access Token
- 除非改代码

**Comment by zhile-io** [comment]
cloud 模式是需要登录的。
