### ISSUE TITLE
问一下，可以使用 Access Token 登录吗？

### ISSUE THREAD

**Issue by achirand** [zhile-io/pandora#102]
问一下，可以使用 Access Token 登录吗？

https://ai-20230927.fakeopen.com/auth  我用这个Chrome 插件获取不到  Access Token。

**Comment by pretenderlu** [comment]
可以的呀

**Comment by buxianshan** [comment]
如果你可以在官网登录，打开这个页面就可以拿到token：http://chat.openai.com/api/auth/session

**Comment by kuke21** [comment]
一样  获取不到了

**Comment by s181462537** [comment]
> 问一下，可以使用 Access Token 登录吗？
> 
> https://ai-20230927.fakeopen.com/auth 我用这个Chrome 插件获取不到 Access Token。

不用插件也能获取，在开发者工具中，网络模块中能找到

**Comment by zhile-io** [comment]
可以的。
