### ISSUE TITLE
新版 WebBrowsing 优化

### ISSUE THREAD

**Issue by JackuXL** [zhile-io/pandora#104]
WebBrowsing 在 Pandora 上搜索时，和在官网显示差别较大

**Comment by JackuXL** [comment]
![image](https://github.com/zhile-io/pandora/assets/58510349/796a0ca4-6c73-4af7-b065-d14e5be221c8)
Pandora 显示了 ChatGPT的思考，排版有些乱

![image](https://github.com/zhile-io/pandora/assets/58510349/4fde4394-2ce0-4f8d-b73a-e695297e3cb6)
官网效果

**Comment by yanyao2333** [comment]
我觉得这样展示出来还挺好的，除了确实不太好看

**Comment by zhile-io** [comment]
已更新
