### ISSUE TITLE
这几天突然无法使用了，提示如下图

### ISSUE THREAD

**Issue by star2k** [zhile-io/pandora#106]
![Snipaste_2023-09-30_18-17-37](https://github.com/zhile-io/pandora/assets/9582078/9cb1f96f-a048-46c0-8313-36313162be45)

**Comment by donson20001982** [comment]
我今天部署，登陆时也是这样。还以为是账户被封禁了

**Comment by sinbadr** [comment]
同问+1

**Comment by kuke21** [comment]
同问+1

**Comment by shark0806** [comment]
+1

**Comment by rui12366B** [comment]
+1

**Comment by WilsonVincent** [comment]
#84

**Comment by Jasone1-3** [comment]
请问这个版本更新怎么操作的，现在是1.18版本想升级，不知道怎么进行

**Comment by WilsonVincent** [comment]
> 请问这个版本更新怎么操作的，现在是1.18版本想升级，不知道怎么进行
https://github.com/zhile-io/pandora/blob/master/doc/wiki.md#%E5%A6%82%E4%BD%95%E8%BF%90%E8%A1%8C

**Comment by Jasone1-3** [comment]
> > 请问这个版本更新怎么操作的，现在是1.18版本想升级，不知道怎么进行
> 
> https://github.com/zhile-io/pandora/blob/master/doc/wiki.md#%E5%A6%82%E4%BD%95%E8%BF%90%E8%A1%8C

哥这个命令启动还是安装的老版本的，

**Comment by hcppxgit** [comment]
> 请问这个版本更新怎么操作的，现在是1.18版本想升级，不知道怎么进行

当然！下面是更新Docker容器中程序版本的具体步骤的总结：

1. 停止当前运行的容器：使用以下命令停止正在运行的容器：
   ```
   docker stop <container_id>
   ```
   将 `<container_id>` 替换为您要停止的容器的ID。您可以使用 `docker ps` 命令来查看正在运行的容器的ID。

2. 删除停止的容器：一旦容器停止，使用以下命令删除容器：
   ```
   docker rm <container_id>
   ```
   将 `<container_id>` 替换为要删除的容器的ID。

3. 拉取新的镜像并创建新容器：使用以下命令拉取新的镜像并创建一个新的容器：
   ```
   docker pull pengzhile/pandora:latest
   docker run -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora:latest
   ```
   这将拉取最新版本的 `pengzhile/pandora` 镜像并创建一个新的容器。

4. 验证新容器是否正在运行：使用以下命令验证新容器是否正在运行：
   ```
   docker ps
   ```
   您应该会看到新容器的相关信息，包括容器的ID、镜像、端口映射等。

完成上述步骤后，您的Docker容器中的程序版本就会成功更新到最新版本了。

请记住，更新之前请确保备份重要数据和配置，并仔细阅读新版本的更新说明和文档，以便了解任何可能需要更新或调整的配置或操作步骤。

如果您还有其他问题，请随时向我提问。祝您成功更新您的Docker程序！

**Comment by WilsonVincent** [comment]
> > > 请问这个版本更新怎么操作的，现在是1.18版本想升级，不知道怎么进行
> > 
> > 
> > https://github.com/zhile-io/pandora/blob/master/doc/wiki.md#%E5%A6%82%E4%BD%95%E8%BF%90%E8%A1%8C
> 
> 哥这个命令启动还是安装的老版本的，

docker部署就是docker pull ...
本地编译可以直接根据文档编译运行。

**Comment by alex-oos** [comment]
我的项目老起不来，我本来想自己开发自己修改一下呢
![image](https://github.com/zhile-io/pandora/assets/46887064/5654042c-7629-4bd0-86f4-7f2f6da7ff9d)

**Comment by PlayMcBKuwu** [comment]
> 我的项目老起不来，我本来想自己开发自己修改一下呢 ![image](https://user-images.githubusercontent.com/46887064/272987543-5654042c-7629-4bd0-86f4-7f2f6da7ff9d.png)

不要直接启动这个 Python 文件，你得先打包

**Comment by alex-oos** [comment]
> > 我的项目老起不来，我本来想自己开发自己修改一下呢 ![image](https://user-images.githubusercontent.com/46887064/272987543-5654042c-7629-4bd0-86f4-7f2f6da7ff9d.png)
> 
> 不要直接启动这个 Python 文件，你得先打包

好的，我试试哈

**Comment by xinggangxu** [comment]
我也是这样，登入不上去了，有解决方案吗？

**Comment by alex-oos** [comment]
> 我也是这样，登入不上去了，有解决方案吗？

自己搭建一个试试

**Comment by PlayMcBKuwu** [comment]
> 我也是这样，登入不上去了，有解决方案吗？

可以尝试用我的 Fork 版本，理论上是正常的

**Comment by hcppxgit** [comment]
> > 我也是这样，登不上去了，有解决方案吗？
> 
> 可以用我的 Fork 版本尝试一下，理论上是正常的

这个问题出在登录过程中好像获取不到token了，这问题你解决了？而且你那个库拉不了啊【# docker pull zhile-io/pandora
Using default tag: latest
Error response from daemon: pull access denied for zhile-io/pandora, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
】

**Comment by zhile-io** [comment]
已修复。

**Comment by star2k** [comment]
> 已修复。

我们这竟然不用更新版本就修复了，之前这是什么问题啊？
