### ISSUE TITLE
增加share_token的有效时长

### ISSUE THREAD

**Issue by jeffreycai** [zhile-io/pandora#107]
请问下，有没有可能增加share_token的有效时长？貌似超过1天以上时长的share_token就无法生成了

**Comment by undefinedcodezhong** [comment]
share token时效不是自定义的吗，你设置为0可以让它跟随access token有效时长

**Comment by jeffreycai** [comment]
> share token时效不是自定义的吗，你设置为0可以让它跟随access token有效时长

不是啊，定义过长的时长就不允许了，2天都不行

**Comment by undefinedcodezhong** [comment]
@jeffreycai 为什么不设置为0（跟随access token）呢？

**Comment by WilsonVincent** [comment]
默认，sharetoken就是一直有效（与token同期）。
生成sharetoken的key固定的话，每次只需要输入最新的token刷新这个shaeretoken即可。
sharetoken推行以来，没遇到这个问题。可能是你参数写错了吧。

**Comment by semiBorn** [comment]
请问share token生成的教程在哪里

**Comment by undefinedcodezhong** [comment]
> 请问share token生成的教程在哪里

https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#share-token-%E7%9B%B8%E5%85%B3

**Comment by semiBorn** [comment]
@undefinedcodezhong share token为啥最长只能设置九天

**Comment by jeffreycai** [comment]
> 默认，sharetoken就是一直有效（与token同期）。 生成sharetoken的key固定的话，每次只需要输入最新的token刷新这个shaeretoken即可。 sharetoken推行以来，没遇到这个问题。可能是你参数写错了吧。

好的，谢谢

**Comment by zhile-io** [comment]
设置为0，则跟随access token的有效期。
