### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by Hushan123** [zhile-io/pandora#108]
这几天https://ai-20230626.fakeopen.com/auth和chat.zhile.io两个网站直接输入账号密码无法登录，显示获取token出错，官方登陆后手动进入http://chat.openai.com/api/auth/session后复制token后填入可登录

**Comment by hcppxgit** [comment]
遇到同样的问题。

**Comment by iKenzo** [comment]
同上

**Comment by likfees** [comment]
同上，登录不了

**Comment by undefinedcodezhong** [comment]
你们提问的时候都不先看看相似问题的帖子的嘛？官方改登录验证了，所以用账户密码登录的老方法不管用，等作者后续能不能搞定

**Comment by XhnPLayer** [comment]
MFA Code  出来个双重验证..

**Comment by zzwsfnas** [comment]
等待更新

**Comment by hututusb** [comment]
![image](https://github.com/zhile-io/pandora/assets/131585628/f202100c-c0e0-4361-b740-78d313ac1975)
现在登录出现需要填MFA code，请问大佬怎么填

**Comment by boysye** [comment]
同样问题,mark一下.

**Comment by WilsonVincent** [comment]
#84

**Comment by jp-github** [comment]
![image](https://github.com/zhile-io/pandora/assets/83535157/e57408e3-2c4a-462c-bc10-ee39132f431b)
一直这样子

**Comment by PhiBrain-ZhaoLiang** [comment]
我也一样，账号密码登录后跳回到登录界面，无法获取token，但是用谷歌账号快捷登录又可以，问题是登录后history还不能正常现实，人麻了

**Comment by PlayMcBKuwu** [comment]
> ![image](https://user-images.githubusercontent.com/83535157/272538859-e57408e3-2c4a-462c-bc10-ee39132f431b.png) 一直这样子

Cloudflare 的防机器人模式 Zhile 改严格了，多等等即可或者在这个页面晃晃鼠标
