### ISSUE TITLE
同局域网下访问PANDORA——CLOUD

### ISSUE THREAD

**Issue by for3ever3** [zhile-io/pandora#109]
- 起初是因为我想要在校园网中随时随地访问我部署的pandora，正常来说，架设上去能够直接用校园网内的IP访问的，但是，第一次访问的时候出现了connection refused
- 后面问了一下discord里的师傅，他说让我设置sever为0.0.0.0
- 命令：pandora-cloud -s 0.0.0.0:8081
- 然后局域网就能访问了

**Comment by zzy-plus** [comment]
是这样的，一般服务端都是监听0.0.0.0，表示监听本机所有ipv4地址。我之前也在学校部署了一个，遇到过相同问题哈哈哈。监听127.0.0.1是不行的，因为回环地址只允许本机访问
