### ISSUE TITLE
宝塔面板安装Pandora，反向代理之后CSS失效

### ISSUE THREAD

**Issue by daniellauyu** [zhile-io/pandora#11]
![image](https://github.com/zhile-io/pandora/assets/17739321/deb57706-7104-4e45-ae77-47c04948c726)
![image](https://github.com/zhile-io/pandora/assets/17739321/8eb6930b-3c9c-4997-8804-2f07891d5914)
见上图，宝塔后台已经配置反代了，也能通过域名正常访问，但是css加载不出来。
Pandora是通过docker-compose.yml安装的，通过IP+端口可以正常访问，css加载也正常
![image](https://github.com/zhile-io/pandora/assets/17739321/4aaea7af-a379-4d1c-8fc4-c3a0707e0b52)

**Comment by zhile-io** [comment]
你可能需要设置一些类似 host port 之类的nginx头

**Comment by daniellauyu** [comment]
解决了，注释掉配置中的这部分就解决了
```
    # location ~ .*\.(jpg|jpeg|gif|png|js|css)$
    # {
    #     expires      30d;
    #     access_log /dev/null;
    #     valid_referers aobenhaimo.com;
    #     if ($invalid_referer){
    #       return 404;
    #     }
    # }
```
