### ISSUE TITLE
最新的图片上传功能没有出现

### ISSUE THREAD

**Issue by sandycs-protoss** [zhile-io/pandora#110]
我用pip install pandora-chatgpt[cloud]
pandora-cloud命令拉去了最新的安装包并运行
但是最新的图片上传功能没有出现（测试网址和chat官网都已经有了）
是不是哪里需要配置？

**Comment by sandycs-protoss** [comment]
你说的这个是DALLE-3
我说的是图片上传的功能

**Comment by Jerry-Terrasse** [comment]
@sandycs-protoss 你的意思是 https://chat.zhile.io/ 已经有图片上传功能了？我这边看不到诶

**Comment by JackuXL** [comment]
> 你说的这个是DALLE-3 我说的是图片上传的功能

@sandycs-protoss 图片上传已经出现了。我这里可以正常使用

**Comment by sandycs-protoss** [comment]
需要怎么开通吗？
我的cloud版本没有出现
