### ISSUE TITLE
关于accessToken获取

### ISSUE THREAD

**Issue by zzy-plus** [zhile-io/pandora#111]
我发现accessToken可以直接通过访问chat.openai.com/chat（前提当然是需要登陆过的.）借助网页调试工具(F12)获取。操作步骤为：打开F12，访问上述地址，然后在“网络”中搜索“accessToken”，找到一个名为“session”的请求，这个请求的响应中包含了accessToken。我通过这个方式获取到的token的过期时间为2024年1月份，不知道是不是真的这么久。另外实测通过这种方式获得的token可用。

**Comment by undefinedcodezhong** [comment]
你都走官网通道了，为什么还整这么麻烦，直接访问session对应的请求网页不就有了（在readme提到过了）：https://chat.openai.com/api/auth/session
access token有用是因为pandora用的也是这个access token，至于token标识的过期时间是否真的能用那么久，旧仓库有帖子讨论过，反正应该是没有那么久的

**Comment by hezhushizaishi** [comment]
各位大佬好，我是刚来的新人，我有一些困惑，但看了Issues没有我想要的答案，本人不才，实在是不好意思开个楼，在此借楼
1.我应该已经成功部署，知道现在被限制不能用密码登录了，所有改用access token进入官网，我发现默认是chatGPT4.0模式，请问这就成功实现作者大大功能“越狱”吗？
2.作者大大所说的功能从哪个地方可以判断说实现了效果呢？
3.请问api与access token与账号密码登录之间，有什么联系和区别，是建议采用access token还是账号密码登录呢？
4.知道作者大大有免费共享账号（本人已经有，没有占用）的项目，这些账号都可以实现“越狱”吗？还是说不用魔法体验免费体验一下
暂时主要疑惑就是这些，可能有些问题很白痴，，本人不才希望各位大佬能解惑，谢谢。

**Comment by zzy-plus** [comment]
> 你都走官网通道了，为什么还整这么麻烦，直接访问session对应的请求网页不就有了（在readme提到过了）：https://chat.openai.com/api/auth/session access token有用是因为pandora用的也是这个access token，至于token标识的过期时间是否真的能用那么久，旧仓库有帖子讨论过，反正应该是没有那么久的

你给的这个地址打不开

**Comment by zzy-plus** [comment]
> 你都走官网通道了，为什么还整这么麻烦，直接访问session对应的请求网页不就有了（在readme提到过了）：https://chat.openai.com/api/auth/session access token有用是因为pandora用的也是这个access token，至于token标识的过期时间是否真的能用那么久，旧仓库有帖子讨论过，反正应该是没有那么久的

不知道。没看文档

**Comment by undefinedcodezhong** [comment]
@hezhushizaishi 
1. pandora没有“越狱”功能，你的access token在官网是什么权限，在pandora就是什么权限，默认gpt4可能只是UI显示问题
2. 用access token可以部署在无魔法地区使用，这是pandora最大、最重要的效果，如果这就是你理解的“越狱”功能的话。另外还有share token、pool token等用web模拟api的操作
3. 用access token登录web版，跟在官网用账号密码登录使用web版理论上没有区别，不消耗api额度，频率限制与官网相同
4. 共享账号跟你使用access token一样，都是可以免魔法使用

**Comment by undefinedcodezhong** [comment]
> > 你都走官网通道了，为什么还整这么麻烦，直接访问session对应的请求网页不就有了（在readme提到过了）：https://chat.openai.com/api/auth/session access token有用是因为pandora用的也是这个access token，至于token标识的过期时间是否真的能用那么久，旧仓库有帖子讨论过，反正应该是没有那么久的
> 
> 你给的这个地址打不开

这个是官网地址，需要魔法，另外就是如果你浏览器没有缓存的话，要先登录chat，再开这个地址，也就是readme的这句话：
![image](https://github.com/zhile-io/pandora/assets/40236765/4bf41a37-9b14-4328-ab55-feadb061004c)

**Comment by lakako** [comment]
我在设置accessToken的时候提示Signature verification failed，有没有办法跳过验证？

**Comment by hezhushizaishi** [comment]
> @hezhushizaishi
> 
> 1. pandora没有“越狱”功能，你的access token在官网是什么权限，在pandora就是什么权限，默认gpt4可能只是UI显示问题
> 2. 用access token可以部署在无魔法地区使用，这是pandora最大、最重要的效果，如果这就是你理解的“越狱”功能的话。另外还有share token、pool token等用web模拟api的操作
> 3. 用access token登录web版，跟在官网用账号密码登录使用web版理论上没有区别，不消耗api额度，频率限制与官网相同
> 4. 共享账号跟你使用access token一样，都是可以免魔法使用
谢谢大佬的解答，刚刚看了一下，显示的是fake chatgpt（假chatGPT），如果说主要功能是为了不使用魔法的话登录体验，那这样子的话其实对我作用不是很大，我其实更看重的他的功能4,5，就是问一下比较擦边的话，就会触发道德审查，触发了几次后，我上个号就没了（哭笑），请问我不论用什么方式登录，只要进入到作者大大的所设置的GPT里面，主页上介绍的主要功能到目前为止应该可以生效吧，麻烦大佬们再次解惑，谢谢大佬们。

**Comment by hezhushizaishi** [comment]
> @hezhushizaishi
> 
> 1. pandora没有“越狱”功能，你的access token在官网是什么权限，在pandora就是什么权限，默认gpt4可能只是UI显示问题
> 2. 用access token可以部署在无魔法地区使用，这是pandora最大、最重要的效果，如果这就是你理解的“越狱”功能的话。另外还有share token、pool token等用web模拟api的操作
> 3. 用access token登录web版，跟在官网用账号密码登录使用web版理论上没有区别，不消耗api额度，频率限制与官网相同
> 4. 共享账号跟你使用access token一样，都是可以免魔法使用


谢谢大佬的解答，刚刚看了一下，显示的是fake chatgpt（假chatGPT），如果说主要功能是为了不使用魔法的话登录体验，那这样子的话其实对我作用不是很大，我其实更看重的他的功能4,5，就是问一下比较擦边的话，就会触发道德审查，触发了几次后，我上个号就没了（哭笑），请问我不论用什么方式登录，只要进入到作者大大的所设置的GPT里面，主页上介绍的主要功能到目前为止应该可以生效吧，麻烦大佬们再次解惑，谢谢大佬们。

**Comment by undefinedcodezhong** [comment]
> > @hezhushizaishi
> > 
> > 1. pandora没有“越狱”功能，你的access token在官网是什么权限，在pandora就是什么权限，默认gpt4可能只是UI显示问题
> > 2. 用access token可以部署在无魔法地区使用，这是pandora最大、最重要的效果，如果这就是你理解的“越狱”功能的话。另外还有share token、pool token等用web模拟api的操作
> > 3. 用access token登录web版，跟在官网用账号密码登录使用web版理论上没有区别，不消耗api额度，频率限制与官网相同
> > 4. 共享账号跟你使用access token一样，都是可以免魔法使用
> 
> 谢谢大佬的解答，刚刚看了一下，显示的是fake chatgpt（假chatGPT），如果说主要功能是为了不使用魔法的话登录体验，那这样子的话其实对我作用不是很大，我其实更看重的他的功能4,5，就是问一下比较擦边的话，就会触发道德审查，触发了几次后，我上个号就没了（哭笑），请问我不论用什么方式登录，只要进入到作者大大的所设置的GPT里面，主页上介绍的主要功能到目前为止应该可以生效吧，麻烦大佬们再次解惑，谢谢大佬们。

显示fake chatgpt仅仅是作者的UI设置，毕竟不是官方原版网站，做一点小小的区分，你甚至可以自己改UI显示fxxk chatgpt都可以。
作者readme里应该写的也很清楚，pandora最主要的功能就是日常免魔法使用。当然获取access token的时候需要魔法，所谓的“充电五分钟，使用两小时”嘛，对于没有稳定魔法的人来说这是很有用的，而且可以通过access token、share token给到其他人使用，还可以使用share token模拟api，很大程度丰富了使用体验。或者是像其他issue里提到的，局域网部署，其他设备访问这种使用途径。

**Comment by hezhushizaishi** [comment]
> > > @hezhushizaishi
> > > 
> > > 1. pandora没有“越狱”功能，你的access token在官网是什么权限，在pandora就是什么权限，默认gpt4可能只是UI显示问题
> > > 2. 用access token可以部署在无魔法地区使用，这是pandora最大、最重要的效果，如果这就是你理解的“越狱”功能的话。另外还有share token、pool token等用web模拟api的操作
> > > 3. 用access token登录web版，跟在官网用账号密码登录使用web版理论上没有区别，不消耗api额度，频率限制与官网相同
> > > 4. 共享账号跟你使用access token一样，都是可以免魔法使用
> > 
> > 
> > 谢谢大佬的解答，刚刚看了一下，显示的是fake chatgpt（假chatGPT），如果说主要功能是为了不使用魔法的话登录体验，那这样子的话其实对我作用不是很大，我其实更看重的他的功能4,5，就是问一下比较擦边的话，就会触发道德审查，触发了几次后，我上个号就没了（哭笑），请问我不论用什么方式登录，只要进入到作者大大的所设置的GPT里面，主页上介绍的主要功能到目前为止应该可以生效吧，麻烦大佬们再次解惑，谢谢大佬们。
> 
> 显示fake chatgpt仅仅是作者的UI设置，毕竟不是官方原版网站，做一点小小的区分，你甚至可以自己改UI显示fxxk chatgpt都可以。 作者readme里应该写的也很清楚，pandora最主要的功能就是日常免魔法使用。当然获取access token的时候需要魔法，所谓的“充电五分钟，使用两小时”嘛，对于没有稳定魔法的人来说这是很有用的，而且可以通过access token、share token给到其他人使用，还可以使用share token模拟api，很大程度丰富了使用体验。或者是像其他issue里提到的，局域网部署，其他设备访问这种使用途径。



> > > @hezhushizaishi
> > > 
> > > 1. pandora没有“越狱”功能，你的access token在官网是什么权限，在pandora就是什么权限，默认gpt4可能只是UI显示问题
> > > 2. 用access token可以部署在无魔法地区使用，这是pandora最大、最重要的效果，如果这就是你理解的“越狱”功能的话。另外还有share token、pool token等用web模拟api的操作
> > > 3. 用access token登录web版，跟在官网用账号密码登录使用web版理论上没有区别，不消耗api额度，频率限制与官网相同
> > > 4. 共享账号跟你使用access token一样，都是可以免魔法使用
> > 
> > 
> > 谢谢大佬的解答，刚刚看了一下，显示的是fake chatgpt（假chatGPT），如果说主要功能是为了不使用魔法的话登录体验，那这样子的话其实对我作用不是很大，我其实更看重的他的功能4,5，就是问一下比较擦边的话，就会触发道德审查，触发了几次后，我上个号就没了（哭笑），请问我不论用什么方式登录，只要进入到作者大大的所设置的GPT里面，主页上介绍的主要功能到目前为止应该可以生效吧，麻烦大佬们再次解惑，谢谢大佬们。
> 
> 显示fake chatgpt仅仅是作者的UI设置，毕竟不是官方原版网站，做一点小小的区分，你甚至可以自己改UI显示fxxk chatgpt都可以。 作者readme里应该写的也很清楚，pandora最主要的功能就是日常免魔法使用。当然获取access token的时候需要魔法，所谓的“充电五分钟，使用两小时”嘛，对于没有稳定魔法的人来说这是很有用的，而且可以通过access token、share token给到其他人使用，还可以使用share token模拟api，很大程度丰富了使用体验。或者是像其他issue里提到的，局域网部署，其他设备访问这种使用途径。

感谢大佬的答疑解惑，已经有初步的认识了，谢谢大佬

**Comment by zhile-io** [comment]
具体时间可以把access token放进 jwt.io 查看`exp`
