### ISSUE TITLE
[bug]error get login token

### ISSUE THREAD

**Issue by sjhsbhqf** [zhile-io/pandora#112]
对于网站 https://chat.zhile.io/auth/login?v=5

我输入chatgpt账号和密码后，点击登录，

提示error get login token

**Comment by undefinedcodezhong** [comment]
写新帖子前可以先看看其他的帖子，满满的都是登录相关的问题，何必再新开一个徒增烦恼呢？
问题就是这么个问题：https://github.com/zhile-io/pandora/issues/84#issuecomment-1734734145

**Comment by sjhsbhqf** [comment]
> 写新帖子前可以先看看其他的帖子，满满的都是登录相关的问题，何必再新开一个徒增烦恼呢？ 问题就是这么个问题：[#84 (comment)](https://github.com/zhile-io/pandora/issues/84#issuecomment-1734734145)

好的，感谢！之前没搜到，不好意思。
