### ISSUE TITLE
大佬，求一个对话框上传图片的功能支持

### ISSUE THREAD

**Issue by xaswq** [zhile-io/pandora#113]
感谢大佬，好人一生平安！
![dd8d8acc22262dceed882eabf65bfab](https://github.com/zhile-io/pandora/assets/85377380/35e01a9d-e9fe-4e3b-8e8f-e64162284b53)

**Comment by JackuXL** [comment]
已经支持了啊，只是按钮的图标是附件的图标

**Comment by xaswq** [comment]
> 已经支持了啊，只是按钮的图标是附件的图标

好像不太行  @JackuXL 
![image](https://github.com/zhile-io/pandora/assets/85377380/f84c92bb-d451-41c0-b467-efb3befc5cc1)

**Comment by RoyRao2333** [comment]
> 已经支持了啊，只是按钮的图标是附件的图标

@JackuXL pandora-cloud貌似还没看到图标，无论图片还是附件

**Comment by zhile-io** [comment]
已更新。
