### ISSUE TITLE
DALL·E 3 支持

### ISSUE THREAD

**Issue by JackuXL** [zhile-io/pandora#114]
![image](https://github.com/zhile-io/pandora/assets/58510349/c4efbe96-2141-47f0-8988-ee525779ff1f)

如题 出现了选项但是有BUG @zhile-io

**Comment by zhheo** [comment]
看了一下详情，似乎是不支持显示图片

**Comment by neosun100** [comment]
When will it be fixed? 🔥

**Comment by luozhiguo12** [comment]
等待适配

**Comment by semiBorn** [comment]
@zhile-io 每日一问

**Comment by i-yuanfang** [comment]
已适配

**Comment by zhile-io** [comment]
已更新。
