### ISSUE TITLE
关于某些不能科学上网地区服务器商审核的问题

### ISSUE THREAD

**Issue by youhuangla** [zhile-io/pandora#116]
能用，感谢！担忧某些地区云服务器商可能会封。使用cloud模式时，是否存在一种方法，表面上无法访问该服务器对应端口，但是添加某些域名可以访问，达到规避目的？或者设置成不能直接跳转到登录界面？有办法使用Docker部署做到吗？承德事件还历历在目，害怕

**Comment by MoeBai** [comment]
监听127.0.0.1:端口 , 然后通过Nginx反代试试?

**Comment by PlayMcBKuwu** [comment]
> 能用，感谢！担忧某些地区云服务器商可能会封。使用cloud模式时，是否存在一种方法，表面上无法访问该服务器对应端口，但是添加某些域名可以访问，达到规避目的？或者设置成不能直接跳转到登录界面？有办法使用Docker部署做到吗？承德事件还历历在目，害怕

_~~云服务器商理论上没有封禁你的那个必要就是了。~~_
- 使用 nginx 反代即可，使用 127.0.0.1 回环地址防止通过 IP 访问
- 使用 Cloudflare 进行 DNS 处理并且打开代理模式否则容易被四大运营商锁 IP
- nginx 或许可以修改 /auth/login 改成其他地址？**（不明确）**
- 有修改代码的能力最好用 pip 版本，Docker 理论上没办法设置成不能跳转到登录界面，pip 版本也得改很多代码
