### ISSUE TITLE
share token的有效期问题。

### ISSUE THREAD

**Issue by laixiao** [zhile-io/pandora#118]
![微信图片_20231007094928](https://github.com/zhile-io/pandora/assets/7324402/fa0f0e7a-c5cc-44dd-b4f2-fe425640f65b)

官网貌似已经延迟了有效期，不再是14天，生成的sharetoken能否解除这个14天有效期限制。（现在填0也是14天）
https://ai.fakeopen.com/token

**Comment by hansonhantong** [comment]
这个accesstoken有效期日期是有问题的吧，换算下是14天

**Comment by laixiao** [comment]
> 这个accesstoken有效期日期是有问题的吧，换算下是14天

这个是官方链接获取的，应该没问题。之前新闻好像也听说延长了token有效期

**Comment by hansonhantong** [comment]
我之前用这个获取的accesstoken确实14天就到期了，你看的新闻是什么时间来着

**Comment by laixiao** [comment]
> 我之前用这个获取的accesstoken确实14天就到期了，你看的新闻是什么时间来着

应该以实际官方为准吧，上面截图显示24年1月到期。
官方token获取地址：https://chat.openai.com/api/auth/session

**Comment by wzhanjun** [comment]
> > 我之前用这个获取的accesstoken确实14天就到期了，你看的新闻是什么时间来着
> 
> 应该以实际官方为准吧，上面截图显示24年1月到期。 官方token获取地址：https://chat.openai.com/api/auth/session

搞错了吧，那个expire 不代表accesstoken的有效期， 实际得accesstoken有效期， 你解析下accesstoken就知道了

**Comment by zhile-io** [comment]
事实上官方缩短了access token的有效期，现在是10天了。 你可以贴进 jwt.io 查看。

**Comment by hansonhantong** [comment]
> 事实上官方缩短了access token的有效期，现在是10天了。 你可以贴进 jwt.io 查看。

现在才10天了？已经实行了？

**Comment by hansonhantong** [comment]
> 事实上官方缩短了access token的有效期，现在是10天了。 你可以贴进 jwt.io 查看。

已经实行了嘛？ 要是这样就麻烦了 续期没法自动化 人都会废掉了

**Comment by hansonhantong** [comment]
> > 事实上官方缩短了access token的有效期，现在是10天了。 你可以贴进 jwt.io 查看。
> 
> 已经实行了嘛？ 要是这样就麻烦了 续期没法自动化 人都会废掉了

从10月一号开始的，我9月28号的token还是14天期限的，现在再申请就变成10天期限的了
