### ISSUE TITLE
如何通过源码部署pandora的web版及配置个人api_base地址呢？

### ISSUE THREAD

**Issue by wxtt522** [zhile-io/pandora#12]
我使用docker build -t pandora . 打出来的镜像默认启动命令行访问，和直接docker pull下来的镜像的web端不一样，没找到相关文档，特来问一下。

使用token的调用地址 openai.api_base = "https://ai.fakeopen.com/v1/"是这个项目提供的服务么

**Comment by zhile-io** [comment]
配置这个需要设置环境变量，具体可以看文档。
