### ISSUE TITLE
请教下 access token 能写死在配置里面吗？

### ISSUE THREAD

**Issue by leonqiu888** [zhile-io/pandora#121]
请教下 access token 能写死在配置里面吗？我是用的docker的搭建  不想每次都要记住token 直接写死到系统里面 是否可以？如果可以是哪个配置文件 还请教下  谢谢

**Comment by linyongcheng94** [comment]
access token 存在有效期的，写死在配置里，到期了之后也是用不了的。

**Comment by leonqiu888** [comment]
我自己解决了 ，  免去每次复制的麻烦  但是风险肯定是有的 到期后自己在换就好了

> access token 存在有效期的，写死在配置里，到期了之后也是用不了的。

**Comment by onlyfew** [comment]
怎么解决的？改的哪里啊？ @leonqiu888

**Comment by leonqiu888** [comment]
> 怎么解决的？改的哪里啊？ @leonqiu888

搜索容器里面的login.html文件编辑这个文件 搜索 Swal.fire({input: 'textarea',inputLabel: 'Continue with Access Token',inputPlaceholder: 'Please input access token...',inputValue: 'YOUR_DEFAULT_VALUE_HERE', // 设置默认输入值

**Comment by PlayMcBKuwu** [comment]
_~~Cloud 版本千年无解的内置 Token 终于实现了。~~_
- ~~可以 Fork 后自己在 wiki.md 里面加上这一段方便大家~~
