### ISSUE TITLE
请问可否通过 不同密码+token 的方式进行会话隔离？

### ISSUE THREAD

**Issue by Cranberrycrisp** [zhile-io/pandora#122]
类似https://chat-shared2.zhile.io/shared.html

**Comment by PlayMcBKuwu** [comment]
> 类似https://chat-shared2.zhile.io/shared.html

目前 Share Token 无解，密码还没办法，只能判断设备 ID 和 IP

**Comment by zhile-io** [comment]
可以，请使用[share token](https://ai.fakeopen.com/token)。

**Comment by PlayMcBKuwu** [comment]
> 可以，请使用[share token](https://ai.fakeopen.com/token)。

准确而言，本题 Author 的意思是需要密码来隔离（
