### ISSUE TITLE
{"detail":"rate limited."} 是官方加强了吗 就很烦

### ISSUE THREAD

**Issue by lgzzk** [zhile-io/pandora#123]

**Comment by lgzzk** [comment]
https://chat.openai.com/api/auth/session 还是拿这个吧 "expires": "2024-01-05T14:16:09.110Z", 两个月也差不多了

**Comment by gavinup** [comment]
> https://chat.openai.com/api/auth/session 还是拿这个吧 "expires": "2024-01-05T14:16:09.110Z", 两个月也差不多了

实际没有2个月的

**Comment by xinggangxu** [comment]
我也是这个错误。

**Comment by lgzzk** [comment]
> > https://chat.openai.com/api/auth/session 还是拿这个吧 "expires": "2024-01-05T14:16:09.110Z", 两个月也差不多了
> 
> 实际没有2个月的

啊这😂
