### ISSUE TITLE
请问有绕过cloudflare的accessToken的批量获取方式

### ISSUE THREAD

**Issue by shiyegao** [zhile-io/pandora#124]
- openai本身是需要人机验证的，搞不定

- 相关仓库[go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)也不支持了

- <https://ai-20230626.fakeopen.com/auth1>也需要人机验证

请问有没有**脚本化**能够【根据username和password】获取accessToken的方式？

**Comment by mufeng510** [comment]
+1，多个账户手动获取太麻烦了，不现实

**Comment by linyongcheng94** [comment]
+1，部署chatgpt-web项目时，accesstoken过期需要手动更新，太麻烦

**Comment by mufeng510** [comment]
试了一下，好像复活了

**Comment by shiyegao** [comment]
> 试了一下，好像复活了

是指[go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)么？还是怎么批量获取

**Comment by mufeng510** [comment]
> > 试了一下，好像复活了
> 
> 是指[go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)么？还是怎么批量获取

就是pandora的脚本

**Comment by shiyegao** [comment]
> > > 试了一下，好像复活了
> > 
> > 
> > 是指[go-chatgpt-api](https://github.com/linweiyuan/go-chatgpt-api)么？还是怎么批量获取
> 
> 就是pandora的脚本

hxd能不能指个路，具体在哪里可以根据账号密码批量获取accessToken呢？

**Comment by mufeng510** [comment]
我上传了我使用的脚本到了[仓库](https://github.com/mufeng510/Free-ChatGPT-API)

**Comment by shiyegao** [comment]
> 我上传了我使用的脚本到了[仓库](https://github.com/mufeng510/Free-ChatGPT-API)

感谢！确实很好用！狠狠地给star了！
```

**Comment by mufeng510** [comment]
> > 我上传了我使用的脚本到了[仓库](https://github.com/mufeng510/Free-ChatGPT-API)
> 
> 感谢！确实很好用！狠狠地给star了！
> 
> 关键就是这句话：
> 
> ```
> # pip install pandora-chatgpt
> import pandora
> accessToken = pandora.openai.auth(username, password).auth(False)
> ```

是，其他都是pandora的东西了
