### ISSUE TITLE
在手机浏览器上一直显示真人验证界面，无法进入登录界面。

### ISSUE THREAD

**Issue by yamasita351** [zhile-io/pandora#125]
在手机浏览器上一直显示真人验证界面，无法进入登录界面
![4ba3c9912d61e51946025cffabd06c3](https://github.com/zhile-io/pandora/assets/143191931/432f22dd-b8a9-46fa-b392-2ec8f16e1d40)

**Comment by yamasita351** [comment]
即使偶尔进入登录界面后，输入账号和密码登录后又重新回到了真人验证界面，还是无法登录。

**Comment by PlayMcBKuwu** [comment]
> 即使偶尔进入登录界面后，输入账号和密码登录后又重新回到了真人验证界面，还是无法登录。

### 很明显是因为 zhile.io 为了防 DDoS 必须得加这个
### 而手机由于没有鼠标，Cloudflare 无法正确判断你是否是使用手机 UA 的机器人，所以只能久一点了

**Comment by yamasita351** [comment]
> > 即使偶尔进入登录界面后，输入账号和密码登录后又重新回到了真人验证界面，还是无法登录。
> 
> ### 很明显是因为 zhile.io 为了防 DDoS 必须得加这个
> ### 而手机由于没有鼠标，Cloudflare 无法正确判断你是否是使用手机 UA 的机器人，所以只能久一点了

感谢大佬的回答，请问这个有什么方法解决吗？还是只能用access token登录吗？

**Comment by PlayMcBKuwu** [comment]
> > > 即使偶尔进入登录界面后，输入账号和密码登录后又重新回到了真人验证界面，还是无法登录。
> > 
> > 
> > ### 很明显是因为 zhile.io 为了防 DDoS 必须得加这个
> > ### 而手机由于没有鼠标，Cloudflare 无法正确判断你是否是使用手机 UA 的机器人，所以只能久一点了
> 
> 感谢大佬的回答，请问这个有什么方法解决吗？还是只能用access token登录吗？

# 你用 Access Token 是一样的。
# 这不取决于你怎么登录。
# 如果一直反复刷新，唯一解就是不要使用移动/联通运营商或者搞个梯子
