### ISSUE TITLE
粘贴gpt4的access token就能用4了吗？

### ISSUE THREAD

**Issue by onlyfew** [zhile-io/pandora#127]
如题，目前只能用3.5的模型，是因为用的access token没开通plus吗？开通plus后是否可以和官网一样用4了呢？官网的插件可以用吗？代码解释器什么的？上传图片识别的功能等。

**Comment by undefinedcodezhong** [comment]
是的，如果你的账号是plus，那么对应的access token登录后也能使用4.0的模型和大部分插件，由于插件feature需要作者维护，所以官网新出的插件功能可能同步性要晚一点

**Comment by onlyfew** [comment]
谢谢 @undefinedcodezhong
