### ISSUE TITLE
函数__part_five 返回http状态码303

### ISSUE THREAD

**Issue by JasonTa2023** [zhile-io/pandora#129]
本地登录在__part_five这里出错，返回码为303，不是期望的302.

运行结果
C:\Users\Administrator>pandora -l -p http://127.0.0.1:7890

            Pandora - A command-line interface to ChatGPT
            Github: https://github.com/zhile-io/pandora
            Get access token: https://ai-20231007.fakeopen.com/auth
            Version: 1.3.2, Mode: cli, Engine: free

Please enter your email and password to log in ChatGPT!
  Email: xxx
  Password:
  MFA Code(Optional if not set):
### Error occurred: Error login.303

对应代码（稍微修改了下，把resp.status_code显示出来）：

    def __part_five(self, code_verifier: str, state: str) -> str:
        url = 'https://auth0.openai.com/u/login/password?state=' + state
        headers = {
            'User-Agent': self.user_agent,
            'Referer': url,
            'Origin': 'https://auth0.openai.com',
        }
        data = {
            'state': state,
            'username': self.email,
            'password': self.password,
            'action': 'default',
        }

        resp = self.session.post(url, headers=headers, data=data, allow_redirects=False, **self.req_kwargs)
        if resp.status_code == 302:
            location = resp.headers['Location']
            if not location.startswith('/authorize/resume?'):
                raise Exception('Login failed.')

            return self.__part_six(code_verifier, location, url)

        if resp.status_code == 400:
            raise Exception('Wrong email or password.')
        else:
            raise Exception('Error login.'+str(resp.status_code))

**Comment by undefinedcodezhong** [comment]
账号密码的登录方式暂时不可用了，用token登录吧

**Comment by knight-666** [comment]
+1

**Comment by zhile-io** [comment]
OpenAI在登录环节添加了验证码，如果不提供正确的arkose token，就是303
