### ISSUE TITLE
fakeopen 相关文档

### ISSUE THREAD

**Issue by zhile-io** [zhile-io/pandora#13]
文档地址在： https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md

本issue为与其相关的集中讨论贴。

**Comment by zhile-io** [comment]
> 从文档里看来，如果用api那似乎就没潘多拉什么事情了，不知道理解的对不对

是如此。潘多拉主要解决的痛点在README里也写了。主要是提供多种访问界面，免魔法等一些限制。

**Comment by Joackk** [comment]
> > 从文档里看来，如果用api那似乎就没潘多拉什么事情了，不知道理解的对不对
> 
> 是如此。潘多拉主要解决的痛点在README里也写了。主要是提供多种访问界面，免魔法等一些限制。

大佬这个服务可以fakeopen可以自己部署吗？因为我是个人使用并不需要放在公网。看大佬您说的这个服务现在是搭建在您自己的服务器上，有一定的不稳定可能性。

**Comment by zhile-io** [comment]
> > > 从文档里看来，如果用api那似乎就没潘多拉什么事情了，不知道理解的对不对
> > 
> > 
> > 是如此。潘多拉主要解决的痛点在README里也写了。主要是提供多种访问界面，免魔法等一些限制。
> 
> 大佬这个服务fakeopen可以自己部署吗？因为我是个人使用并不需要放在公网。看大佬您说的这个服务现在是搭建在您自己的服务器上，有一定的不稳定可能性。

不能的。
如你所见fakeopen已经涉及到众多服务接口，部署并不容易（gpt-4使用还需要使用ai模型打码）且有一些对openai的私密调用（公开就封了）。如果你只是需要包装3.5的api，社区其实有不少开源的代理，你可以去部署一下。
至于稳定性不用太担心，之前社区代理全不能用的时候，fakeopen也照样正常工作。

**Comment by Joackk** [comment]
> > > > 从文档里看来，如果用api那似乎就没潘多拉什么事情了，不知道理解的对不对
> > > 
> > > 
> > > 是如此。潘多拉主要解决的痛点在README里也写了。主要是提供多种访问界面，免魔法等一些限制。
> > 
> > 
> > 大佬这个服务fakeopen可以自己部署吗？因为我是个人使用并不需要放在公网。看大佬您说的这个服务现在是搭建在您自己的服务器上，有一定的不稳定可能性。
> 
> 不能的。 如你所见fakeopen已经涉及到众多服务接口，部署并不容易（gpt-4使用还需要使用ai模型打码）且有一些对openai的私密调用（公开就封了）。如果你只是需要包装3.5的api，社区其实有不少开源的代理，你可以去部署一下。 至于稳定性不用太担心，之前社区代理全不能用的时候，fakeopen也照样正常工作。

soga，了解，非常感谢解惑

**Comment by Joackk** [comment]
> > > > 从文档里看来，如果用api那似乎就没潘多拉什么事情了，不知道理解的对不对
> > > 
> > > 
> > > 是如此。潘多拉主要解决的痛点在README里也写了。主要是提供多种访问界面，免魔法等一些限制。
> > 
> > 
> > 大佬这个服务fakeopen可以自己部署吗？因为我是个人使用并不需要放在公网。看大佬您说的这个服务现在是搭建在您自己的服务器上，有一定的不稳定可能性。
> 
> 不能的。 如你所见fakeopen已经涉及到众多服务接口，部署并不容易（gpt-4使用还需要使用ai模型打码）且有一些对openai的私密调用（公开就封了）。如果你只是需要包装3.5的api，社区其实有不少开源的代理，你可以去部署一下。 至于稳定性不用太担心，之前社区代理全不能用的时候，fakeopen也照样正常工作。

是的我只用3.5，请问社区是哪个哇，我去看看有没有直接拉docker来用的

**Comment by Joackk** [comment]
> > > > 从文档里看来，如果用api那似乎就没潘多拉什么事情了，不知道理解的对不对
> > > 
> > > 
> > > 是如此。潘多拉主要解决的痛点在README里也写了。主要是提供多种访问界面，免魔法等一些限制。
> > 
> > 
> > 大佬这个服务fakeopen可以自己部署吗？因为我是个人使用并不需要放在公网。看大佬您说的这个服务现在是搭建在您自己的服务器上，有一定的不稳定可能性。
> 
> 不能的。 如你所见fakeopen已经涉及到众多服务接口，部署并不容易（gpt-4使用还需要使用ai模型打码）且有一些对openai的私密调用（公开就封了）。如果你只是需要包装3.5的api，社区其实有不少开源的代理，你可以去部署一下。 至于稳定性不用太担心，之前社区代理全不能用的时候，fakeopen也照样正常工作。

大佬您说的这些网页转api的我也试了几个，但是大部分都需要开魔法才能正常使用，我一直纠结潘多拉的原因其实是看文档里说只有第一次需要魔法，后面就不需要了我这里的部署其实是准备搭建在家里的nas上，但是nas平常并没有挂代理，所以才一直以为潘多拉部署后就算没魔法也可以正常的把网页转为api这样子

**Comment by zhile-io** [comment]
> > > > > 从文档里看来，如果用api那似乎就没潘多拉什么事情了，不知道理解的对不对
> > > > 
> > > > 
> > > > 是如此。潘多拉主要解决的痛点在README里也写了。主要是提供多种访问界面，免魔法等一些限制。
> > > 
> > > 
> > > 大佬这个服务fakeopen可以自己部署吗？因为我是个人使用并不需要放在公网。看大佬您说的这个服务现在是搭建在您自己的服务器上，有一定的不稳定可能性。
> > 
> > 
> > 不能的。 如你所见fakeopen已经涉及到众多服务接口，部署并不容易（gpt-4使用还需要使用ai模型打码）且有一些对openai的私密调用（公开就封了）。如果你只是需要包装3.5的api，社区其实有不少开源的代理，你可以去部署一下。 至于稳定性不用太担心，之前社区代理全不能用的时候，fakeopen也照样正常工作。
> 
> 大佬您说的这些网页转api的我也试了几个，但是大部分都需要开魔法才能正常使用，我一直纠结潘多拉的原因其实是看文档里说只有第一次需要魔法，后面就不需要了我这里的部署其实是准备搭建在家里的nas上，但是nas平常并没有挂代理，所以才一直以为潘多拉部署后就算没魔法也可以正常的把网页转为api这样子

自行部署一定是要魔法的，而且ip质量还要求不低。 fakeopen 通常并不需要魔法，一次也不需要。

**Comment by Joackk** [comment]
> > > > > > 从文档里看来，如果用api那似乎就没潘多拉什么事情了，不知道理解的对不对
> > > > > 
> > > > > 
> > > > > 是如此。潘多拉主要解决的痛点在README里也写了。主要是提供多种访问界面，免魔法等一些限制。
> > > > 
> > > > 
> > > > 大佬这个服务fakeopen可以自己部署吗？因为我是个人使用并不需要放在公网。看大佬您说的这个服务现在是搭建在您自己的服务器上，有一定的不稳定可能性。
> > > 
> > > 
> > > 不能的。 如你所见fakeopen已经涉及到众多服务接口，部署并不容易（gpt-4使用还需要使用ai模型打码）且有一些对openai的私密调用（公开就封了）。如果你只是需要包装3.5的api，社区其实有不少开源的代理，你可以去部署一下。 至于稳定性不用太担心，之前社区代理全不能用的时候，fakeopen也照样正常工作。
> > 
> > 
> > 大佬您说的这些网页转api的我也试了几个，但是大部分都需要开魔法才能正常使用，我一直纠结潘多拉的原因其实是看文档里说只有第一次需要魔法，后面就不需要了我这里的部署其实是准备搭建在家里的nas上，但是nas平常并没有挂代理，所以才一直以为潘多拉部署后就算没魔法也可以正常的把网页转为api这样子
> 
> 自行部署一定是要魔法的，而且ip质量还要求不低。 fakeopen 通常并不需要魔法，一次也不需要。

soga，原来是这样，感谢大佬

**Comment by doveppp** [comment]
要延长accesstoken使用时间只需要定期通过refersh token刷新access token就可以吗，我是谷歌账号登录的这个应该怎样获取refersh token？我看文档中的接口是需要账号密码。

**Comment by magicalAttacker** [comment]
在我看来fakeopen是一个魔改的`chat.openai.com`的镜像站，可以这么理解吧

**Comment by wxtt522** [comment]
如果所有请求都由ai.fakeopen.com代理，那这个服务安全吗？

**Comment by shuaiplus** [comment]
> 如果所有请求都由ai.fakeopen.com代理，那这个服务安全吗？

人家已经免费拿出来给你用了，用不用是你的事，不需要作者保障安全性

**Comment by kettly1260** [comment]
那我能换成自己的go-chatgpt-api地址吗？没看到配置文档里有这个选项

**Comment by iblogc** [comment]
@Joackk 看你的描述，我感觉这个项目适合你 https://github.com/x-dr/chatgptProxyAPI，使用 Cloudflare 中转下 OpenAI 的 API，然后就可能直接调用了，我自己也在用。

**Comment by Joackk** [comment]
> @Joackk 看你的描述，我感觉这个项目适合你 https://github.com/x-dr/chatgptProxyAPI ，使用 Cloudflare 中转下 OpenAI 的 API，然后就可能直接调用了，我自己也在用。

这似乎是给api做中转？但我api额度早就用完了

**Comment by pineconeliu** [comment]
1、本地cloud模式启动成功了
<img width="632" alt="uTools_1697338307484" src="https://github.com/zhile-io/pandora/assets/39823232/121c59ed-d0aa-4b2f-83dd-dbd4fcbf42e0">

2、使用accessToken也进入了页面，但是页面不能发送消息，且登录的状态中没有自己的账户名

<img width="914" alt="uTools_1697338100835" src="https://github.com/zhile-io/pandora/assets/39823232/11f2c25c-5ee4-4914-bf2b-5fcb13001e55">


有没有知道的大佬呀，求指导一下

**Comment by zhile-io** [comment]
> 1、本地cloud模式启动成功了 <img alt="uTools_1697338307484" width="632" src="https://user-images.githubusercontent.com/39823232/275298429-121c59ed-d0aa-4b2f-83dd-dbd4fcbf42e0.png">
> 
> 2、使用accessToken也进入了页面，但是页面不能发送消息，且登录的状态中没有自己的账户名
> 
> <img alt="uTools_1697338100835" width="914" src="https://user-images.githubusercontent.com/39823232/275298286-11f2c25c-5ee4-4914-bf2b-5fcb13001e55.png">
> 有没有知道的大佬呀，求指导一下

什么上古版本，都1.3.4了。

**Comment by Somnus1437** [comment]
三款模式里面cloud模式最好用，完全可以当镜子使用，可一直没搞懂储存了Token进去了，为什么分享给朋友使用，他们登录还是出现了登录窗口，怎么跳过去啊，大神。介绍这个的文章一直找不到，原来介绍的nginx的好像行不通啊

**Comment by undefinedcodezhong** [comment]
> 三款模式里面cloud模式最好用，完全可以当镜子使用，可一直没搞懂储存了Token进去了，为什么分享给朋友使用，他们登录还是出现了登录窗口，怎么跳过去啊，大神。介绍这个的文章一直找不到，原来介绍的nginx的好像行不通啊

怎么说呢，cloud模式免登录是件危险的事情，万一网址被扫到，别人不就直接薅你的账户了嘛，所以作者才如此设置。

**Comment by QJKuan** [comment]
问一下各位大佬  docker启动是不支持cloud模式吗  好像只能用命令行操作

**Comment by QJKuan** [comment]
> > 三款模式里面cloud模式最好用，完全可以当镜子使用，可一直没搞懂储存了Token进去了，为什么分享给朋友使用，他们登录还是出现了登录窗口，怎么跳过去啊，大神。介绍这个的文章一直找不到，原来介绍的nginx的好像行不通啊
> 
> 怎么说呢，cloud模式免登录是件危险的事情，万一网址被扫到，别人不就直接薅你的账户了嘛，所以作者才如此设置。

大佬  我自己有一个登录系统 所以我想要直接存储token进去 这样我共享给朋友就不用登录  有什么参数可以直接注入吗

**Comment by wj2008** [comment]
大佬看你在其它issue里回复  “3.5需要arkose，目前客户端不可用，网页可用。”
是否意味着没有arkose_token 将无法使用https://ai-20231024.fakeopen.com/api/conversation 接口
这个后续会出生成arkose_token参数的接口不？

**Comment by zhile-io** [comment]
> 大佬看你在其它issue里回复 “3.5需要arkose，目前客户端不可用，网页可用。” 是否意味着没有arkose_token 将无法使用https://ai-20231024.fakeopen.com/api/conversation 接口 这个后续会出生成arkose_token参数的接口不？

会弄，但坦白说3.5需求巨大，不太可能让人人都用得上。

**Comment by doveppp** [comment]
最近fakeopen经常不返回信息  使用sharetoken 或者pooltoken都一样 换账号也不行   我的问题还是怎么？  
![image](https://github.com/zhile-io/pandora/assets/54977106/f4f4a0a6-c4f3-4fef-865f-7b0f5c1525cf)
![image](https://github.com/zhile-io/pandora/assets/54977106/4253e5c0-d321-4754-aa31-2622bda41cf7)

**Comment by Yanyutin753** [comment]
我也是
