### ISSUE TITLE
我账号几个人用,但是历史记录不想让他们都看到,使用Cloud模式可以解决吗?

### ISSUE THREAD

**Issue by AShadow666** [zhile-io/pandora#131]

**Comment by AShadow666** [comment]
如题,主要是想解决几个人共用历史记录被查看的问题.因经常用GPT写代码,以免部分内容泄露.

**Comment by PlayMcBKuwu** [comment]
> 如题,主要是想解决几个人共用历史记录被查看的问题.因经常用GPT写代码,以免部分内容泄露.

- https://ai.fakeopen.com/token
- 可以在这里生成区分对话历史的 Share Token。

**Comment by AShadow666** [comment]
你太棒了,感谢

> > 如题,主要是想解决几个人共用历史记录被查看的问题.因经常用GPT写代码,以免部分内容泄露.
> 
> * https://ai.fakeopen.com/token
> * 可以在这里生成区分对话历史的 Share Token。
