### ISSUE TITLE
最近两周都登录不上了，是什么原因

### ISSUE THREAD

**Issue by wangwzc** [zhile-io/pandora#132]
![image](https://github.com/zhile-io/pandora/assets/7286295/b409a7c0-31ed-432d-aece-4d5a4a07df13)
这一步转半天，转不出来是什么问题。

**Comment by jp-github** [comment]
+1

**Comment by stephen-coding** [comment]
+1

**Comment by stephen-coding** [comment]
+1

**Comment by FuSiYu666** [comment]
可以直接进https://chat-shared2.zhile.io/shared.html
