### ISSUE TITLE
pool token怎么使用

### ISSUE THREAD

**Issue by dao-zero** [zhile-io/pandora#134]

**Comment by undefinedcodezhong** [comment]
生成：https://ai.fakeopen.com/pool
使用：当成免费api key使用

**Comment by kitaev-chen** [comment]
> 生成：https://ai.fakeopen.com/pool 使用：当成免费api key使用

如果作为命令行下，配置 pandora 使用呢？文档里只说了用 access token，并没有 share token, pool token 在终端下如何使用的内容。

**Comment by undefinedcodezhong** [comment]
> > 生成：https://ai.fakeopen.com/pool 使用：当成免费api key使用
> 
> 如果作为命令行下，配置 pandora 使用呢？文档里只说了用 access token，并没有 share token, pool token 在终端下如何使用的内容。

虽然share token/pool token 主要面向的场景是 api 场景，但是share token仍然可以作为access token来使用：
![image](https://github.com/zhile-io/pandora/assets/40236765/9a70b0f5-c67d-48c7-80fd-fe7566bfa4a8)

pool token意义是轮询，所以（实测）不能作为access token使用。
但其实终端交互和 pandora UI 交互场景下没太必要使用。

**Comment by kitaev-chen** [comment]
哦明白了，确实share token有用而pool token没用。终端下是有与真实网页版绑定了。谢谢！
