### ISSUE TITLE
### Error occurred: {"detail":"rate limited."}

### ISSUE THREAD

**Issue by Ntohpn** [zhile-io/pandora#135]
### Error occurred: {"detail":"rate limited."}
登录的时候显示这个是什么原因？

**Comment by yifu1024** [comment]
+1

**Comment by xaswq** [comment]
> 奇怪了，怎么突然又好了

@sdlkhfksl 确实好了

**Comment by manshisan** [comment]
> > 奇怪了，怎么突然又好了
> 
> @sdlkhfksl 确实好了

现在已经可以账号登录了？

**Comment by ludashi2020** [comment]
大佬牛逼，真的可以登录了

**Comment by Ivesfsy** [comment]
"detail"."service overload"变了一个，是这个错误
