### ISSUE TITLE
DALL·E 3在cloud模式下无法显示图片（官网可以看到）

### ISSUE THREAD

**Issue by luozhiguo12** [zhile-io/pandora#136]
![1696833411396](https://github.com/zhile-io/pandora/assets/97721925/d9b5fbee-738d-465d-ac7a-f917cc864926)
![image](https://github.com/zhile-io/pandora/assets/97721925/98775d3c-55cb-4b55-aec3-db8d79d913da)

**Comment by xaswq** [comment]
等作者适配吧
