### ISSUE TITLE
这是啥子情况，莫名其妙出现好多会话

### ISSUE THREAD

**Issue by chansanya** [zhile-io/pandora#138]
![image](https://github.com/zhile-io/pandora/assets/47585031/59f5a3f1-7d6d-43ad-b184-de5b5c18cba1)

**Comment by zhile-io** [comment]
都是些什么内容？你是不是账号信息泄露被人扫号了？

**Comment by xaswq** [comment]
账户泄漏了吧

**Comment by Mr-zhao98** [comment]
我没有

**Comment by Mr-zhao98** [comment]
> 都是些什么内容？你是不是账号信息泄露被人扫号了？

啥时候 修复账号登录

**Comment by MrLiuGangQiang** [comment]
> 都是些什么内容？你是不是账号信息泄露被人扫号了？

老板，最近没有更新修复计划么？

**Comment by kitaev-chen** [comment]
我出现过这种情况，是用了arxivGPT chrome插件，每次它实现功能的时候，都会往chatgpt网站里保存功能内容为一个新会话。你可以查查相关的插件，设置关闭什么的。

**Comment by chansanya** [comment]
> 都是些什么内容？你是不是账号信息泄露被人扫号了？

不清楚，每个窗口都是提问了一个：1。
删了我半天，人傻了。

**Comment by chansanya** [comment]
> 我出现过这种情况，是用了arxivGPT chrome插件，每次它实现功能的时候，都会往chatgpt网站里保存功能内容为一个新会话。你可以查查相关的插件，设置关闭什么的。
> 
> 另外，chatgpt手机app端产生的内容，也会同步成新会话的。

每个会话都是单走一个1，插件的话，只是在idea里用过token

**Comment by dao-zero** [comment]
好智障呀，每个窗口一个你好，给我弄上限了，我都没法用了，咱就是说那些扫号的要点脸好不，你要用你好好用，一个对话一个你好是啥意思（不知道是谁用的）

**Comment by dao-zero** [comment]
你们看看你们服务器的nginx的日志，我这边是被一个杭州得脚本一直访问的

**Comment by zhile-io** [comment]
> 你们看看你们服务器的nginx的日志，我这边是被一个杭州得脚本一直访问的

你的部署参数是什么？

**Comment by dao-zero** [comment]
docker run -d --name "$container_name" --restart always --network=host   -e PANDORA_TOKENS_FILE=/root/access_token.json   -e PANDORA_SERVER=0.0.0.0:8888   -v /root/access_token.json:/root/access_token.json   pengzhile/pandora

**Comment by zhile-io** [comment]
> docker run -d --name "$container_name" --restart always --network=host -e PANDORA_TOKENS_FILE=/root/access_token.json -e PANDORA_SERVER=0.0.0.0:8888 -v /root/access_token.json:/root/access_token.json pengzhile/pandora

你这任何人知道网址就能访问啊，考虑在nginx中设置一下basic auth。

**Comment by XhnPLayer** [comment]
现在卡在 二次验证 . 无法登录
