### ISSUE TITLE
常见问题FAQs

### ISSUE THREAD

**Issue by zhile-io** [zhile-io/pandora#14]
这里将手机一些常见问题的原因和解决方案。

**Q:** 为什么我部署的服务不能复制代码？
**A:** 浏览器安全限制了`https`和`127.0.0.1`之外的剪贴板访问权限，简单来说就是：上`https`或用`127.0.0.1`访问。

**Q:** 为什么我部署的服务样式错乱，资源404？
**A:** 通常因为你使用nginx进行反代，但没设置正确的 `$host` 或 `$scheme` 之类的头。具体自行搜索nginx相关资料。

**Comment by hoopec** [comment]
关于复制代码失败，请问是否能够尝试多种方式代码实现以确保功能可用
百度找到了这个链接，应该还是能通过代码实现的，作者可以试试吗？
https://www.ruanyifeng.com/blog/2021/01/clipboard-api.html

**Comment by weixiuu** [comment]
打完字发出去没有反应是什么原因

**Comment by FrankLuo426** [comment]
2023-10-18 10:32:01.009 | ERROR | 
pandora.bots.server:_handle_error:99 - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. 
这个报错是说明啥

**Comment by 14790897** [comment]
现在还有pooltoken吗？想玩一下autogpt

**Comment by 1nihao8** [comment]
我们的系统检测到您的系统存在异常活动。请稍后再试   这个是为什么呀   昨天还能用今天就不能用了

**Comment by guyingi** [comment]
> 我们的系统检测到您的系统存在异常活动。请稍后再试 这个是为什么呀 昨天还能用今天就不能用了

我的也是，而且历史里面有不是我问过的问题，肯定被别人操作过，但是我的token别人怎么会知道，所以有点质疑这个项目作者，有没有收集token拿去做pool做国内付费chatgpt赚钱啊，希望作者解释一下，或者是有什么漏洞被别人利用了

**Comment by zhile-io** [comment]
> > 我们的系统检测到您的系统存在异常活动。请稍后再试 这个是为什么呀 昨天还能用今天就不能用了
> 
> 我的也是，而且历史里面有不是我问过的问题，肯定被别人操作过，但是我的token别人怎么会知道，所以有点质疑这个项目作者，有没有收集token拿去做pool做国内付费chatgpt赚钱啊，希望作者解释一下，或者是有什么漏洞被别人利用了

我解释过了，如果你用server模式，是打开就能访问的。你的网址一旦被人知道，人人都能访问。还有最近有很多扫号的，如果你的账号密码跟一些其他网站相同，可能已经泄露被扫。我没有做任何赚钱项目，广告都没有。我没收任何人钱，也没拉着任何人过来用，如果你不放心可以不要使用，别再拉着我出来解释了。

**Comment by 1nihao8** [comment]
这个有啥解决办法吗  还是说只能换号

**Comment by 1nihao8** [comment]
> > > 我们的系统检测到您的系统存在异常活动。请稍后再试这是为什么呀昨天还能用今天就不能用了
> > 
> > 
> > 我的也是，历史里面有不是我问过的问题，肯定被别人操作过，但是我的代币别人怎么会知道，所以有点质疑这个项目作者，有没有收集代币拿来进行矿池做国内付费chatgpt赚钱啊，希望作者解释一下，或者是有什么漏洞被别人利用了
> 
> 我解释了一下，如果你用服务器模式，是打开可以访问的。你的网址一旦被人知道，人就可以访问。还有最近有很多扫号的，如果你的账号密码跟一些其他网站一样，可能已经泄露被扫了。我没有做任何赚钱项目，广告都没有。我没有收任何人钱，也没有拉着任何人过来用，如果你不放心可以用，别再拉着我出来解释了。

没恶意   觉得网站挺好用的  比官网都好  就是突然不能用了 想问问解决办法

**Comment by 14790897** [comment]
自己找个vps，vps用warp访问chatgpt官网，再也没有任何问题，具体操作上油管搜

**Comment by zhile-io** [comment]
> > > > 我们的系统检测到您的系统存在异常活动。请稍后再试这是为什么呀昨天还能用今天就不能用了
> > > 
> > > 
> > > 我的也是，历史里面有不是我问过的问题，肯定被别人操作过，但是我的代币别人怎么会知道，所以有点质疑这个项目作者，有没有收集代币拿来进行矿池做国内付费chatgpt赚钱啊，希望作者解释一下，或者是有什么漏洞被别人利用了
> > 
> > 
> > 我解释了一下，如果你用服务器模式，是打开可以访问的。你的网址一旦被人知道，人就可以访问。还有最近有很多扫号的，如果你的账号密码跟一些其他网站一样，可能已经泄露被扫了。我没有做任何赚钱项目，广告都没有。我没有收任何人钱，也没有拉着任何人过来用，如果你不放心可以用，别再拉着我出来解释了。
> 
> 没恶意 觉得网站挺好用的 比官网都好 就是突然不能用了 想问问解决办法

官方在灰度3.5验证，要适配更新，我在现有issue里提过了。

**Comment by guyingi** [comment]
> > > 我们的系统检测到您的系统存在异常活动。请稍后再试 这个是为什么呀 昨天还能用今天就不能用了
> > 
> > 
> > 我的也是，而且历史里面有不是我问过的问题，肯定被别人操作过，但是我的token别人怎么会知道，所以有点质疑这个项目作者，有没有收集token拿去做pool做国内付费chatgpt赚钱啊，希望作者解释一下，或者是有什么漏洞被别人利用了
> 
> 我解释过了，如果你用server模式，是打开就能访问的。你的网址一旦被人知道，人人都能访问。还有最近有很多扫号的，如果你的账号密码跟一些其他网站相同，可能已经泄露被扫。我没有做任何赚钱项目，广告都没有。我没收任何人钱，也没拉着任何人过来用，如果你不放心可以不要使用，别再拉着我出来解释了。

网站很好用，没有恶意，也只是说一下问题，防止有什么漏洞被别人利用了，多谢了

**Comment by ChenEeeee** [comment]
怎么开server模式啊。。。

**Comment by guyingi** [comment]
> 怎么开server模式啊。。。

把cloud的那个参数去掉，加上access token那个参数

**Comment by ChenEeeee** [comment]
好了  谢谢

**Comment by hsq1820** [comment]
用的docker，启动不了，总是反馈这个Email: ### Error occurred: EOF when reading a line
