### ISSUE TITLE
潘多拉可以记住上下文吗？

### ISSUE THREAD

**Issue by Joackk** [zhile-io/pandora#140]
之前再用的时候，先给他发送了一组文件名，然后要求他帮我进行一些处理，他却重新提示，让我发送给他要处理的。再次发送给他后，要求他处理，他说没有给。似乎无法记住上下文？

**Comment by kitaev-chen** [comment]
我感觉上下文的能力是要弱于原始chatgpt的网站的。

**Comment by Joackk** [comment]
> 我感觉上下文的能力是要弱于原始chatgpt的网站的。

我先给他发了要处理的数据，然后让他处理，他说我没发给他，离谱

**Comment by kitaev-chen** [comment]
> > 我感觉上下文的能力是要弱于原始chatgpt的网站的。
> 
> 我先给他发了要处理的数据，然后让他处理，他说我没发给他，离谱

你试试在该会话的设置里配置全局prompt，要求它记录数据什么的。

**Comment by muxinxy** [comment]
ChatGPT不能处理文件，只能处理文本

**Comment by undefinedcodezhong** [comment]
你说的是web版还是模拟api操作？web版是可以记住上下文的，api本身是没有上下文的，需要自己提供上下文
![image](https://github.com/zhile-io/pandora/assets/40236765/add8fef3-898a-4203-92bd-86b51bb314ac)

**Comment by Joackk** [comment]
> ChatGPT不能处理文件，只能处理文本

都没发文件的选项，我当然是给他的文本啊

**Comment by Joackk** [comment]
> 你说的是web版还是模拟api操作？web版是可以记住上下文的，api本身是没有上下文的，需要自己提供上下文 ![image](https://user-images.githubusercontent.com/40236765/273783098-add8fef3-898a-4203-92bd-86b51bb314ac.png)

服务模式启动的web版本，也是这样操作的，先发给他，然后告诉他处理上面的数据，但是她告诉我没有，我是直接pytyhon环境启动的，-s这样启动的，是加了什么特殊设置吗？也可能是发的文本有点乱让他认不出来

**Comment by undefinedcodezhong** [comment]
@Joackk 我也是python -s启动的，是你发的文本太长导致遗忘token了？web版还没遇到过很明显的遗忘上下文情况，你试试短文本会不会遇到你说的情况，或者给个无隐私的记录截图看看

**Comment by Joackk** [comment]
> @Joackk 我也是python -s启动的，是你发的文本太长导致遗忘token了？web版还没遇到过很明显的遗忘上下文情况，你试试短文本会不会遇到你说的情况，或者给个无隐私的记录截图看看

重新试了下，短一些的可以，估计是上次太长了，而且有些乱，感谢
