### ISSUE TITLE
access_denied Your version of the ChatGPT app is out of date

### ISSUE THREAD

**Issue by JokerChenX** [zhile-io/pandora#141]
cloud模式下，账号密码登录
页面显示
{"detail":"access_denied: Your version of the ChatGPT app is out of date. Please update to the newest build of the app."}

**Comment by Jerry-Terrasse** [comment]
我也遇到了，不过按照README所说，可以先用官方的登录然后直接访问[这里](http://chat.openai.com/api/auth/session)拿到access token
> 也可以官方登录，然后访问 [这里](http://chat.openai.com/api/auth/session) 拿 Access Token

**Comment by zhile-io** [comment]
已修复。
