### ISSUE TITLE
这个地址不能变吗？

### ISSUE THREAD

**Issue by lnsane** [zhile-io/pandora#142]
https://github.com/zhile-io/pandora/blob/79153d2fb3682505db78f77108003d8dc4aded19/src/pandora/exts/config.py#L15

我看请求都到这个地址，这个地址的项目开源吗？

**Comment by ludashi2020** [comment]
大概率是闭源的，这是核心技术。

**Comment by zhile-io** [comment]
能的，这是默认的地址。你可以通过环境变量更改，具体查看项目文档。

**Comment by lnsane** [comment]
> 能的，这是默认的地址。你可以通过环境变量更改，具体查看项目文档。

我改成自己的地址，那边这个地址对应80的端口要部署哪个项目？是这个项目还是cluod的？我有点懵逼

**Comment by lnsane** [comment]
> fakeopen

/token/register 代码逻辑没有开源？
