### ISSUE TITLE
Pool Token的情况下，ChatGPT 会话去哪里了，以及隔离与否的表现形式？

### ISSUE THREAD

**Issue by kitaev-chen** [zhile-io/pandora#143]
使用场景：用多个 access token 生成多个 share token，用多个 share token 生成一个 pool token。然后将该 pool token 作为 api key 在其他项目中使用，比如 ChatGPT Next Web。

**问题1：**
ChatGPT Next Web 可正常使用，正常开启多个会话。**但对应的 ChatGPT 账号中，没有新建任何会话**。

**这其实是我想要的**，毕竟不希望 ChatGPT 账号中同步记录这些会话，会很乱。但原理上不是很理解，按理说 pandora 将 ChatGPT 网页反馈封装成 api 的形式，ChatGPT 应该会记录这些访问内容才对，希望能从原理上理解没有记录的原因。

**问题2：**
该 pool token 生成的时候是采用脚本，似乎没看到代码中有 “是否会话无需隔离” 的参数传递，是否脚本刷新时候，默认就是隔离的？注意到网页上操作，默认是 “会话无需隔离”。

“会话无需隔离” 这个选项，意思上明白，但实际表现上，对于共享 pool token 的多个用户，有什么不同？

比如大家都本地使用 ChatGPT Next Web，共享 pool token，似乎每个用户的会话都是各是各的，没看到串台的情况。而底层的 ChatGPT 账号，也并未保存任何用户使用 pool token 发起会话的内容，谈不上什么隔离不隔离的。

**Comment by undefinedcodezhong** [comment]
ChatGPT next web 是面向api操作的，它本身就不会向官网请求历史会话（因为对api调用方式来说历史会话是不存在的），虽然它允许用户设置云同步，但那个也只是同步用户本地的会话历史，所以不会出现串台。
至于为什么使用pool token后在ChatGPT上不会看到新建会话，不确定作者是否进行了在调用完会话后自动向ChatGPT发送删除会话记录的操作。

**Comment by kitaev-chen** [comment]
嗯有道理，如果有指令可以删除ChatGPT的话，那确实不会留下什么记录。

关于历史会话那个，我后来稍微有点清楚了。API调用方式确实不会有历史会话，除非代码中设置保存，ChatGPT Next Web 里面有设置 max token 和 attach msg count，后者就是配置历史会话数的。
