### ISSUE TITLE
这是啥情况啊？

### ISSUE THREAD

**Issue by lnsane** [zhile-io/pandora#146]
![image](https://github.com/zhile-io/pandora/assets/20310872/ee59609e-2d41-4dc1-9145-0daa7ed45701)

**Comment by undefinedcodezhong** [comment]
https://community.openai.com/t/gpt-4-through-api-says-its-gpt-3/286881/2
因为辨别模型是不是gpt4，不能直接问，它的数据集没有告诉它是谁，去网上搜一下分辨gpt4的智力题
