### ISSUE TITLE
在阿里云使用 docker 搭建的, 项目可以启动但是聊天没有响应,默认配置,请问是需要改其他的配置吗?

### ISSUE THREAD

**Issue by 805131398** [zhile-io/pandora#149]
<img width="1492" alt="image" src="https://github.com/zhile-io/pandora/assets/31980378/8879ef9e-2b1f-42e7-bcbf-771b6f12f4ce">

提示这个: 
An error occurred. Either the engine you requested does not exist or there was another issue processing your request. If this issue persists please contact us through our help center at help.openai.com.

 出现错误。您请求的引擎不存在，或者在处理您的请求时出现其他问题。如果此问题仍然存在，请通过我们的帮助中心help.openai.com与我们联系。

**Comment by ilfann** [comment]
看下账号有问题吗

**Comment by 805131398** [comment]
> 看下账号有问题吗

帐号正常, 挂梯子可以在本机使用,key 也可以的
