### ISSUE TITLE
GPT4-DALL·E 3 图片无法正常显示

### ISSUE THREAD

**Issue by i-yuanfang** [zhile-io/pandora#153]
如图，无法正常显示，在官方openai 窗口中可以正常显示图片
![1696993409163](https://github.com/zhile-io/pandora/assets/18746924/4b6821ab-6bac-4032-8f62-3d6d75356288)
![1696993895203](https://github.com/zhile-io/pandora/assets/18746924/7639d25d-2e81-4027-b892-e41dc881fe17)

**Comment by zhheo** [comment]
遇到了相同问题+1

**Comment by tdouguo** [comment]
<img width="866" alt="image" src="https://github.com/zhile-io/pandora/assets/22972345/49de52c6-2104-48a3-a9ea-a6e313148f37">

**Comment by luozhiguo12** [comment]
等作者适配

**Comment by Sember2023** [comment]
这个DallE3 是已经在ChatGPT上推出了，还是插件，还是在实验室

**Comment by luozhiguo12** [comment]
> 这个DallE3 是已经在ChatGPT上推出了，还是插件，还是在实验室

已经出来了，在alpha那里，主要是识图和输出图。

**Comment by geekhuashan** [comment]
坐等适配，话说是不是项目最近一个月，没有更新了啊

**Comment by i-yuanfang** [comment]
> > > 这个DallE3 是已经在ChatGPT上推出了，还是插件，还是在实验室
> > 
> > 
> > 已经出来了，在alpha那里，主要是识图和输出图。
> 
> 那这个alpha又在哪里

官方和pandora（fakegpt）有所差异，前提是需要先开通GPT4 PLUS 

官方入口，新建窗口后
![Dingtalk_20231012103555](https://github.com/zhile-io/pandora/assets/18746924/123e5e4a-6c94-4a20-8ad3-88ab81cf4997)


pandora（fakegpt）新建窗口第三个选项
![Dingtalk_20231012103626](https://github.com/zhile-io/pandora/assets/18746924/85a2322e-b720-4a4e-96a4-2ffcc51f8eaf)

**Comment by Sember2023** [comment]
现在pandora项目的图片上传和dalle3都有了，账密登录也可以了
