### ISSUE TITLE
get token网站打不开

### ISSUE THREAD

**Issue by maggieqnr** [zhile-io/pandora#154]
readme.md 里面的第二个（https://ai...fakeopen.com/auth）可以打开，但装上插件后点击获取token时网页打不开、第三个get token的网站也无法打开。

**Comment by manongj** [comment]
会不会是被墙？
我通过“官方登录，然后访问 [这里](http://chat.openai.com/api/auth/session) 拿”，可以获取。而且觉得官方会稳定一点？

**Comment by zhile-io** [comment]
如果方便的话，能不能配一些截图？

**Comment by 1508103369** [comment]
![image](https://github.com/zhile-io/pandora/assets/58204103/a3ad1274-4e03-4a23-adf3-e2bed4993963)
我也无法获取token了
点击完登录就卡顿

**Comment by luozhiguo12** [comment]
> ![搜狗截图20231011231200](https://github.com/zhile-io/pandora/assets/146079448/0e84fea9-293e-4347-8dc0-73f91e34bdd8)
> 

官网的有墙，你得上梯子。
可以直接用README里的第三个，直接走作者网站拿token

**Comment by zhile-io** [comment]
直接到https://ai.fakeopen.com/auth1或官方拿吧，插件的方法失效了。
