### ISSUE TITLE
能否增加一个只有账号和密码登录成功后才能使用的页面

### ISSUE THREAD

**Issue by xboy734** [zhile-io/pandora#155]
全部部署好后，发现和https://chat.zhile.io的内容一样，
我想将网站部署在服务器上，为了各种安全，能否配置成需要账号和密码才能使用，账号和密码是自己提前写入文件或数据库的。
token是提前配置好了的

**Comment by zhile-io** [comment]
你那是为了安全吗？不是为了二次售卖？
