### ISSUE TITLE
chatgpt官网在GPT-4的default里面已经支持上传图片功能，除此之外，添加了DALL.E3绘图功能，希望博主受累在该项目里面添加该功能

### ISSUE THREAD

**Issue by lugaochao** [zhile-io/pandora#159]
<img width="650" alt="iShot_2023-10-13_10 59 08" src="https://github.com/zhile-io/pandora/assets/30764488/0a43196c-d163-469e-b2eb-55dff44297de">
<img width="842" alt="iShot_2023-10-12_16 21 14" src="https://github.com/zhile-io/pandora/assets/30764488/198a0aa4-e3ef-445a-8efc-32ec7e778620">

**Comment by xaswq** [comment]
辛苦博主了，期待更新，感谢感谢！

**Comment by fucheng830** [comment]
辛苦了！

**Comment by jianwi** [comment]
+1，博主辛苦了。

**Comment by happigs** [comment]
没错，感觉升级变化挺大，画画再也不用找mj了  十分方便
要是能支持封装传图片的API，那就更牛了，现在官方API还不知道啥时候可以

**Comment by crazyit** [comment]
+1 群主辛苦了

**Comment by rui12366B** [comment]
+1 博主辛苦了

**Comment by Sember2023** [comment]
现在图片上传和dalle3都有了，甚至恢复了账密登录（我这里是可以的不知道你们那边有没有）

**Comment by Sember2023** [comment]
就是UI界面好像变了，原来是圆弧形的，现在和官网界面一样（不过速度感觉比原来要快一点）

**Comment by zhile-io** [comment]
已更新
