### ISSUE TITLE
fakeopen.com

### ISSUE THREAD

**Issue by litongjava** [zhile-io/pandora#160]
https://ai-20230625.fakeopen.com

1.fakeopen.com代理的是那个网站,我可以绕过 fakeopen.com 调用chatgpt官方的网站吗?
2.fakeopen.com 是开源的吗?我可以自己部署一份吗?

**Comment by LaiBaoYuan** [comment]
代理现在是没有开源的，我也希望作者能够开源🥹

**Comment by MrLiuGangQiang** [comment]
> https://ai-20230625.fakeopen.com
> 
> 1.fakeopen.com代理的是那个网站,我可以绕过 fakeopen.com 调用chatgpt官方的网站吗? 2.fakeopen.com 是开源的吗?我可以自己部署一份吗?

go-chatgpt-api了解一下 可以的

docker run -d \
--name=chatapi \
--restart=always \
-v /etc/localtime:/etc/localtime \
-e GO_CHATGPT_API_PANDORA=1 \
-p 28080:8080 \
linweiyuan/go-chatgpt-api

**Comment by litongjava** [comment]
@MrLiuGangQiang 如果在国外,是不是可以使用chatpgt官方的服务,无需使用go-chatgpt-api或者[fakeopen.com](https://ai-20230625.fakeopen.com/)

**Comment by zhile-io** [comment]
> https://ai-20230625.fakeopen.com
> 
> 1.fakeopen.com代理的是那个网站,我可以绕过 fakeopen.com 调用chatgpt官方的网站吗? 2.fakeopen.com 是开源的吗?我可以自己部署一份吗?

1. 代理的是 `chat.openai.com` 原则上大家都可以做。
2. 并没有开源，我想这是`fakeopen.com`从一开始持续活到现在的一个总要原因。
