### ISSUE TITLE
/auth/platform/login 接口咨询

### ISSUE THREAD

**Issue by undefinedcodezhong** [zhile-io/pandora#164]
感谢作者的工作。
/auth/login 和 /auth/refresh 接口目前能用，不过 /auth/platform/login 和 /auth/platform/refresh 接口还不行，会报500错误，{"detail":"error login"}  ，请问这两个接口的修复在计划中吗？

**Comment by pretenderlu** [comment]
> 感谢作者的工作。 /auth/login 和 /auth/refresh 接口目前能用，不过 /auth/platform/login 和 /auth/platform/refresh 接口还不行，会报500错误，{"detail":"error login"} ，请问这两个接口的修复在计划中吗？

大佬，你的自动刷新脚本活了吗，哈哈~~

**Comment by undefinedcodezhong** [comment]
@pretenderlu 那个能用了，有人做了改进版：https://github.com/mufeng510/Free-ChatGPT-API

**Comment by pretenderlu** [comment]
@undefinedcodezhong 嗯，好嘞，我去看看~~

**Comment by zhile-io** [comment]
> 感谢作者的工作。
> /auth/login 和 /auth/refresh 接口目前能用，不过 /auth/platform/login 和 /auth/platform/refresh 接口还不行，会报500错误，{"detail":"error login"} ，请问这两个接口的修复在计划中吗？

在修复计划中。目前登录接口稳定性在观测中，稳定之后会修复这些。

**Comment by undefinedcodezhong** [comment]
> > 感谢作者的工作。
> > /auth/login 和 /auth/refresh 接口目前能用，不过 /auth/platform/login 和 /auth/platform/refresh 接口还不行，会报500错误，{"detail":"error login"} ，请问这两个接口的修复在计划中吗？
> 
> 在修复计划中。目前登录接口稳定性在观测中，稳定之后会修复这些。

好的！辛苦了大佬！

**Comment by pretenderlu** [comment]
> @pretenderlu 那个能用了，有人做了改进版：https://github.com/mufeng510/Free-ChatGPT-API

今天试的时候好像又不行了🥴

**Comment by Somnus1437** [comment]
我也测试了，也不行

**Comment by hansonhantong** [comment]
这个接口和pamdora一样的嘛，https://github.com/zhile-io/pandora/blob/master/doc/HTTP-API.md#apiconversationconversation_id

**Comment by undefinedcodezhong** [comment]
> 这个接口和pandora一样的嘛，https://github.com/zhile-io/pandora/blob/master/doc/HTTP-API.md#apiconversationconversation_id

不是一个目的

**Comment by kitaev-chen** [comment]
> > 感谢作者的工作。
> > /auth/login 和 /auth/refresh 接口目前能用，不过 /auth/platform/login 和 /auth/platform/refresh 接口还不行，会报500错误，{"detail":"error login"} ，请问这两个接口的修复在计划中吗？
> 
> 在修复计划中。目前登录接口稳定性在观测中，稳定之后会修复这些。

奇了个怪了，我已经转而手动更新access token了，但感觉没几天就不能用了，过期日是默认选项0。
我就是去那几个网站转share token什么的，看到share token跟以前一样就没走pool token的流程了。当时也立即恢复能用了，过几天就不行了。是我流程没走完，还是什么别的原因？太频繁了累死了。

**Comment by kitaev-chen** [comment]
> > 感谢作者的工作。
> > /auth/login 和 /auth/refresh 接口目前能用，不过 /auth/platform/login 和 /auth/platform/refresh 接口还不行，会报500错误，{"detail":"error login"} ，请问这两个接口的修复在计划中吗？
> 
> 在修复计划中。目前登录接口稳定性在观测中，稳定之后会修复这些。

最近好像是挺不稳定的，刚手动刷新的token没几天又不能用了。登录账号后发现有极其繁琐的图像或者声音验证，验证成功后，多登录几个账号后就又开始要求验证了，没完没了了属于是。
