### ISSUE TITLE
在vercel上自部署的serverless网页版怎么更新，获取对DALL·E 3的适配支持？

### ISSUE THREAD

**Issue by JerryWesler** [zhile-io/pandora#166]
我看到博主提供的链接是可以用DALL·E 3，但是自部署的目前还是报错。想知道怎么升级获取最新的支持，谢谢。
<img width="711" alt="Snipaste_2023-10-14_13-40-21" src="https://github.com/zhile-io/pandora/assets/44219765/c8105811-3e9c-4d3d-8500-6da81a803ee0">

**Comment by zhile-io** [comment]
vercel 那边 redeploy 一下即可。
