### ISSUE TITLE
如何更新目前pandora的版本

### ISSUE THREAD

**Issue by Jasone1-3** [zhile-io/pandora#170]
我用的是命令pip install pandora-chatgpt 安装的1.18版本的
![image](https://github.com/zhile-io/pandora/assets/116706300/8a5f37af-2d0b-4525-9bee-28959180c455)
不想用docker的方式，直接用命令也不能更新

**Comment by undefinedcodezhong** [comment]
加-U 或 --upgrade参数：`pip install -U pandora-chatgpt`

**Comment by Jasone1-3** [comment]
> 加-U 或 --upgrade参数：`pip install -U pandora-chatgpt[cloud]`

![image](https://github.com/zhile-io/pandora/assets/116706300/5b590e8b-0526-495c-acb2-9d28f24028f4)
哥还是不行

**Comment by zhile-io** [comment]
> > 加-U 或 --upgrade参数：`pip install -U pandora-chatgpt[cloud]`
> 
> ![image](https://user-images.githubusercontent.com/116706300/275315960-5b590e8b-0526-495c-acb2-9d28f24028f4.png) 哥还是不行

不建议使用国内镜像源，要花挺久才能同步到最新的。

`pip install -U -i https://pypi.org/simple pandora-chatgpt[cloud]`

**Comment by undefinedcodezhong** [comment]
你要升级的不是cloud版嘛，你倒是把cloud加上啊

**Comment by Jasone1-3** [comment]
> 你要升级的不是cloud版嘛，你倒是把cloud加上啊

![image](https://github.com/zhile-io/pandora/assets/116706300/974cc935-ed78-40d9-92e8-1d3ab9898fe9)
哥还是连不上去，我挂梯子的。不影响吧

**Comment by undefinedcodezhong** [comment]
挂梯就开全局，实在不行就pip uninstall掉再重装 😂

**Comment by Jasone1-3** [comment]
> 挂梯就开全局，实在不行就pip uninstall掉再重装 😂

感谢哥的帮助，虽然没解决问题但是有思路了
![image](https://github.com/zhile-io/pandora/assets/116706300/398e35c7-ffcc-4938-a114-04945ee463d3)
我修改了指向映射的文件，
![image](https://github.com/zhile-io/pandora/assets/116706300/914e9deb-c8f9-4282-aa1b-07aba7fc4f45)

**Comment by zhile-io** [comment]
> > 挂梯就开全局，实在不行就pip uninstall掉再重装 😂
> 
> 感谢哥的帮助，虽然没解决问题但是有思路了 ![image](https://user-images.githubusercontent.com/116706300/275318228-398e35c7-ffcc-4938-a114-04945ee463d3.png) 我修改了指向映射的文件， ![image](https://user-images.githubusercontent.com/116706300/275318257-914e9deb-c8f9-4282-aa1b-07aba7fc4f45.png)

我给你的命令你到底试一试啊。

**Comment by Jasone1-3** [comment]
> > > 挂梯就开全局，实在不行就pip uninstall掉再重装 😂
> > 
> > 
> > 感谢哥的帮助，虽然没解决问题但是有思路了 ![image](https://user-images.githubusercontent.com/116706300/275318228-398e35c7-ffcc-4938-a114-04945ee463d3.png) 我修改了指向映射的文件， ![image](https://user-images.githubusercontent.com/116706300/275318257-914e9deb-c8f9-4282-aa1b-07aba7fc4f45.png)
> 
> 我给你的命令你到底试一试啊。

![image](https://github.com/zhile-io/pandora/assets/116706300/6317c34d-428b-4eac-8019-f270566be046)
这个还是老样子

**Comment by zhile-io** [comment]
> > > > 挂梯就开全局，实在不行就pip uninstall掉再重装 😂
> > > 
> > > 
> > > 感谢哥的帮助，虽然没解决问题但是有思路了 ![image](https://user-images.githubusercontent.com/116706300/275318228-398e35c7-ffcc-4938-a114-04945ee463d3.png) 我修改了指向映射的文件， ![image](https://user-images.githubusercontent.com/116706300/275318257-914e9deb-c8f9-4282-aa1b-07aba7fc4f45.png)
> > 
> > 
> > 我给你的命令你到底试一试啊。
> 
> ![image](https://user-images.githubusercontent.com/116706300/275318450-6317c34d-428b-4eac-8019-f270566be046.png) 这个还是老样子

连接你本地的代理失败。

`pip install -U -i https://pypi.org/simple pandora-chatgpt[cloud]==1.3.4`

强制指定版本试试。

**Comment by Jasone1-3** [comment]
> > > > > 挂梯就开全局，实在不行就pip uninstall掉再重装 😂
> > > > 
> > > > 
> > > > 感谢哥的帮助，虽然没解决问题但是有思路了 ![image](https://user-images.githubusercontent.com/116706300/275318228-398e35c7-ffcc-4938-a114-04945ee463d3.png) 我修改了指向映射的文件， ![image](https://user-images.githubusercontent.com/116706300/275318257-914e9deb-c8f9-4282-aa1b-07aba7fc4f45.png)
> > > 
> > > 
> > > 我给你的命令你到底试一试啊。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/116706300/275318450-6317c34d-428b-4eac-8019-f270566be046.png) 这个还是老样子
> 
> 连接你本地的代理失败。
> 
> `pip install -U -i https://pypi.org/simple pandora-chatgpt[cloud]==1.3.4`
> 
> 强制指定版本试试。

![image](https://github.com/zhile-io/pandora/assets/116706300/af94603b-ed85-41dc-9816-b638811cab73)

**Comment by zhile-io** [comment]
> > > > > > 挂梯就开全局，实在不行就pip uninstall掉再重装 😂
> > > > > 
> > > > > 
> > > > > 感谢哥的帮助，虽然没解决问题但是有思路了 ![image](https://user-images.githubusercontent.com/116706300/275318228-398e35c7-ffcc-4938-a114-04945ee463d3.png) 我修改了指向映射的文件， ![image](https://user-images.githubusercontent.com/116706300/275318257-914e9deb-c8f9-4282-aa1b-07aba7fc4f45.png)
> > > > 
> > > > 
> > > > 我给你的命令你到底试一试啊。
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/116706300/275318450-6317c34d-428b-4eac-8019-f270566be046.png) 这个还是老样子
> > 
> > 
> > 连接你本地的代理失败。
> > `pip install -U -i https://pypi.org/simple pandora-chatgpt[cloud]==1.3.4`
> > 强制指定版本试试。
> 
> ![image](https://user-images.githubusercontent.com/116706300/275319447-af94603b-ed85-41dc-9816-b638811cab73.png)

Cannot connect to proxy 你的梯子是有问题的。 执行 pip install -U pip 先把你pip版本升级一下再说。
