### ISSUE TITLE
NGINX 反代Cloud模式携带TOKEN免登录访问

### ISSUE THREAD

**Issue by onenov** [zhile-io/pandora#171]
**在部署好Cloud模式之后使用NGINX反向代理IP+端口，在NGINX反向代理配置中添加：**

```
add_header Set-Cookie "access-token=你的Access Token; Path=/; SameSite=None; Secure";
```

将**你的Access Token**替换为获取到的 Access Token ，然后访问域名即可通过NGINX来载入Access Token。

**缺点是首次访问会跳转到 /auth/login 登录页面，需要再次回到主域名。**

但是可以通过`sub_filter`插入一个JS来解决，在NGINX反向代理配置中添加
```
    proxy_set_header Accept-Encoding "";
    sub_filter '</head>' '<script src="https://你的JS地址/pandora.js"></script></head>';
    sub_filter_once off;
```
将你的pandora.js放到一个能公网访问的地方（COS啥的），`https://你的JS地址/pandora.js`更改为你的JS文件地址

**在`pandora.js`中写入重定向规则：**
```
window.onload = function() {
    // 获取当前地址
    var currentUrl = window.location.href;
    // 检查当前地址是否为登陆页面
    if (currentUrl === "https://pandora.域名/auth/login") {
        // 如果是，则重定向到首页
        window.location.href = "https://pandora.域名/";
    }
}
```
这样就能在访问Cloud模式的Pandora携带Access Token并自动登录了，**同理，也可以直接在JS中添加Cookie来写入access-token**：
```
document.cookie = 'access-token=你的Access Token;  path=/';
```

这样就实现简单的Cloud模式携带TOKEN免登录访问。

**Comment by jianwi** [comment]
是不是可以直接在nginx里写上js代码？

**Comment by onenov** [comment]
似乎不行
________________________________
发件人: Dujianjun ***@***.***>
发送时间: 2023年10月16日 14:09
收件人: zhile-io/pandora ***@***.***>
抄送: NAN LI ***@***.***>; Author ***@***.***>
主题: Re: [zhile-io/pandora] NGINX 反代Cloud模式携带TOKEN免登录访问 (Issue #171)


是不是可以直接在nginx里写上js代码？

―

**Comment by Somnus1437** [comment]
是真的不行，我也试过了

**Comment by asdfsadfjlkasndf** [comment]
可以试试直接使用frp进行反代

**Comment by zhile-io** [comment]
请使用share token
