### ISSUE TITLE
pandora -s http加载dalle3无法加载图片

### ISSUE THREAD

**Issue by AuditAIH** [zhile-io/pandora#173]
我用的是Pandora -s启动的 也安装了cloud
系统是Linux centos8 本地Python部署的
cloud模式可以加载图片 但是直接web启动不能
通过存储过的token文件登录 web browsing模式正常
作者大大可以帮帮忙嘛 感谢～
![Uploading IMG_0761.jpeg…]()

**Comment by jianwi** [comment]
https://github.com/zhile-io/pandora/issues/171

你要不试试这个

**Comment by Mzaxd** [comment]
我这边是只有cloud模式才能正常使用所有功能 http模式只能使用普通的3.5和4的对话
