### ISSUE TITLE
docker版本pandora更新版本到最新后页面还是原来的样式

### ISSUE THREAD

**Issue by will15980** [zhile-io/pandora#174]
![1111222](https://github.com/zhile-io/pandora/assets/16914827/48f8331b-fd44-488a-a568-e7a602bc04f8)
![222336](https://github.com/zhile-io/pandora/assets/16914827/ca0e4f69-cdcc-457f-a6d3-2631675305f9)

docker-compose pull pandora 更新后启动版本已经是1.3.4但是前端页面好像还是老样式，请问要如何才能同步到最新的样式版本

**Comment by zhile-io** [comment]
cloud模式会是最新ui
