### ISSUE TITLE
我想通过接口进行4v的上传图片和接收消息

### ISSUE THREAD

**Issue by isJN** [zhile-io/pandora#175]
如题,有哪位大佬可以解答下我的疑惑

**Comment by xaswq** [comment]
目前还没有吧，这个估计很难

**Comment by isJN** [comment]
我个人抓包得到https://chat.openai.com/files和https://fileserviceuploadsperm.blob.core.windows.net/files/这两个接口应该是用作上床的,第一个正常返回编号,但是进行第二个请求上传的时候怎么都不行返回的是Authentication information is not given in the correct format. Check the value of Authorization header.
