### ISSUE TITLE
请问大佬vercel部署，能把access token写入到环境变量里吗？

### ISSUE THREAD

**Issue by JerryWesler** [zhile-io/pandora#177]
自部署给朋友用，还是希望免去输入access token这一步

**Comment by zhile-io** [comment]
有更好的实现方式，可以参考[这里](https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#基础信息-3)的文档。
简单来说就是生成一个控制能力更强的Share Token，然后拼接在地址上发送给你的朋友。他们点开即可访问。
