### ISSUE TITLE
如何搭建与作者一样的共享网站

### ISSUE THREAD

**Issue by Pride-lee** [zhile-io/pandora#178]
我想搭建一个和作者共享网站chat-shared.zhile.io功能一样的要怎么搞?
作者的网站也被墙了，自己有账号想搭建一个免登录且会话隔离的网站给同事和朋友用

**Comment by yuwangi** [comment]
可以直接参考 ：https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E7%A1%80%E4%BF%A1%E6%81%AF-3

**Comment by Somnus1437** [comment]
我看到的最好的目前是ylsapp.com，我一直在研究怎么做出来怎么不用登录就能访问。nginx研究不明白，怎么免去登录的介绍文章一直找不到

**Comment by zhile-io** [comment]
<img width="908" alt="image" src="https://github.com/zhile-io/pandora/assets/144572553/5181872e-e2ab-4961-b600-f0c2e8eb7c43">

一个链接就能访问。
