### ISSUE TITLE
问题：大佬，请问 share token可以也做负载吗？

### ISSUE THREAD

**Issue by yuwangi** [zhile-io/pandora#181]
情况描述：目前有大约80人左右再用 share token 模式访问 fake ，想多加 plus 账号做负载，最好是 能做到 pool 池那样，但是pool 池只支持 api ,请问有什么办法吗？
![image](https://github.com/zhile-io/pandora/assets/13346477/9e094043-d43e-4bc5-b029-ccfa5b0a8a90)

**Comment by ccpjcmjs** [comment]
蹲一个解决方案

**Comment by zhile-io** [comment]
不能的，这里会有很多会话记录的问题。
