### ISSUE TITLE
网址似乎访问不了了

### ISSUE THREAD

**Issue by 1592363624** [zhile-io/pandora#188]
网址似乎访问不了了

**Comment by zouguoweigo** [comment]
same issue

**Comment by MC-XiaoHei** [comment]
same issue

**Comment by ALEXsun0** [comment]
[](https://chat.zhile.io/)好像被墙了？science能连

**Comment by 1592363624** [comment]
> https://chat.zhile.io/好像被墙了？science能连

啊这  岂不是太难受了

**Comment by zhile-io** [comment]
https://chat1.zhile.io
