### ISSUE TITLE
网站似乎打不开了

### ISSUE THREAD

**Issue by Thewind0603** [zhile-io/pandora#189]

**Comment by hayruler** [comment]
我也打不开了

**Comment by zhile-io** [comment]
被墙了

**Comment by hayruler** [comment]
如果想使用gpt 还有什么其他方法吗😖



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月19日(周四) 晚上7:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhile-io/pandora] 网站似乎打不开了 (Issue #189)




 
被墙了

**Comment by zhile-io** [comment]
> 如果想使用gpt 还有什么其他方法吗😖
> […](#)

先开个梯好了
