### ISSUE TITLE
Hmm...something seems to have gone wrong

### ISSUE THREAD

**Issue by ImMALWARE** [zhile-io/pandora#193]
When you use chat.zhile.io with working api key or using API with any working token, there is always error: {"error":{"message":"Hmm...something seems to have gone wrong.","type":"requests","param":"fk-U_T3W-4fTdHmERft31oDJbs********************","code":null}}

**Comment by tree-eighteen** [comment]
openai它自己的网站都用不了。

![image](https://github.com/zhile-io/pandora/assets/41732381/31b9983d-7e21-4503-b869-b11ff8980281)

**Comment by sunwukong2021** [comment]
救救孩子吧，不能用是真难受啊

**Comment by Peterzion89** [comment]
顶你个肺，，

**Comment by xbmlz** [comment]
```json
{"cf_details":"Something went wrong. Please contact Support.", "type":"dc"}
```

**Comment by xbmlz** [comment]
```json
{"detail":"Hmm...something seems to have gone wrong."}
```

**Comment by bbsGod** [comment]
那就等等吗

**Comment by jp-github** [comment]
![image](https://github.com/zhile-io/pandora/assets/83535157/154180c3-b3cc-43a7-a1a7-8aedf81ba523)

**Comment by tb520912** [comment]
官网能用了呀

**Comment by s181462537** [comment]
官方的api也用不了

**Comment by jp-github** [comment]
官方我可以用的，zhile的可以登录、查看历史消息，可是不能询问

**Comment by lfz-5** [comment]
> openai它自己的网站都用不了。
> 
> ![image](https://user-images.githubusercontent.com/41732381/276782537-31b9983d-7e21-4503-b869-b11ff8980281.png)

求问这是什么网站

**Comment by hwccurry** [comment]
呜呜呜，害怕

**Comment by undefinedcodezhong** [comment]
> > openai它自己的网站都用不了。
> > ![image](https://user-images.githubusercontent.com/41732381/276782537-31b9983d-7e21-4503-b869-b11ff8980281.png)
> 
> 求问这是什么网站

https://status.openai.com/
