### ISSUE TITLE
Hmm...something seems to have gone wrong.

### ISSUE THREAD

**Issue by LaiBaoYuan** [zhile-io/pandora#194]
这咋办呀

**Comment by onecloud-codigger** [comment]
I don't know what's wrong. I just saw that several issues with more comments were closed by the author, but the author has not issued a new announcement for the time being

**Comment by zhheo** [comment]
我也遇到了
<img width="1003" alt="image" src="https://github.com/zhile-io/pandora/assets/33177975/6dc8e544-16d4-4412-8a52-e2c6d4df9e44">

**Comment by zpc-dragon** [comment]
It has been a long time from this morning
