### ISSUE TITLE
快回来吧

### ISSUE THREAD

**Issue by henghengkan** [zhile-io/pandora#195]
哦！我的潘多拉啊，你怎么崩了呜呜

**Comment by dalefeng** [comment]
我不能失去我的潘多拉呜呜

**Comment by fgott** [comment]
https://ai-20231019.fakeopen.com/api/aip/p?offset=0&limit=250&is_installed=true     401 错误
https://ai-20231019.fakeopen.com/api/conversation   418错误。

是接口发生改变吗？

**Comment by wj2008** [comment]
我这边也是418了

**Comment by nikefu** [comment]
网站访问不了了

**Comment by henghengkan** [comment]
> https://ai-20231019.fakeopen.com/api/aip/p?offset=0&limit=250&is_installed=true 401 错误 https://ai-20231019.fakeopen.com/api/conversation 418错误。
> 
> 是接口发生改变吗？

反正现在接口肯定是用不了了

**Comment by fgott** [comment]
> > https://ai-20231019.fakeopen.com/api/aip/p?offset=0&limit=250&is_installed=true 401 错误 https://ai-20231019.fakeopen.com/api/conversation 418错误。
> > 是接口发生改变吗？
> 
> 反正现在接口肯定是用不了了

昨天才想着 退给朋友用，今天就出意外了。

**Comment by onecloud-codigger** [comment]
作者出来关issue了哈哈哈

**Comment by zhile-io** [comment]
> 作者出来关issue了哈哈哈

我关issue不是因为服务恢复了。 openai那边还在抽。

**Comment by henghengkan** [comment]
> > 作者出来关issue了哈哈哈
> 
> 我关issue不是因为服务恢复了。 openai那边还在抽。

up给我的标签是什么啊 T-T
