### ISSUE TITLE
没有潘多拉不能正常工作

### ISSUE THREAD

**Issue by shawokou123** [zhile-io/pandora#196]
没有潘多拉不能正常工作
这会不能用了！不知道什么时间回复

**Comment by zhheo** [comment]
不能用+1

**Comment by 1024981189** [comment]
![image](https://github.com/zhile-io/pandora/assets/57926605/ae023973-64b7-4796-8bc6-a38aaf92d16e)
这可怎么办

**Comment by zhheo** [comment]
> ![image](https://user-images.githubusercontent.com/57926605/276798365-ae023973-64b7-4796-8bc6-a38aaf92d16e.png) 这可怎么办

你这个是被墙了，和项目不能用没太大关系。

**Comment by rongrongrong233** [comment]
😭回来吧我的潘多拉😭
👼我最骄傲的信仰👼
⚡历历在目的年代⚡
😭眼泪莫名在流淌😭
😍我最喜欢的网站😍
🌟它是我灵感的源泉🌟
💻每次访问都充满期待💻
🎐让我的思绪飞扬🎐

**Comment by shawokou123** [comment]
群众的 呼声，说明了这个项目的重要性！！！

**Comment by cachexy123** [comment]
😭回来吧我的潘多拉😭
👼我最骄傲的信仰👼
⚡历历在目的年代⚡
😭眼泪莫名在流淌😭
😍我最喜欢的网站😍
🌟它是我灵感的源泉🌟
💻每次访问都充满期待💻
🎐让我的思绪飞扬🎐

**Comment by liuchaoyang95** [comment]
翻墙之后也登录不上了

**Comment by 1414044032** [comment]
+1

**Comment by 1024981189** [comment]
![image](https://github.com/zhile-io/pandora/assets/57926605/906675fc-f2de-425d-be0f-6b4aede21f38)
😢😢

**Comment by Mzaxd** [comment]
> 翻墙之后也登录不上了

我的能登陆 应该只是潘多拉用不了了 我猜测可能是OpenAI又改认证方式了

**Comment by ShaySheng** [comment]
你快回来. 我一人承受不来

**Comment by MaskerPRC** [comment]
+1

**Comment by randolph555** [comment]
+1

**Comment by xaswq** [comment]
泪目，是不是官方封杀了。。

**Comment by Pzasuki** [comment]
亲爱的作者，网站似乎被墙了，开梯子我还能进😥

**Comment by Lemon-jie** [comment]
没有gpt 我都停工2h 时了

**Comment by kaixindeyouxia** [comment]
但是能查看历史记录，不知道是什么问题

**Comment by shiquda** [comment]
是不是墙了+openai接口出问题了

**Comment by aasheng1** [comment]
??回来吧我的潘多拉??
👼我最自豪的信仰👼⚡
历年在目标年代⚡
??泪莫名在流淌??
😍我最喜欢的网站😍🌟
这是我灵感的源泉🌟💻
每次访问都充满期待
💻🎐让我的思绪飞扬🎐

**Comment by luozhiguo12** [comment]
😭回来吧我的潘多拉😭
👼我最骄傲的信仰👼
⚡历历在目的年代⚡
😭眼泪莫名在流淌😭
😍我最喜欢的网站😍
🌟它是我灵感的源泉🌟
💻每次访问都充满期待💻
🎐让我的思绪飞扬🎐

**Comment by 823302271** [comment]
网站被墙了，开梯子能进，但是目前fajegpt.org访问不了了

**Comment by MaskerPRC** [comment]
好了好了

**Comment by StardustXiaoT** [comment]
啥时候好呀

**Comment by ShaySheng** [comment]
好了，我也能用了。感谢zhile大哥，感谢感谢😭

**Comment by Pzasuki** [comment]
感谢zhile，你就是我的神

**Comment by shawokou123** [comment]
好了？
api base还是，https://ai.fakeopen.com/v1 吗？？？
"api_base": "https://ai.fakeopen.com/v1",

**Comment by onecloud-codigger** [comment]
作者刚回复我说Openai还在抽

**Comment by yaotong1985** [comment]
美好啊现在历史记录都看不到了，只能用梯子访问官网

**Comment by Leewen010601** [comment]
😭回来吧我的潘多拉😭
👼我最骄傲的信仰👼
⚡历历在目的年代⚡
😭眼泪莫名在流淌😭
😍我最喜欢的网站😍
🌟它是我灵感的源泉🌟
💻每次访问都充满期待💻
🎐让我的思绪飞扬🎐

**Comment by ShaySheng** [comment]
> 😭回来吧我的潘多拉😭 👼我最骄傲的信仰👼 ⚡历历在目的年代⚡ 😭眼泪莫名在流淌😭 😍我最喜欢的网站😍 🌟它是我灵感的源泉🌟 💻每次访问都充满期待💻 🎐让我的思绪飞扬🎐

你细看，换了网址了，应该能用了吧

**Comment by Leewen010601** [comment]
> > 😭回来吧我的潘多拉😭 👼我最骄傲的信仰👼 ⚡历历在目的年代⚡ 😭眼泪莫名在流淌😭 😍我最喜欢的网站😍 🌟它是我灵感的源泉🌟 💻每次访问都充满期待💻 🎐让我的思绪飞扬🎐
> 
> 你细看，换了网址了，应该能用了吧

![image](https://github.com/zhile-io/pandora/assets/138188912/124ec267-f6da-4d78-be68-b105061b458f)
能正常登录但是没有回显是什么情况啊请问
