### ISSUE TITLE
大佬们，服务器部署之后经常性出现不能使用是什么问题

### ISSUE THREAD

**Issue by zbl1997-code** [zhile-io/pandora#198]
![1697769895426](https://github.com/zhile-io/pandora/assets/74107460/b6767232-a606-4e76-8af5-5c08670a8df9)

**Comment by xaswq** [comment]
今天挂了

**Comment by zbl1997-code** [comment]
就是昨天刚部署完一整天完全没有问题，今天就出现需要验证，我重新获取了access_token还是一样。chatgpt账号正常，使用梯子也能正常访问官网

**Comment by EdwinOlders11** [comment]
这会儿潘多拉炸了

**Comment by galaxy24** [comment]
openai官网炸了

**Comment by iganb** [comment]
刚刚还能用一下，现在又不行了

**Comment by Jasone1-3** [comment]
> 刚刚还能用一下，现在又不行了

Something went wrong. If this issue persists please contact us through our help center at help.openai.com.
我是这样的就是不能用。大家都一样吗

**Comment by mengxueForgoogle** [comment]
我也一样用不了

**Comment by k1nm0** [comment]
### Error occurred: {"detail":"access_denied: Something went wrong. Please restart the app and try again. If the issue
persists, please reinstall the app. (true)"}
