### ISSUE TITLE
无法使用10.20

### ISSUE THREAD

**Issue by 7BlackJack** [zhile-io/pandora#201]
国内代理 无法访问，要如何解决？ 麻烦 很急！！

**Comment by 7BlackJack** [comment]
![image](https://github.com/zhile-io/pandora/assets/108774643/59c99d23-e54d-4763-a05a-8326a45ae5b6)

**Comment by StardustXiaoT** [comment]
我是页面都能打开 就是用不了 老是弹验证 然后验证完 也还是用不了

**Comment by mayaohua** [comment]
> 国内代理 无法访问，要如何解决？ 麻烦 很急！！

大家都很急，但是你先不要急。
