### ISSUE TITLE
获取获取Access Token失败，Something went wrong. Please restart the app and try again

### ISSUE THREAD

**Issue by mayaohua** [zhile-io/pandora#202]
获取Access Token失败了
access_denied: Something went wrong. Please restart the app and try again. If the issue persists, please reinstall the app. (true)

**Comment by 7BlackJack** [comment]
有图片看一下吗

**Comment by mayaohua** [comment]
> 有图片看一下吗

![image](https://github.com/zhile-io/pandora/assets/24264563/ef9771fa-45ff-44b9-b946-502761d717dd)

![image](https://github.com/zhile-io/pandora/assets/24264563/f01233f0-62d2-4819-a102-3501a970da3c)

**Comment by lfz-5** [comment]
官方（http://chat.openai.com/api/auth/session）的可以获取accessToken 但仍然无法正常使用

**Comment by qyaaaa** [comment]
一样的问题

**Comment by hansonhantong** [comment]
作者怎么不说话了

**Comment by Mashunping** [comment]
一样有解决办法吗

**Comment by y383688728** [comment]
2023/10/18一样的 没得办法了
