### ISSUE TITLE
无法使用share token，报错All connection attempts failed

### ISSUE THREAD

**Issue by AowerDmax** [zhile-io/pandora#204]
pandora版本为1.3.4.部署在一台电脑上，然后通过局域网访问这台电脑上的pandora服务。没有使用127.0.0.1，没有设置https。
在尝试http://10.x.x.170:8899/auth/login_share?token=<your Token>后，报错All connection attempts failed。并且仍在登陆界面

**Comment by zhile-io** [comment]
请排查网络问题
