### ISSUE TITLE
接口https://ai.fakeopen.com/v1/chat/completions请求gpt4模型报错，请求3.5模型可以

### ISSUE THREAD

**Issue by galaxy24** [zhile-io/pandora#207]
接口https://ai.fakeopen.com/v1/chat/completions请求gpt4模型报错，请求3.5模型可以，这是为什么啊
报错信息：{
    "error": {
        "message": "Request is not allowed. Please try again later.",
        "type": "requests",
        "param": "fk-o3AbdhYr_BMw0G8WDr2T8IC********************",
        "code": null
    }
}

**Comment by namezzz** [comment]
是的，我这边也是这个现象，不知道是因为什么。

**Comment by QvQQ** [comment]
+1，插眼

**Comment by nxuu** [comment]
同问+1
