### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by walkskyer** [zhile-io/pandora#208]
access_denied: Something went wrong. Please restart the app and try again. If the issue persists, please reinstall the app. (true)

**Comment by 1832245819** [comment]
解决方法：一、登录官方的chatgpt服务；二、https://chat.openai.com/api/auth/session 获取Token。将 "accessToken": ”（Token）“，后面双引号里面的内容复制。；三、https://chat1.zhile.io/ 通过Token 登录
