### ISSUE TITLE
最新的登陆地址；以及Error: access_denied, Something went wrong. 解决方法

### ISSUE THREAD

**Issue by 1832245819** [zhile-io/pandora#209]
最新的登陆地址：https://chat1.zhile.io/
登录出现以下提示及解决办法。
Error: access_denied, Something went wrong. Please restart the app and try again. If the issue persists, please reinstall the app. (true)
解决方法：一、登录官方的chatgpt服务；二、https://chat.openai.com/api/auth/session 获取Token。将 "accessToken": ”（Token）“，后面双引号里面的内容复制。；三、https://chat1.zhile.io/ 通过Token 登录

**Comment by onecloud-codigger** [comment]
有没有啥方法把accessToken从旧网址同步到新网址

**Comment by 1592363624** [comment]
![Shell截图_20231020163647](https://github.com/zhile-io/pandora/assets/50036597/36e02211-b231-4e35-b22e-a645df91c1bc)
zhe这特么验证是真离谱

**Comment by 1832245819** [comment]
> ![Shell截图_20231020163647](https://user-images.githubusercontent.com/50036597/276873659-36e02211-b231-4e35-b22e-a645df91c1bc.png) zhe这特么验证是真离谱

免费的数据集标注工程师了属于是。

**Comment by 1592363624** [comment]
> > ![Shell截图_20231020163647](https://user-images.githubusercontent.com/50036597/276873659-36e02211-b231-4e35-b22e-a645df91c1bc.png) zhe这特么验证是真离谱
> 
> 免费的数据集标注工程师了属于是。

最可恶的是有10个  第一次搞还是出现了你说的那个报错 第二次登录官网又玩10次 人麻了=.=

**Comment by zhile-io** [comment]
> ![Shell截图_20231020163647](https://user-images.githubusercontent.com/50036597/276873659-36e02211-b231-4e35-b22e-a645df91c1bc.png)
> zhe这特么验证是真离谱

建议用自己账号，不要去shared chat上受折磨啊。

**Comment by 1592363624** [comment]
> > ![Shell截图_20231020163647](https://user-images.githubusercontent.com/50036597/276873659-36e02211-b231-4e35-b22e-a645df91c1bc.png)
> > zhe这特么验证是真离谱
> 
> 建议用自己账号，不要去shared chat上受折磨啊。

我是用的自己的账号

**Comment by zhile-io** [comment]
> > > ![Shell截图_20231020163647](https://user-images.githubusercontent.com/50036597/276873659-36e02211-b231-4e35-b22e-a645df91c1bc.png)
> > > zhe这特么验证是真离谱
> > 
> > 
> > 建议用自己账号，不要去shared chat上受折磨啊。
> 
> 我是用的自己的账号

自己账号怎么会有码啊

**Comment by 1592363624** [comment]
> > > > ![Shell截图_20231020163647](https://user-images.githubusercontent.com/50036597/276873659-36e02211-b231-4e35-b22e-a645df91c1bc.png)
> > > > zhe这特么验证是真离谱
> > > 
> > > 
> > > 建议用自己账号，不要去shared chat上受折磨啊。
> > 
> > 
> > 我是用的自己的账号
> 
> 自己账号怎么会有码啊

那就不清楚了  头一次见这么离谱的验证

**Comment by zhile-io** [comment]
> > > > > ![Shell截图_20231020163647](https://user-images.githubusercontent.com/50036597/276873659-36e02211-b231-4e35-b22e-a645df91c1bc.png)
> > > > > zhe这特么验证是真离谱
> > > > 
> > > > 
> > > > 建议用自己账号，不要去shared chat上受折磨啊。
> > > 
> > > 
> > > 我是用的自己的账号
> > 
> > 
> > 自己账号怎么会有码啊
> 
> 那就不清楚了 头一次见这么离谱的验证

官方登录确实是有码的，今天官方登录把风控等级调的非常高。

**Comment by henghengkan** [comment]
好耶，登上了，爱我的潘多拉 T - T
