### ISSUE TITLE
第三方登陆获取token报错了

### ISSUE THREAD

**Issue by maoshibai** [zhile-io/pandora#213]
也不知道是不是只有第三方登陆会报错。。我是用谷歌账号登陆的
![ChatGPT](https://github.com/zhile-io/pandora/assets/49072001/b1341149-6e25-4196-b544-9c6f969b3415)

**Comment by sau1g0dman** [comment]
我也是同样的问题

**Comment by CHANGEORT** [comment]
Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

**Comment by aaronzgh** [comment]
> Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

+1
开了梯子，使用 ChatGPT Auth Helper 登录到最后会提示这个错误，无法获取到 access token

**Comment by zhile-io** [comment]
第三方登录目前还是去官网拿吧，这个方法失效了。直登可以去 https://ai.fakeopen.com/auth1
