### ISSUE TITLE
{"detail":"access_denied: Something went wrong. Please restart the app and try again. If the issue persists, please reinstall the app. (true)"}

### ISSUE THREAD

**Issue by tohsakarinww** [zhile-io/pandora#216]
{"detail":"access_denied: Something went wrong. Please restart the app and try again. If the issue persists, please reinstall the app. (true)"}
![image](https://github.com/zhile-io/pandora/assets/123134759/afeb67a2-378c-438c-abc9-74cb70a3fa65)

**Comment by jinchengsnow** [comment]
我也是爆这个。如何解决

**Comment by zhile-io** [comment]
修复了
