### ISSUE TITLE
被墙了

### ISSUE THREAD

**Issue by cxzio** [zhile-io/pandora#217]
挂梯子火狐正常，edge access_denied

**Comment by camerayuhang** [comment]
怎么解决呀，现在无法获取access token了

**Comment by hcppxgit** [comment]
应该是官方又改了接口，今天我登陆官方gpt，弹出一个很变态的验证码，要验证6-7次才能登陆，把我都给转晕了

**Comment by zhile-io** [comment]
看置顶
