### ISSUE TITLE
access_denied: Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

### ISSUE THREAD

**Issue by ImMALWARE** [zhile-io/pandora#218]
![image](https://github.com/zhile-io/pandora/assets/53017160/82e959e3-484a-40cd-97a5-61186002c5c0)

**Comment by huajie19890** [comment]
encountered the same problem.

Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

**Comment by danio-peng** [comment]
Same problem here. Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

**Comment by AIinstar** [comment]
Same problem me too

**Comment by danio-peng** [comment]
Problem solved. Get the token from the OpenAI official site.

**Comment by shifuture** [comment]
try :  http://chat.openai.com/api/auth/session  

```json 
{
...
accessToken: "...."   <- copy the code
...
}
```

> Problem solved. Get the token from the OpenAI official site.
