### ISSUE TITLE
获取access token的方式似乎有变更，目前无法获取access token

### ISSUE THREAD

**Issue by malphitee** [zhile-io/pandora#222]
从插件尝试access token，跳转openai进行登陆，会提示需要人机验证
![image](https://github.com/zhile-io/pandora/assets/14119813/369c608f-4f88-43a4-a6c9-cbe78e7d6adb)
![image](https://github.com/zhile-io/pandora/assets/14119813/04026246-5917-437a-995f-d565d0c92628)

逐步完成人机验证后，并没有像往常一样获取到token，而是报错了
![image](https://github.com/zhile-io/pandora/assets/14119813/0d52ec68-1c59-4e25-b88c-037eb418488c)

**Comment by malphitee** [comment]
不好意思，这个号不是常用的github账号，没有点star，刚也补上了，没有不respect的意思哈

**Comment by malphitee** [comment]
另外补充一下描述，目前我是使用仓库里提到的http://chat.openai.com/api/auth/session这个接口获取的token，上面提出的问题是出于反馈疑似谷歌浏览器插件问题的考虑提出的，没有想到会冒犯到作者，非常抱歉

**Comment by xiatian12345** [comment]
同样的问题呢

**Comment by xiatian12345** [comment]
解决了，可以不用插件，直接访问https://chat.openai.com/api/auth/session 获取token
