### ISSUE TITLE
无法回复消息，显示“Our systems have detected unusual activity from your system. Please try again later.”

### ISSUE THREAD

**Issue by DragonJianxin** [zhile-io/pandora#224]
_不好意思，之前一直没找到star在哪里可以点击，现在已经找到_

无法回复消息，显示“Our systems have detected unusual activity from your system. Please try again later.”
该问题已持续存在超过24小时
使用的浏览器包括google、edge
重启后问题也依然存在

补充1：但在直接通过openAI登录GPT官网时可得到回复

补充2：新旧登录网址均显示同样问题

![image](https://github.com/zhile-io/pandora/assets/129564093/5a3c6b83-9408-4dbb-a534-7f992769ab31)

**Comment by xiangxingze** [comment]
Our systems have detected unusual activity from your system. Please try again later.
同样的问题，估计是被限制了

**Comment by Treeofabyss** [comment]
我现在也是，请问有什么解决方案吗？

**Comment by nader8** [comment]
俺也一样

**Comment by hhhhpaaa** [comment]
+1

**Comment by Lixia-Yi** [comment]
+1111

**Comment by Scolism** [comment]
+1111111

**Comment by tree-eighteen** [comment]
![image](https://github.com/zhile-io/pandora/assets/41732381/167dd750-f873-4b9d-abc5-b39f1ade7620)

目前出现这个问题了，官方的网站可以用，但用pandora部署的这个会报错。

**Comment by tohsakarinww** [comment]
俺也一样

**Comment by mlabalabala** [comment]
可能是账号原因，我的一个账号异常情况和楼主一样，另一个可以正常使用

**Comment by mlabalabala** [comment]
可能是账号原因，我的一个账号异常情况和楼主一样，另一个可以正常使用

**Comment by fskz** [comment]
+1

**Comment by gsons** [comment]
# 换chatgpt账号！！ 满血复活！！

**Comment by ZhouXiaolin** [comment]
+1

**Comment by wj2008** [comment]
俺也一样.....

**Comment by Chimeng1314** [comment]
有什么好的解决办法吗，除了换账号，已经重新安装过一次 pandora 镜像了，error 还一直存在

**Comment by SmallDingHappy** [comment]
+1，重新拉了镜像还是不行

**Comment by hexh250786313** [comment]
同

**Comment by XueDugu** [comment]
同

**Comment by zhile-io** [comment]
#235 在这里跟踪

**Comment by zz99zz9** [comment]
俺也一样，有解决方法吗？还是过一段时间就会好？

**Comment by lifafang** [comment]
> 我可以用了， ![image](https://user-images.githubusercontent.com/87591236/277596822-0ceb0b38-6754-4cf1-854e-56c1b2e0c9ae.png)
请问如何解决的？

**Comment by white527** [comment]
请问有什么解决办法吗？

**Comment by zhile-io** [comment]
我刚发布了修复，更新版本即可。

**Comment by XueDugu** [comment]
> 我刚发布了修复，更新版本即可。

感谢，重新部署已经可以正常使用了。
