### ISSUE TITLE
不能访问GPT-4

### ISSUE THREAD

**Issue by for3ever3** [zhile-io/pandora#230]
我在用access token 生成的api访问gpt-4-32k-0613的时候，爆出下面错误

```
{
  "error": {
    "message": "Request is not allowed. Please try again later.",
    "type": "requests",
    "param": "fk-tsu************************************",
    "code": null
  }
}
```
不能访问GPT-4，但是能访问3.5，我不是很清楚为什么会被拒绝访问GPT-4

**Comment by for3ever3** [comment]
我的 账户是有GPT-4权限的，之前还能访问的，但是现在不能了，我重新生成过api也是不能

**Comment by dEon1911** [comment]
蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？

**Comment by for3ever3** [comment]
> 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？
你这个的完整访问链接是什么，我一直用的ai.fakeopen.com/v1/chat/completions

**Comment by for3ever3** [comment]
> 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？

不用蹲了，解决了，是用的日抛代理，详见此处[https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF](url)
你只需要把代理改成今日日期，比如[https://ai-20231022.fakeopen.com](url)，访问格式是一样的，就可以用了。之前那个ai.fakeopen.com/我也不知道为什么不能用了，反正用日抛就行了

**Comment by for3ever3** [comment]
GPT_ACADEMIC、chat next web 均可以

**Comment by dEon1911** [comment]
测试可行！帅！！
另外分享一个信息，我之前一直用https://ai.fakeopen.com/token的Share Token结果现在一直403
但去https://chat1.zhile.io/用Share Token对应的Access Token登录一下，Share Token也能用了

> > 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？
> 
> 不用蹲了，解决了，是用的日抛代理，详见此处[https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF](url) 你只需要把代理改成今日日期，比如[https://ai-20231022.fakeopen.com](url)，访问格式是一样的，就可以用了。之前那个ai.fakeopen.com/我也不知道为什么不能用了，反正用日抛就行了

**Comment by for3ever3** [comment]
> Token对应的Access Token登录一下，Share Token也能用了
这个其实没多大关系，你抓包的时候你也会发现他其实用的也是日抛版代理，和Pandora-cloud模式一样的，本地搭建照样可以用
本地搭建详见项目文件夹/doc/wiki.md

**Comment by houzl3416** [comment]
> > 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？
> 
> 不用蹲了，解决了，是用的日抛代理，详见此处[https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF](url) 你只需要把代理改成今日日期，比如[https://ai-20231022.fakeopen.com](url)，访问格式是一样的，就可以用了。之前那个ai.fakeopen.com/我也不知道为什么不能用了，反正用日抛就行了

还是不可以访问4，大佬有最新的地址吗

**Comment by for3ever3** [comment]
> > > 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？
> > 
> > 不用蹲了，解决了，是用的日抛代理，详见此处[https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF](url) 你只需要把代理改成今日日期，比如[https://ai-20231022.fakeopen.com](url)，访问格式是一样的，就可以用了。之前那个ai.fakeopen.com/我也不知道为什么不能用了，反正用日抛就行了
> 
> 还是不可以访问4，大佬有最新的地址吗

你用哪个地址，发出来

**Comment by astorm-z** [comment]
> > > > 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？
> > > 
> > > 
> > > 不用蹲了，解决了，是用的日抛代理，详见此处[https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF](url) 你只需要把代理改成今日日期，比如[https://ai-20231022.fakeopen.com](url)，访问格式是一样的，就可以用了。之前那个ai.fakeopen.com/我也不知道为什么不能用了，反正用日抛就行了
> > 
> > 
> > 还是不可以访问4，大佬有最新的地址吗
> 
> 你用哪个地址，发出来

pk-this-is-a-real-free-pool-token-for-everyone
https://ai.fakeopen.com
用作者大佬的poolkey，好像用不了GPT4了，改成日抛域名也不行https://ai-20231025.fakeopen.com

**Comment by for3ever3** [comment]
> > > > > 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？
> > > > 
> > > > 
> > > > 不用蹲了，解决了，是用的日抛代理，详见此处[https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF](url) 你只需要把代理改成今日日期，比如[https://ai-20231022.fakeopen.com](url)，访问格式是一样的，就可以用了。之前那个ai.fakeopen.com/我也不知道为什么不能用了，反正用日抛就行了
> > > 
> > > 
> > > 还是不可以访问4，大佬有最新的地址吗
> > 
> > 
> > 你用哪个地址，发出来
> 
> pk-this-is-a-real-free-pool-token-for-everyone https://ai.fakeopen.com 用作者大佬的poolkey，好像用不了GPT4了，改成日抛域名也不行https://ai-20231025.fakeopen.com

他这个是共享池子，但是这个池子好久之前就挂了，我不是很清楚，你去开个新的issue问作者，如果你是用自己的access token生成的API访问，是没有问题的。

**Comment by for3ever3** [comment]
> > > > > > 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？
> > > > > 
> > > > > 
> > > > > 不用蹲了，解决了，是用的日抛代理，详见此处[https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF](url) 你只需要把代理改成今日日期，比如[https://ai-20231022.fakeopen.com](url)，访问格式是一样的，就可以用了。之前那个ai.fakeopen.com/我也不知道为什么不能用了，反正用日抛就行了
> > > > 
> > > > 
> > > > 还是不可以访问4，大佬有最新的地址吗
> > > 
> > > 
> > > 你用哪个地址，发出来
> > 
> > 
> > pk-this-is-a-real-free-pool-token-for-everyone https://ai.fakeopen.com 用作者大佬的poolkey，好像用不了GPT4了，改成日抛域名也不行https://ai-20231025.fakeopen.com
> 
> 他这个是共享池子，但是这个池子好久之前就挂了，我不是很清楚，你去开个新的issue问作者，如果你是用自己的access token生成的API访问，是没有问题的。

不是接口的问题，是你的api的问题，如果想用免费的，去issue看 #206

**Comment by astorm-z** [comment]
> > > > > > 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？
> > > > > 
> > > > > 
> > > > > 不用蹲了，解决了，是用的日抛代理，详见此处[https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF](url) 你只需要把代理改成今日日期，比如[https://ai-20231022.fakeopen.com](url)，访问格式是一样的，就可以用了。之前那个ai.fakeopen.com/我也不知道为什么不能用了，反正用日抛就行了
> > > > 
> > > > 
> > > > 还是不可以访问4，大佬有最新的地址吗
> > > 
> > > 
> > > 你用哪个地址，发出来
> > 
> > 
> > pk-this-is-a-real-free-pool-token-for-everyone https://ai.fakeopen.com 用作者大佬的poolkey，好像用不了GPT4了，改成日抛域名也不行https://ai-20231025.fakeopen.com
> 
> 他这个是共享池子，但是这个池子好久之前就挂了，我不是很清楚，你去开个新的issue问作者，如果你是用自己的access token生成的API访问，是没有问题的。

好嘞，感谢。因为是前几天openai宕机后才开始这样的，之前3.5、4都能用，宕机恢复后就只能用3.5了

**Comment by zhile-io** [comment]
> > > > > > > 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？
> > > > > > 
> > > > > > 
> > > > > > 不用蹲了，解决了，是用的日抛代理，详见此处[https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF](url) 你只需要把代理改成今日日期，比如[https://ai-20231022.fakeopen.com](url)，访问格式是一样的，就可以用了。之前那个ai.fakeopen.com/我也不知道为什么不能用了，反正用日抛就行了
> > > > > 
> > > > > 
> > > > > 还是不可以访问4，大佬有最新的地址吗
> > > > 
> > > > 
> > > > 你用哪个地址，发出来
> > > 
> > > 
> > > pk-this-is-a-real-free-pool-token-for-everyone https://ai.fakeopen.com 用作者大佬的poolkey，好像用不了GPT4了，改成日抛域名也不行https://ai-20231025.fakeopen.com
> > 
> > 
> > 他这个是共享池子，但是这个池子好久之前就挂了，我不是很清楚，你去开个新的issue问作者，如果你是用自己的access token生成的API访问，是没有问题的。
> 
> 好嘞，感谢。因为是前几天openai宕机后才开始这样的，之前3.5、4都能用，宕机恢复后就只能用3.5了

他们说的不太对，你哪个号要用4.0请求，先在cloud站登一下再用。你试试。

**Comment by hevinyu** [comment]
> > > > > > > > 蹲一下同问status.fakeopen.com里连Conversation4都直接干没了，是改写法了还是直接取消了？
> > > > > > > 
> > > > > > > 
> > > > > > > 不用蹲了，解决了，是用的日抛代理，详见此处[https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF](url) 你只需要把代理改成今日日期，比如[https://ai-20231022.fakeopen.com](url)，访问格式是一样的，就可以用了。之前那个ai.fakeopen.com/我也不知道为什么不能用了，反正用日抛就行了
> > > > > > 
> > > > > > 
> > > > > > 还是不可以访问4，大佬有最新的地址吗
> > > > > 
> > > > > 
> > > > > 你用哪个地址，发出来
> > > > 
> > > > 
> > > > pk-this-is-a-real-free-pool-token-for-everyone https://ai.fakeopen.com 用作者大佬的poolkey，好像用不了GPT4了，改成日抛域名也不行https://ai-20231025.fakeopen.com
> > > 
> > > 
> > > 他这个是共享池子，但是这个池子好久之前就挂了，我不是很清楚，你去开个新的issue问作者，如果你是用自己的access token生成的API访问，是没有问题的。
> > 
> > 
> > 好嘞，感谢。因为是前几天openai宕机后才开始这样的，之前3.5、4都能用，宕机恢复后就只能用3.5了
> 
> 他们说的不太对，你哪个号要用4.0请求，先在cloud站登一下再用。你试试。

登录一下再请求4.0确实可以了，这是什么原因？
