### ISSUE TITLE
What can I do to fix this?"Our systems have detected unusual activity from your system. Please try again later."

### ISSUE THREAD

**Issue by MackDing** [zhile-io/pandora#235]
![image](https://github.com/zhile-io/pandora/assets/19878893/5be57fb7-832f-4fd5-8f6e-91615a45a904)

What can I do to fix this? pls

**Comment by DGUTyu** [comment]
+1

**Comment by DGUTyu** [comment]
我部署的服务器是洛杉矶的，使用Access Token登录后也报Our systems have detected unusual activity from your system. Please try again later.

**Comment by zbsguilai** [comment]
最近出现的这个问题，这个能修复吗

**Comment by DGUTyu** [comment]
您好，我已收到你的邮件，我会尽快查收。

**Comment by liucangsong** [comment]
我也出现了这个问题

**Comment by lhfdou** [comment]
我也出现了这个问题，需要怎么解决呢？

**Comment by zhile-io** [comment]
官方在3.5的提问上灰度一些账号进行arkose验证码校验，需要更新。

**Comment by Einzieg** [comment]
+1

**Comment by jinde98** [comment]
我以为只是自己的问题，原来这样的很多。

**Comment by duzhuoshanwai** [comment]
更换账号后正常使用

**Comment by jinde98** [comment]
> 更换账号后正常使用

我换了2账号，都是这种情况

**Comment by CHANGEORT** [comment]
> > 更换账号后正常使用
> 
> 我换了2账号，都是这种情况

作者大大回复的是：官方在3.5的提问上灰度一些账号进行arkose验证码校验，需要更新。可能你两个账号都在灰度测试里面

**Comment by 1592363624** [comment]
> 官方在3.5的提问上灰度一些账号进行arkose验证码校验，需要更新。

这玩意儿无解吗

**Comment by jinde98** [comment]
> > > 更换账号后正常使用
> > 
> > 
> > 我换了2账号，都是这种情况
> 
> 作者大大回复的是：官方在3.5的提问上灰度一些账号进行arkose验证码校验，需要更新。可能你两个账号都在灰度测试里面

嗯，目前的我账户能登录官网web，但是没办使用使用pandora项目的web等

**Comment by lou612500** [comment]
我的在官网正常使用，在pandora上不行

**Comment by SeanFalcon** [comment]
昨天正常使用，今天出现这个问题，官网上是可以使用的，重新获取token也不行

**Comment by s181462537** [comment]
的确是部分账号被限制，我4个号有两个正常，两个不行

**Comment by litianfu1997** [comment]
+1

**Comment by xionggd** [comment]
+1

**Comment by zhile-io** [comment]
cloud已修复

**Comment by MackDing** [comment]
> cloud已修复
请问需要更新镜像吗

**Comment by nowitzki121** [comment]
> cloud已修复

请问大大有计划修复server模式吗？
