### ISSUE TITLE
能否让GPT实现联网功能

### ISSUE THREAD

**Issue by xboy734** [zhile-io/pandora#238]
WebChatGPT能让3.5实现联网的功能，能否支持这个插件，或者有什么其他办法实现联网的功能吗

**Comment by Roulders** [comment]
我有个想法，提问的时候，同时爬取搜索引擎的检索数据，把这个数据喂给GPT，然后再让他回答，怎么样？

**Comment by xboy734** [comment]
这个功能能配置成在服务端或者客户端就最好了，
服务端自己搭建的就能用上Google搜索，
客户端的话就可以不占用服务器资源了

**Comment by zhile-io** [comment]
目前不行，因为没办法使用function call

**Comment by Roulders** [comment]
> 目前不行，因为没办法使用function call

是活着的大佬！
