### ISSUE TITLE
代理怎么搭建？

### ISSUE THREAD

**Issue by long202258** [zhile-io/pandora#242]
作者提供得代理是https://ai.fakeopen.com，求搭建代理得教程，不是把域名转发到https://ai.fakeopen.com

**Comment by long202258** [comment]
> 目前并未开源。

收到，想着自己搞个代理 给大神省点服务器

**Comment by LaiBaoYuan** [comment]
别问了，大佬开源的话，就会被openai的人封杀的，所以才选择不开源
