### ISSUE TITLE
可试试换个账号，据说是官网对部分3.5账号灰度测试，需要等项目更新

### ISSUE THREAD

**Issue by long202258** [zhile-io/pandora#247]
可试试换个账号，据说是官网对部分3.5账号灰度测试，需要等项目更新

_Originally posted by @s181462537 in https://github.com/zhile-io/pandora/issues/246#issuecomment-1776332967_
        
换账号试过了还是不行

**Comment by s181462537** [comment]
我4个账号，有两个行，两个不行，也许你换的账号也在测试之列

**Comment by zhile-io** [comment]
cloud已修复
