### ISSUE TITLE
刚刚更新了下pandora，这需要啥配置文件

### ISSUE THREAD

**Issue by onewinner** [zhile-io/pandora#249]
![image](https://github.com/zhile-io/pandora/assets/94044430/d604ac58-5f59-49c7-ac46-9ac850030053)

**Comment by onewinner** [comment]
还有pandora-cloud更新后报错
![image](https://github.com/zhile-io/pandora/assets/94044430/e71a8ef4-e853-424d-b1af-7f584d6ff6fb)

![image](https://github.com/zhile-io/pandora/assets/94044430/adf7fdeb-db35-4237-a3e7-7e8766bfdead)

**Comment by zhile-io** [comment]
pandora那个包不是的，可以删掉。

**Comment by onewinner** [comment]
> pandora那个包不是的，可以删掉。

![image](https://github.com/zhile-io/pandora/assets/94044430/843202e6-0172-4b62-9fe5-7ce070b3958d)
nazh那这个问题呢

**Comment by onewinner** [comment]
> pandora那个包不是的，可以删掉。

删了，还是存在报错

**Comment by onewinner** [comment]
我知道了，给pandora-chatgpt更新就好了
