### ISSUE TITLE
获取不了access token了

### ISSUE THREAD

**Issue by Chadnon** [zhile-io/pandora#252]
Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.
<img width="927" alt="微信图片_20231024112730" src="https://github.com/zhile-io/pandora/assets/43345641/447fc675-3577-4c43-a2d1-e5918dfbcffb">

**Comment by Aiolos-Wang** [comment]
我也是同样的问题

**Comment by fremindmm** [comment]
<img width="637" alt="image" src="https://github.com/zhile-io/pandora/assets/7918323/a8e8e3e7-5854-4543-9f8b-430d6a3dca3f">
同样的问题

**Comment by chxgzs** [comment]
弄了一上午我还以为是我的问题呢.

**Comment by cxsunny** [comment]
我也是

**Comment by WillxUN1ON** [comment]
same，求修复了踢我一下

**Comment by jiupinjiandingshi** [comment]
同样的问题

**Comment by LikyThu** [comment]
same+1

**Comment by hututusb** [comment]
多谢多谢！

**Comment by advwei** [comment]
也是遇到了同样的问题，还专门升级了docker里面的版本
https://github.com/zhile-io/pandora/issues/252

**Comment by zhile-io** [comment]
这个问题短期内无法被修复，请去官方获取access token，或者使用 https://ai.fakeopen.com/auth1 获取。
