### ISSUE TITLE
> > 我们的系统检测到您的系统存在异常活动。请稍后再试 这个是为什么呀 昨天还能用今天就不能用了

### ISSUE THREAD

**Issue by 1nihao8** [zhile-io/pandora#258]
> > 我们的系统检测到您的系统存在异常活动。请稍后再试 这个是为什么呀 昨天还能用今天就不能用了
> 
> 我的也是，而且历史里面有不是我问过的问题，肯定被别人操作过，但是我的token别人怎么会知道，所以有点质疑这个项目作者，有没有收集token拿去做pool做国内付费chatgpt赚钱啊，希望作者解释一下，或者是有什么漏洞被别人利用了

我解释过了，如果你用server模式，是打开就能访问的。你的网址一旦被人知道，人人都能访问。还有最近有很多扫号的，如果你的账号密码跟一些其他网站相同，可能已经泄露被扫。我没有做任何赚钱项目，广告都没有。我没收任何人钱，也没拉着任何人过来用，如果你不放心可以不要使用，别再拉着我出来解释了。

_Originally posted by @zhile-io in https://github.com/zhile-io/pandora/issues/14#issuecomment-1776779389_

**Comment by zhile-io** [comment]
#235
