### ISSUE TITLE
能发信息，但是没有答应，昨晚还能用，openai上账号能用

### ISSUE THREAD

**Issue by Vincent465072111** [zhile-io/pandora#259]
![image](https://github.com/zhile-io/pandora/assets/59242412/621dbe5c-7b73-4578-a0a3-0f9d06b0f074)
![image](https://github.com/zhile-io/pandora/assets/59242412/1339ea93-62fd-4ebb-a7ad-6aaba7f698e6)

**Comment by Asuralf** [comment]
![image](https://github.com/zhile-io/pandora/assets/55649839/47b890c6-b0c8-4a74-a76b-bae6787a0f5a)
我也遇到了。蹲一下。

**Comment by Peter-Rey** [comment]
我也遇到了，想请教一下是什么问题？中转服务器挂了吗？
![image](https://github.com/zhile-io/pandora/assets/55908856/2f46772a-1351-4517-a742-d64c83307cf1)

**Comment by Peter-Rey** [comment]
我也遇到了，想请教一下是什么问题？中转服务器挂了吗？
![image](https://github.com/zhile-io/pandora/assets/55908856/fe125331-5b95-473e-bb70-4ade0aab982e)

**Comment by zhuhaoxlj** [comment]
遇到了相同的问题，等待作者更新吧

**Comment by zhile-io** [comment]
建议使用cloud模式，已经修复这个问题。

**Comment by Vincent465072111** [comment]
> 建议使用cloud模式，已经修复这个问题。

好的感谢大佬

**Comment by Peter-Rey** [comment]
> 建议使用cloud模式，已经修复这个问题。
十分感谢你的分享和帮助。

**Comment by zhuhaoxlj** [comment]
> 建议使用cloud模式，已经修复这个问题。

测试过 token 可以正常使用了，作者辛苦了🌹🌹🌹

**Comment by fremindmm** [comment]
Our systems have detected unusual activity from your system. Please try again later.  使用cloud模式报这个错误 可能是什么原因呢

**Comment by fremindmm** [comment]
使用panora-cloud 这个Version: 1.3.5 可以解决问题  测试过了完美 感谢大佬

**Comment by Vincent465072111** [comment]
另外的我补充一下，我换了账号也解决了
