### ISSUE TITLE
在 Docker 环境变量指定了 Access Token

### ISSUE THREAD

**Issue by missuo** [zhile-io/pandora#26]
已经在 Docker 环境变量设置了 Access Token，但是访问 Web 仍提示输入帐号或密码，或者输入 Access Token。

请问怎么实现，默认使用已经指定的 Access Token 而不需要登录呢？

**Comment by CureDreams** [comment]
docker run -e PANDORA_ACCESS_TOKEN=你的access_token -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora 试试这个

**Comment by missuo** [comment]
> docker run -e PANDORA_ACCESS_TOKEN=你的access_token -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora 试试这个

我用的是 Docker Compose，卸载环境变量里面，应该是一样的效果。

**Comment by RexLee0929** [comment]
> 已经在 Docker 环境变量设置了 Access Token，但是访问 Web 仍提示输入帐号或密码，或者输入 Access Token。
> 
> 请问怎么实现，默认使用已经指定的 Access Token 而不需要登录呢？

直接指定token的话不是会很麻烦吗,所有人都能使用了?只要知道你的网站,然后还要定期更新token

**Comment by Windy147** [comment]
确实很不安全


> 直接指定token的话不是会很麻烦吗,所有人都能使用了?只要知道你的网站,然后还要定期更新token

**Comment by vectorstone** [comment]
docker的命令里面指定token文件的路径，同时需要映射容器和宿主机的路径不然加载不到token文件
示例如下： 
将宿主机的 /home/gavin/token 目录映射到容器的/root目录，然后将token文件放到/home/gavin/token文件夹里面即可
`docker run --name pandora -e PANDORA_TOKENS_FILE=/root/access_token.json -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 --name pandora -v /home/gavin/token/:/root/ --restart=always -d pengzhile/pandora`

token文件示例： 
文件名就是 access_token.json
`{
"key": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13Um0"
}`

**Comment by vectorstone** [comment]
> 已经在 Docker 环境变量设置了 Access Token，但是访问 Web 仍提示输入帐号或密码，或者输入 Access Token。
> 
> 请问怎么实现，默认使用已经指定的 Access Token 而不需要登录呢？

把docker里面的这个环境变量 `-e PANDORA_CLOUD=1` 删除掉，指定好Access Token就可以实现免登录的效果了，如果内网的话没什么问题， 如果公网的话，最好开启Nginx auth鉴权
