### ISSUE TITLE
使用access token在python中调用官网的接口？

### ISSUE THREAD

**Issue by jinde98** [zhile-io/pandora#261]
在已经获得access token，有大佬能给出https://chat.openai.com/backend-api/conversation官网这个接口具体调用代码吗？
下面是大佬给的说明
![1698145895120](https://github.com/zhile-io/pandora/assets/127750182/ce806b53-7004-4cb6-8732-a26188c8707c)

**Comment by By-laosuye** [comment]
![image](https://github.com/zhile-io/pandora/assets/62440221/0457da24-c557-4bea-95b7-c986713c6a5a)
java好像报错了，有没有大佬知道啥问题的啊

**Comment by jinde98** [comment]
> ![image](https://user-images.githubusercontent.com/62440221/277707441-0457da24-c557-4bea-95b7-c986713c6a5a.png) java好像报错了，有没有大佬知道啥问题的啊

很多账户都出现这个问题， 目前这些账户只能在官网上使用了。
我换了一个账号就可以了
