### ISSUE TITLE
找到可以使用的API的规律了

### ISSUE THREAD

**Issue by long202258** [zhile-io/pandora#262]
fk-yhAvQipTv7qs5Hu**********D50mQInQ0CjeYYM   这种生产的API没有“-”这个横杠的就不可以用，fk-E167b1k1nX************PWzZ9aB_qL4gG0NMM  这个有小横杠的就可以用

**Comment by zhile-io** [comment]
我表示不懂。。

**Comment by Attiv** [comment]
我现在带_的也不能用了，重新登录也是提示：Request is not allowed
