### ISSUE TITLE
获取 token 登录失败

### ISSUE THREAD

**Issue by chenlai** [zhile-io/pandora#263]
网站 extension://niffhmkbadlcidfcbbpebfpmadbpdejh/auth.html  提示 ：

Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app.

**Comment by notylou** [comment]
+1

**Comment by boboarts** [comment]
+1

**Comment by xixino** [comment]
+2

**Comment by xixino** [comment]
也可以官方登录，然后访问 [这里](http://chat.openai.com/api/auth/session) 拿 Access Token

**Comment by robbiexgithub** [comment]
+1
官方登录，拿 Access Token，出现以下错误:
Unable to load site

Please try again later. If you are using a VPN, try turning it off. Check the [status page](https://status.openai.com/) for information on outages.

[IP:91.243.81.135 | Ray ID:81b6be0efc5e91a5]

**Comment by junlongzzz** [comment]
> +1 官方登录，拿 Access Token，出现以下错误: Unable to load site
> 
> Please try again later. If you are using a VPN, try turning it off. Check the [status page](https://status.openai.com/) for information on outages.
> 
> [IP:91.243.81.135 | Ray ID:81b6be0efc5e91a5]

你这是你的梯子不行，访问不到官方页面
