### ISSUE TITLE
Our systems have detected unusual activity from your system. Please try again later.

### ISSUE THREAD

**Issue by China-ZengYuZai** [zhile-io/pandora#265]
使用的使用突然弹出这个,
![image](https://github.com/zhile-io/pandora/assets/51729090/3b920fe5-a83b-4ab2-acc9-10816a88c038)

之前是正常的,这个怎么解决

**Comment by fremindmm** [comment]
Our systems have detected unusual activity from your system. Please try again later. 
使用 pandora-cloud 报如上错误

**Comment by fremindmm** [comment]
使用panora-cloud 这个Version: 1.3.5 可以解决问题
