### ISSUE TITLE
使用Access Token返回内容为空

### ISSUE THREAD

**Issue by runcode1** [zhile-io/pandora#266]
使用Access token 在 
https://chat1.zhile.io/登录是正常的
但是通过接口调用时 
![image](https://github.com/zhile-io/pandora/assets/127473442/c9d9ff69-f455-4d3b-ba4b-c59374f66620)
可以生成新会话但是返回内容为空，大概昨天下午开始

**Comment by zhile-io** [comment]
现在在 chat1.zhile.io 也还是这样吗？

**Comment by zhile-io** [comment]
自己部署的要更新一下版本，我昨晚发了版本

**Comment by mcgwa9** [comment]
请问docker镜像那边有更新吗

**Comment by qingshengwen** [comment]
> 请问docker镜像那边有更新吗

hub仓库显示也是14H之前，但是我这边用的是最新版本了也还是不行，跟楼主一样的情况
但是试了大佬那边chat1.zhile.io也是正常的，不知道问题出在哪里，好像是跟openai官网那个验证有关系？

**Comment by mcgwa9** [comment]
> > 请问docker镜像那边有更新吗
> 
> hub仓库显示也是14H之前，但是我这边用的是最新版本了也还是不行，跟楼主一样的情况 但是试了大佬那边chat1.zhile.io也是正常的，不知道问题出在哪里，好像是跟openai官网那个验证有关系？

docker run -d --name pandora --restart=always -e PANDORA_CLOUD=cloud -e PANDORA_THREADS=4 -e PANDORA_SERVER=0.0.0.0:8090 -p 8090:8090 -e PANDORA_ACCESS_TOKEN="填自己的" pengzhile/pandora
我这边切换成cloud模式就解决了
