### ISSUE TITLE
服务部署过后域名认证

### ISSUE THREAD

**Issue by javasopp** [zhile-io/pandora#27]
老哥你好，我想请问下，就是能不能有地方保存域名认证信息啊，还有个问题就是，浏览器打开过后的那个页面标签，有没有哪里可以修改啊，我想域名备案，可能需要修改这些地方。

**Comment by zhile-io** [comment]
如果是cloud模式在 pandora-cloud 仓库找一个叫login.html的文件添加备案信息。
