### ISSUE TITLE
自己部署的pandora没有泄露，为什么会有别人使用的痕迹？

### ISSUE THREAD

**Issue by rzchenn** [zhile-io/pandora#272]
自己部署的pandora没有泄露，为什么会有别人使用的痕迹？就是左边的对话记录里偶尔会有别人的交流过程。

1、是不是我的access token泄露了？ 我是从官方获取的。不是从第三方登录。
2、是不是我的ip或者域名被别人知道了？那我不用域名了。只要ip加新端口试试。看还有类似问题没。

懂得大佬解答下可能是哪种方式？

**Comment by mcgwa9** [comment]
可能是第二种

**Comment by zhile-io** [comment]
> 自己部署的pandora没有泄露，为什么会有别人使用的痕迹？就是左边的对话记录里偶尔会有别人的交流过程。
> 
> 1、是不是我的access token泄露了？ 我是从官方获取的。不是从第三方登录。 2、是不是我的ip或者域名被别人知道了？那我不用域名了。只要ip加新端口试试。看还有类似问题没。
> 
> 懂得大佬解答下可能是哪种方式？

从你的上一个issue来看，你应该是server方式部署，打开就用，不要直接暴露在公网上。

**Comment by mcok** [comment]
公网上还是用nginx加个basic auth吧 公网一直都有坏家伙扫IP和端口的

**Comment by daerbiubiu** [comment]
> 公网上还是用nginx加个basic auth吧 公网一直都有坏家伙扫IP和端口的

请问通过docker部署的项目如何通过nginx转发设置basic auth？
