### ISSUE TITLE
现在怎么不显示回复了，我看openai官网好像是更新了回复效果

### ISSUE THREAD

**Issue by snowarea1994** [zhile-io/pandora#275]
Pandora：
![image](https://github.com/zhile-io/pandora/assets/18032043/14165dc5-d851-47b4-b468-0fc9d95ec460)
官网：
![image](https://github.com/zhile-io/pandora/assets/18032043/80f10fa2-99d5-472a-9530-c8876c8b1df3)

**Comment by snowarea1994** [comment]
Pandora：
{"prompt":"3+3=","message_id":"261c2172-e6f9-4dfa-b05f-10780fc6d751","conversation_id":"fab21c07-7e67-4ca4-b5a7-1aa26e9ecf4b","parent_message_id":"676fa8cc-7701-4ee4-aa03-f286f4604877","model":"text-davinci-002-render-sha","timezone_offset_min":-480}
官网：
{"action":"variant","messages":[{"id":"261c2172-e6f9-4dfa-b05f-10780fc6d751","author":{"role":"user","metadata":{}},"create_time":1698221256.344785,"content":{"content_type":"text","parts":["3+3="]},"status":"finished_successfully","weight":1,"metadata":{"timestamp_":"absolute"},"recipient":"all"}],"conversation_id":"fab21c07-7e67-4ca4-b5a7-1aa26e9ecf4b","parent_message_id":"676fa8cc-7701-4ee4-aa03-f286f4604877","model":"text-davinci-002-render-sha","timezone_offset_min":-480,"variant_purpose":"none","history_and_training_disabled":false,"arkose_token":"98817914b732d0526.6535390802|r=us-west-2|meta=3|metabgclr=transparent|metaiconclr=%23757575|guitextcolor=%23000000|pk=3D86FBBA-9D22-402A-B512-3420086BA6CC|at=40|sup=1|rid=94|ag=101|cdn_url=https%3A%2F%2Ftcr9i.chat.openai.com%2Fcdn%2Ffc|lurl=https%3A%2F%2Faudio-us-west-2.arkoselabs.com|surl=https%3A%2F%2Ftcr9i.chat.openai.com|smurl=https%3A%2F%2Ftcr9i.chat.openai.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager","force_paragen":false}

**Comment by qRainBirdp** [comment]
同样的问题，日志报错405
2023-10-25 02:33:26.830 | ERROR    | pandora.bots.server:__handle_error:99 - 405 Method Not Allowed: The method is not allowed for the requested URL.

**Comment by imok7** [comment]
估计是被ban了？

**Comment by zhushen12580** [comment]
如果能调用Pandora-cloud版本的api就好了

**Comment by snowarea1994** [comment]
> 如果能调用Pandora-cloud版本的api就好了

cloud版本还能用吗？

**Comment by tetabc** [comment]
> Pandora： ![image](https://user-images.githubusercontent.com/18032043/277919638-14165dc5-d851-47b4-b468-0fc9d95ec460.png) 官网： ![image](https://user-images.githubusercontent.com/18032043/277919753-80f10fa2-99d5-472a-9530-c8876c8b1df3.png)

我用的Pandora正常，官网不回复

**Comment by ahlkddhfklh** [comment]
An error occurred. Either the engine you requested does not exist or there was another issue processing your request. If this issue persists please contact us through our help center at help.openai.com.

**Comment by zhushen12580** [comment]
> > 如果能调用Pandora-cloud版本的api就好了
> 
> cloud版本还能用吗？

能
