### ISSUE TITLE
救命，今天遇到一个特别离谱的事情，感觉是技术灵异事件，关于accessToken的

### ISSUE THREAD

**Issue by IronEaterBeast** [zhile-io/pandora#278]
简单说：

昨天以前-》用chat.openai.com/api/auth/session拿到的accessToken大概如下
![2023-10-25 175513](https://github.com/zhile-io/pandora/assets/9688223/29ebfe91-084b-41d9-a0d6-cbf0dc84134c)
毫无疑问这是chatgpt的token，使用这个token是无法访问gpt-4的，因为我的chatgpt没有购买，这个很合理。

今天-》       突然发现用这个token能访问gpt-4了，欣喜若狂，感觉白嫖之神光顾我了，玩了一天gpt-4，下午显示错误“You exceeded your current quota”，感觉很奇怪，跑到账户后台一看，我他喵！
![2023-10-25 180236](https://github.com/zhile-io/pandora/assets/9688223/558f3b16-47a1-44ab-87c7-98f9f0697780)
我确定我的api的key没有这个key，而且api的key最近都没有访问，截图如下
![2023-10-25 180525](https://github.com/zhile-io/pandora/assets/9688223/9b63a69c-4613-445c-bd1d-32c3442e4599)

问题：
这是抽了哪根疯，一个chatgpt的key，却能够访问api的模型，在没有通知的情况下进行收费。我真的要气死了。
谁有类似情况没有。
重写登录chatgpt，重新拿key，依然是这个情况，小学生我不敢充值了都。

**Comment by IronEaterBeast** [comment]
chatgpt官方网页依然正常使用，但只要把这个token拿出来用，就会收费，太灵异了吧！

**Comment by zhile-io** [comment]
并不灵异，这个我早在项目文档中说过了。

**Comment by zhile-io** [comment]
![image](https://github.com/zhile-io/pandora/assets/144572553/2134eb16-a9f4-44ba-9683-cdc567b6ab3b)

**Comment by IronEaterBeast** [comment]
> 并不灵异，这个我早在项目文档中说过了。

谢谢回复，拜读了一下文档，但是我没看到哪个地方有说怎么获得share token呢，谷歌了一下也没找到相关信息，我真的很需要share token或者pool token。
