### ISSUE TITLE
点击复制的按钮会报错“ Failed to copy to clipboard”，导致无法复制chatgpt回复的内容

### ISSUE THREAD

**Issue by 459633382** [zhile-io/pandora#28]
![1694769403419](https://github.com/zhile-io/pandora/assets/44571764/c39b787f-bf0e-4fa2-8494-9ea19ecc9709)

**Comment by 459633382** [comment]
使用环境为docker部署在服务器上的

**Comment by junlongzzz** [comment]
详见FAQ第一条 #14

**Comment by CureDreams** [comment]
怎么开启 HTTPS ？

**Comment by CureDreams** [comment]
怎么开启 HTTPS ？

**Comment by junlongzzz** [comment]
> 怎么开启 HTTPS ？

申请域名->解析到服务器->申请域名https证书->配置证书->完毕访问

PS：用 caddy服务器可以自动申请https证书，方便快捷，反代到pandora即可
