### ISSUE TITLE
启用cloud模式，在docker新创建pandora后。回复消息提示：Our systems have detected unusual activity from your system. Please try again later.

### ISSUE THREAD

**Issue by rzchenn** [zhile-io/pandora#281]
启用cloud模式，在docker新创建pandora后。
发送消息提示：Our systems have detected unusual activity from your system. Please try again later.

但是用同样的access token在chat1.zhile.io能正常使用。在官网也能正常使用。为啥？

**Comment by kuke21** [comment]
哈哈，我今晚也遇到了 一个ip 二个账户使用都会提示这 后来重新安装系统后搭建环境就好了

**Comment by huximi** [comment]
重新拉取新的版本，新版本已经 修复了。

**Comment by rzchenn** [comment]
> 重新拉取新的版本，新版本已经 修复了。

就是用的最新的啊

**Comment by rzchenn** [comment]
> 重新拉取新的版本，新版本已经 修复了。

解决了！拉取重建。就好了。

**Comment by LannyChung** [comment]
为啥我的还是不行，拉了新版本的，重新跑的，还是报这个错
