### ISSUE TITLE
为什么不能用Access Token模拟接口，然后不扣官方额度呢，Share Token最终也是转成Access Token和openai通信的吧？

### ISSUE THREAD

**Issue by IronEaterBeast** [zhile-io/pandora#282]
Share Token这个东西应该openai是不认识的，所以通信只能是Access Token，排除Share Token的那些共享功能之类的，为什么不直接填Access Token呢。没有理解这个设计的初衷。

**Comment by undefinedcodezhong** [comment]
我倒觉得这是一个不错的设计。
首先你说了share token的共享功能，方便对话隔离之类的，有一个很好的实践需求就是plus会员拼车。
其次针对同一用户、同一密码字符串生成的share token是一样的，这使得部署运行的程序可以无感更新，只需要在access token快过期的时候另外刷新就好，甚至在openai做各种加强验证之前，完全都可以脚本实现，整套流程很舒服。而如果使用access token的话，你就需要到各个应用了模拟接口的地方去手动修改。
另外一些微不足道的原因可能包括access token很长，在跨设备、跨应用复制粘贴使用的时候容易出错；access token实际上包含了用户名的相关信息，虽然不会直接暴露账号密码，但仍然增加了被逆向的风险等。
当然，缺点和风险也就集中在了作者的中心化账本上，包括之前出过的T0级事故。但总体来说，我觉得用share token的设计是利大于弊的。
如果追求access token模拟接口，可以看http api那块内容，另外我相信github也能找到一些类似的项目。

**Comment by IronEaterBeast** [comment]
> 我倒觉得这是一个不错的设计。 首先你说了share token的共享功能，方便对话隔离之类的，有一个很好的实践需求就是plus会员拼车。 其次针对同一用户、同一密码字符串生成的share token是一样的，这使得部署运行的程序可以无感更新，只需要在access token快过期的时候另外刷新就好，甚至在openai做各种加强验证之前，完全都可以脚本实现，整套流程很舒服。而如果使用access token的话，你就需要到各个应用了模拟接口的地方去手动修改。 另外一些微不足道的原因可能包括access token很长，在跨设备、跨应用复制粘贴使用的时候容易出错；access token实际上包含了用户名的相关信息，虽然不会直接暴露账号密码，但仍然增加了被逆向的风险等。 当然，缺点和风险也就集中在了作者的中心化账本上，包括之前出过的T0级事故。但总体来说，我觉得用share token的设计是利大于弊的。 如果追求access token模拟接口，可以看http api那块内容，另外我相信github也能找到一些类似的项目。

如果不用作者的站点：https://chat.zhile.io/，而是自己本地部署的话，能够在本地生成share token，并且免费使用api吗

**Comment by jinde98** [comment]
要在本地生成share token可以使用https://github.com/mufeng510/Free-ChatGPT-API这项目，但还是走ai.fakeopen.com。 share token是zhile-io的，只能在pandora项目上用。
利用pandora项目就可以免费使用api。

**Comment by undefinedcodezhong** [comment]
> > 我倒觉得这是一个不错的设计。 首先你说了share token的共享功能，方便对话隔离之类的，有一个很好的实践需求就是plus会员拼车。 其次针对同一用户、同一密码字符串生成的share token是一样的，这使得部署运行的程序可以无感更新，只需要在access token快过期的时候另外刷新就好，甚至在openai做各种加强验证之前，完全都可以脚本实现，整套流程很舒服。而如果使用access token的话，你就需要到各个应用了模拟接口的地方去手动修改。 另外一些微不足道的原因可能包括access token很长，在跨设备、跨应用复制粘贴使用的时候容易出错；access token实际上包含了用户名的相关信息，虽然不会直接暴露账号密码，但仍然增加了被逆向的风险等。 当然，缺点和风险也就集中在了作者的中心化账本上，包括之前出过的T0级事故。但总体来说，我觉得用share token的设计是利大于弊的。 如果追求access token模拟接口，可以看http api那块内容，另外我相信github也能找到一些类似的项目。
> 
> 如果不用作者的站点：[https://chat.zhile.io/，而是自己本地部署的话，能够在本地生成share](https://chat.zhile.io/%EF%BC%8C%E8%80%8C%E6%98%AF%E8%87%AA%E5%B7%B1%E6%9C%AC%E5%9C%B0%E9%83%A8%E7%BD%B2%E7%9A%84%E8%AF%9D%EF%BC%8C%E8%83%BD%E5%A4%9F%E5%9C%A8%E6%9C%AC%E5%9C%B0%E7%94%9F%E6%88%90share) token，并且免费使用api吗

其实刚才测试了一下，虽然有share token模拟api key的设计，但是并没有拒绝access token当做key的方式：
https://github.com/zhile-io/pandora/issues/294#issuecomment-1781495144
share token的设计本身就是为了api-free的，所以和部署无关，只是share token要去作者网站那里生成。

**Comment by zhile-io** [comment]
因为access token本来openai官方就接受请求api。我如果换掉，相当于阉割了官方提供的功能。
