### ISSUE TITLE
cloud修复了arkose问题，那server呢

### ISSUE THREAD

**Issue by nowitzki121** [zhile-io/pandora#285]
#235 
大大，求问有修复server版的计划吗？

**Comment by zhile-io** [comment]
server模式目前不会更新，准备在新版本合并二者。

**Comment by zhile-io** [comment]
目前server模式应该没有arkose困扰了。

**Comment by nowitzki121** [comment]
希望您能考虑保留现有server的功能不受影响，因为我们内网不能直接使用cloud模式，在cloud模式下需要客户端能访问https://ai.fakeopen.com。但是server模式没问题，因为在server模式下，所有流量都经过我自己搭建的服务器转发出去。
