### ISSUE TITLE
Auth Helper获取Token报错

### ISSUE THREAD

**Issue by 1250658183** [zhile-io/pandora#286]
各位大神，今早我尝试获取token发现了报错，提示ChatGPT App不是最新版，请问这个一个临时Bug吗？贴图如下：
<img width="1285" alt="image" src="https://github.com/zhile-io/pandora/assets/45011374/ce707d5e-31d6-474e-a97f-c7604f7040c0">

**Comment by Aniu456** [comment]
加一，咋回事呀

**Comment by zhile-io** [comment]
openai最近的更新把这个插件搞废了。如果是第三方账号，只能到官方登录获取。
