### ISSUE TITLE
An error occurred. Either the engine you requested does not exist or there was another issue processing your request. If this issue persists please contact us through our help center at help.openai.com.这个报错咋解决呀

### ISSUE THREAD

**Issue by LaiBaoYuan** [zhile-io/pandora#292]
<img width="653" alt="image" src="https://github.com/zhile-io/pandora/assets/89441249/1b6bd0bd-0d8a-40a5-8668-0c39a667f86f">
<img width="398" alt="image" src="https://github.com/zhile-io/pandora/assets/89441249/b478d466-8559-41a0-adcd-afdc2a292a74">

**Comment by LaiBaoYuan** [comment]
<img width="806" alt="image" src="https://github.com/zhile-io/pandora/assets/89441249/6b9901b3-eacd-4854-8537-305d6a46f735">
gpt-3.5也加入了arkose_token的验证，为啥https://chat1.zhile.ios上面可以通过，我部署的网站却调用不成功呀，大佬 @zhile-io

**Comment by LaiBaoYuan** [comment]
<img width="646" alt="image" src="https://github.com/zhile-io/pandora/assets/89441249/c32c6324-8a8b-422a-96f0-90bd7d4460b9">

**Comment by zhile-io** [comment]
你要更新版本，会有arkose的。
