### ISSUE TITLE
Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app. 获取token这种问题，怎么办呀！

### ISSUE THREAD

**Issue by Aniu456** [zhile-io/pandora#293]

**Comment by WenLiXue** [comment]
我也有这样的问题

**Comment by nxuu** [comment]
我也是这样 不知道为什么 获取不到access token

**Comment by shawn2016** [comment]
+1

**Comment by russul** [comment]
+1

**Comment by zhile-io** [comment]
由于openai的改动，插件已不再能过去token。如果第三方账号只能去官方获取。

**Comment by russul** [comment]
使用时出现如下错误提示


【An error occurred. Either the engine you requested does not exist or there was another issue processing your request. If this issue persists please contact us through our help center at help.openai.com】




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhile-io/pandora"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月29日(星期天) 中午1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhile-io/pandora] Error: access_denied, Your version of the ChatGPT app is out of date. Please update to the newest build of the app. 获取token这种问题，怎么办呀！ (Issue #293)





 
Closed #293 as completed.
