### ISSUE TITLE
用postman来访问接口

### ISSUE THREAD

**Issue by dd123-a** [zhile-io/pandora#294]
义父们，接口文档对于我来说有点太难理解了，我不知道具体应该设置哪些参数，有大佬可以给出具体的实例吗

**Comment by dd123-a** [comment]
除了头部带有access token外，我在请求体带有{
    "msg": "hi",
    "type": "text",
    "model":"gpt3.5-turbo",
    "action":"next"
}
返回的结果为{
    "detail": "Hmm...something seems to have gone wrong."
}，该怎么解决

**Comment by dd123-a** [comment]
使用https://ai.fakeopen.com/api/conversation/talk之后，请求体为{
    "prompt": "Hello, how are you?",
    "model": "gpt-3.5-turbo",
    "message_id": "ec4f8401-ffd0-4214-a9e9-3f087be911e2",
    "parent_message_id": "50974df0-288f-4701-ae88-3c0914fbf441",
    "stream": true
}，返回的结果{
    "detail": "Method Not Allowed"
}，有点难蚌

**Comment by dd123-a** [comment]
还是希望有更详细的接口文档把，包括详细的参数说明，麻烦了

**Comment by undefinedcodezhong** [comment]
http api那套不是很好用，不确定现在的维护情况，建议模拟api的接口方式，给你一个python代码参考：
```
import requests
import json

API_KEY = '[access token]/[share token]/[pool token]'
API_URL = "https://ai.fakeopen.com/v1/chat/completions"
headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}
data = {
    "model": "gpt-3.5-turbo",
    "messages": [{"role":"user", "content":"1+1"}]
}
response = requests.post(API_URL, headers=headers, data=json.dumps(data))
if response.status_code == 200:
    response = response.json()
    print(response["choices"][0]["message"]["content"])
```

**Comment by jiupinjiandingshi** [comment]
使用pooltoekn的账号必须开gpt 官方额度的账户吗？
