### ISSUE TITLE
 fakeapi项目能得到4.0fakeapi吗 

### ISSUE THREAD

**Issue by dandandujie** [zhile-io/pandora#295]

**Comment by dandandujie** [comment]
我给我原本的账号订阅了plus，然后在申请4.0api，如果fakeapi项目可以得到fake 4.0api的话，不知道哪个大佬能告诉我具体怎么操作。因为我看那个项目是用账号密码得到token，但我记得3.5和4.0是分开的key，我如果继续输入我的账号密码的话，应该还是生成3.5的api，得不到4.0的api。如果这个项目做不到的话，不知道哪个大佬能说说还有没有别的办法免费调用4.0不消耗余额。

**Comment by undefinedcodezhong** [comment]
通过access token 逆向或者说模拟的key,  不区分3.5和4.0， 通过模型名称会自动调用对应的模型。但是注意和web页面共享额度， 所以 plus 账户 3小时50msg 的限制仍然存在。

**Comment by dandandujie** [comment]
谢谢大佬！！！
