### ISSUE TITLE
请教下为什么用nginx代理了端口页面显示不正常

### ISSUE THREAD

**Issue by daerbiubiu** [zhile-io/pandora#298]
如图所示，点击access token登录也没有反应![image](https://github.com/zhile-io/pandora/assets/147224385/3d71247a-515a-4d99-9885-c264123a011d)
通过docker部署
docker run  -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora

nginx使用的配置是 
server {
        listen 80;
        server_name your_domain_name;        
        location / {
            proxy_pass http://127.0.0.1:8899;
        }

**Comment by zhile-io** [comment]
刷新以后是否还是如此？

**Comment by csu-orange** [comment]
把所有请求头都代理，你看一下有没有冲突的配置，可能是这样的。

**Comment by daerbiubiu** [comment]
> 把所有请求头都代理，你看一下有没有冲突的配置，可能是这样的。

请问有参考的配置命令吗？谢谢

**Comment by duzhuoshanwai** [comment]
```  
location / {
        proxy_pass http://172.17.0.2:8018;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

**Comment by csu-orange** [comment]
server {
    listen 80;
    server_name your_domain.com; # 如果有域名，请替换成你的域名

    location / {
        proxy_pass http://0.0.0.0:8899;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
# 这是我使用的，一切正常。

**Comment by daerbiubiu** [comment]
以上两位，非常感谢，现在工作已经正常了，之前可能是头部设置和其他部分有冲突
