### ISSUE TITLE
如图所示

### ISSUE THREAD

**Issue by TDB666** [zhile-io/pandora#301]
![屏幕截图 2023-10-28 053414](https://github.com/zhile-io/pandora/assets/149206955/f302a058-4389-4368-8923-05ff27a881b5)

**Comment by digitalboy** [comment]
+1

**Comment by ryoguo** [comment]
+1

**Comment by TDB666** [comment]
> +1

您好，请问您解决了这个问题吗

**Comment by TDB666** [comment]
> +1
您好，请问您解决了这个问题吗
