### ISSUE TITLE
ai.fakeopen.com 服务全挂了啊

### ISSUE THREAD

**Issue by LaiBaoYuan** [zhile-io/pandora#303]
<img width="2038" alt="image" src="https://github.com/zhile-io/pandora/assets/89441249/0bf17832-5cb5-47ca-a689-4c893cba7b4c">

**Comment by CodeZhangBorui** [comment]
同问

**Comment by mycurjerry** [comment]
是的，我这里也一样

**Comment by skyrise-l** [comment]
我也是，希望尽快能解决

**Comment by jasonhejiahuan** [comment]
是的，会显示`<!DOCTYPE html> <html lang="zh-cn"> <head> <meta charset="utf-8"/> <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/> <title>出错了</title> </head> <body> <p>你所访问的页面出错了！</p> <p>可前往本站<a href="https://status.fakeopen.com" target="_blank">服务状态页面</a>查看更多服务状态。</p> <p><div class="cf-error-details cf-error-524"> <h1>A timeout occurred</h1> <p>The origin web server timed out responding to this request.</p> <ul> <li>Ray ID: 81cf72770effc36d</li> <li>Your IP address: 35.230.88.164</li> <li>Error reference number: 524</li> <li>Cloudflare Location: Seattle</li> </ul> </div> </p> </body> </html>`

**Comment by walmt** [comment]
同样情况，希望作者大大看一看~

**Comment by hk59775634** [comment]
私有化部署也是一样的问题。是不是chat.openai.com的接口又调整导致的无法正常使用啊？

**Comment by zhheo** [comment]
私有部署也连不上了

**Comment by VJ852** [comment]
近期老是挂

**Comment by Sanguine-00** [comment]
![image](https://github.com/zhile-io/pandora/assets/18140259/b5eb2ddd-26a3-43f5-8488-c6bb0f6fe156)
的确用不了, 环境变量手动配置域名也不行.

**Comment by monokuma-top** [comment]
同问

**Comment by MadisonWirtanen** [comment]
cy

**Comment by tauruswei** [comment]
同问

**Comment by WeigangLu** [comment]
同问！！

**Comment by yuwangi** [comment]
+1

**Comment by VJ852** [comment]
希望今天能修复

**Comment by BBrother-GFC** [comment]
百分比越来越少力
![image](https://github.com/zhile-io/pandora/assets/51117375/b9e2b7d6-ff73-4832-98d1-085da248b23e)

**Comment by VJ852** [comment]
> ![图像](https://user-images.githubusercontent.com/18140259/278785149-b5eb2ddd-26a3-43f5-8488-c6bb0f6fe156.png) 根本用不了，环境变量手动配置域名也行。

行还是不行？

**Comment by chengzx98** [comment]
遇到同样的问题 +1

**Comment by dujianchi** [comment]
如果我有一个可以访问openai的服务器，我能不能自己搭一个fakeopen？

**Comment by skyrise-l** [comment]
我使用私有化部署直接调用openai的backend接口也报错，是不是接口调整了

**Comment by daishuge** [comment]
希望尽快解决，毕竟我的项目全是基于pandora的
（ｉДｉ）

**Comment by joeaki1983** [comment]
> 私有部署也连不上了

你的私有部署也是基于api的吗

**Comment by joeaki1983** [comment]
> 私有部署也连不上了

私有部署是不是基于api的

**Comment by JerryXu09** [comment]
chat1登陆后直接没反应了 自己部署的serverless也是登陆后504网关超时 希望能尽快解决😀

**Comment by zhukunpenglinyutong** [comment]
插眼

**Comment by mycurjerry** [comment]
29日早我登录，发现已经修复了

**Comment by daishuge** [comment]
好好好，皆大欢喜，修复了，感谢大佬的努力

mycurjerry ***@***.***> 于 2023年10月29日周日 上午9:05写道：
