### ISSUE TITLE
又无法使用了 怀疑是代理出了问题

### ISSUE THREAD

**Issue by VJ852** [zhile-io/pandora#304]
有没有使用自定义代理的出来说一下呀 
自定义代理能不能用？

**Comment by VJ852** [comment]
![222222222222222222](https://github.com/zhile-io/pandora/assets/86582242/5b9f1a34-e09d-4f38-a044-7a74b21696da)

**Comment by ALEXsun0** [comment]
[FAKEOPEN 相关服务状态](https://status.fakeopen.com/)看这个
