### ISSUE TITLE
关于pandora

### ISSUE THREAD

**Issue by WillamWilliam** [zhile-io/pandora#308]
请问本地部署需要有很高的硬件要求吗？（例如需要服务器）

**Comment by liucangsong** [comment]
这个代理要求极低，我的一个服务器，不到1G内存跑的嗖嗖的

**Comment by joeaki1983** [comment]
> 这个代理要求极低，我的一个服务器，不到1G内存跑的嗖嗖的

部署的是token传API服务吗

**Comment by rodren-lion** [comment]
> > 这个代理要求极低，我的一个服务器，不到1G内存跑的嗖嗖的
> 
> 部署的是token传API服务吗

你可以用 api也可以直接登录账号 每次用每次登录。。。
