### ISSUE TITLE
ai.fakeopen.com不能用就挂了，能不能用自己的代理？有旁路由全局科学，需要怎么设置？

### ISSUE THREAD

**Issue by stkroot** [zhile-io/pandora#309]
docker部署的，需要怎么设置参数，才能直接走自己的代理呢？

有旁路由全局科学，直接打开openai是正常的。但使用pandora就打不开。看评论好像是因为ai.fakeopen.com代理挂了？

**Comment by BBrother-GFC** [comment]
个人感觉是openai改了啥，我用自己的代理也不行（用本地环境去访问OPENAI也不行）

**Comment by TonyLiooo** [comment]
> 个人感觉是openai改了啥，我用自己的代理也不行（用本地环境去访问OPENAI也不行）

感觉本地代理也是用了ai.fakeopen.com

**Comment by lanyirenjg** [comment]
![1698472149637](https://github.com/zhile-io/pandora/assets/78648003/88102d2f-79a2-4ee8-8f55-97b63b3a61a3)
![1698472172672](https://github.com/zhile-io/pandora/assets/78648003/7b41a50b-9806-406d-b709-8da912464d17)

**Comment by lanyirenjg** [comment]
> ![1698472149637](https://user-images.githubusercontent.com/78648003/278793874-88102d2f-79a2-4ee8-8f55-97b63b3a61a3.png) ![1698472172672](https://user-images.githubusercontent.com/78648003/278793889-7b41a50b-9806-406d-b709-8da912464d17.png)

docker部署的，打不开了，不知道什么情况。ai.fakeopen.com是正常的

**Comment by BBrother-GFC** [comment]
![image](https://github.com/zhile-io/pandora/assets/51117375/a6bfa299-231e-403a-ba3e-5bb91d301064)
从这里看才行

**Comment by BBrother-GFC** [comment]
你要看fakeopen的话

**Comment by RickyWang111** [comment]
我用自己的美国服务器直接去访问https://chat.openai.com/auth/login  输入了账号密码又一直返回到了登录界面，有没有兄弟有同样的情况？

**Comment by nxuu** [comment]
是不是openai官方加密了。。。fakeopen是不是以后不能用了？

**Comment by stkroot** [comment]
> 个人感觉是openai改了啥，我用自己的代理也不行（用本地环境去访问OPENAI也不行）

应该是你的代理不行，我用自己的代理正常

**Comment by Saktawdi** [comment]
寄，坐等大佬更新

**Comment by rodren-lion** [comment]
应该代理服务挂了 ？登录  返回 timeout。。
