### ISSUE TITLE
使用 AI-PDF 插件报错

### ISSUE THREAD

**Issue by JackuXL** [zhile-io/pandora#31]
使用 AI-PDF 插件，生成到一半时报错 error in input stream，在官网不会出现类似问题

**Comment by JackuXL** [comment]
@zhile-io ![image](https://github.com/zhile-io/pandora/assets/58510349/fb2f2fc4-a2f8-4fde-920c-9ddb893b2402)

**Comment by zhile-io** [comment]
可以开个全局梯子试试
