### ISSUE TITLE
关于本地部署和体验网站

### ISSUE THREAD

**Issue by WillamWilliam** [zhile-io/pandora#310]
本地部署是不是就不怕体验网站会出现的的问题

**Comment by lukangkang** [comment]
全挂了，用fakeopen接口的cloud版和用本地接口的http服务版都不行了。

**Comment by mycurjerry** [comment]
感谢zhile，已经修复了

**Comment by yetao-git** [comment]
> 全挂了，用fakeopen接口的cloud版和用本地接口的http服务版都不行了。

哈喽，http服务启动以后，ip:port，访问为什么访问不通呢
