### ISSUE TITLE
cf导致无法使用 

### ISSUE THREAD

**Issue by fenglindubu** [zhile-io/pandora#312]
ChatGPT error 524: <!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
<title>出错了</title>

</head>
<body>
<p>你所访问的页面出错了！</p>
<p>可前往本站<a href="https://status.fakeopen.com/" target="_blank">服务状态页面</a>查看更多服务状态。</p>
<p><div class="cf-error-details cf-error-524">
<h1>A timeout occurred</h1>
<p>The origin web server timed out responding to this request.</p>
<ul>

**Comment by rodren-lion** [comment]
好想同样问 题time out

**Comment by FujiwaraChoki** [comment]
> 好想同样问 题time out

xD

**Comment by pepperdog999** [comment]
问题修复了么？

**Comment by mycurjerry** [comment]
修复了，感谢zhile！
