### ISSUE TITLE
请教下如何去官方获取token

### ISSUE THREAD

**Issue by mycurjerry** [zhile-io/pandora#317]
由于openai的改动，插件已不再能过去token。如果第三方账号只能去官方获取。

_Originally posted by @zhile-io in https://github.com/zhile-io/pandora/issues/293#issuecomment-1784000395_
            
ai.fakeopen.com/auth不能获取，显示Error : access _ denied , Your version of the ChatGPT app is out of date . Please update to the newest build of the app，谁知道具体如何去官方获取呢

**Comment by lnts2015** [comment]
好好看文档说明。
