### ISSUE TITLE
可以添加对newbing的支持吗?

### ISSUE THREAD

**Issue by mirrordg** [zhile-io/pandora#32]
几个月前newbing增加了对ip和定位信息的门槛,导致挂全局梯子也有一定概率被重定向,希望大佬能够加一个访问newbing 的方式只需要对简单的聊天支持即可,感谢大佬的付出

**Comment by zhile-io** [comment]
开源社区里应该有newbing的代理库的，你可以找找。目前没精力去研究newbing了。
