### ISSUE TITLE
请问docker启动的，如何使用http访问，按照wiki格式设置docker格式报错

### ISSUE THREAD

**Issue by yetao-git** [zhile-io/pandora#324]
1. 使用 docker 部署，使用命令行模式已启动成功
2. 想换成 http 模式访问，启动命令：docker run -it --rm -e PANDORA_SERVER="本地ip:8888"
3. 提示错误：
WARNING  | pandora.bots.server:run:76 - Serving on http://xxx:8888
### Error occurred: [Errno 99] Cannot assign requested address

**Comment by zhile-io** [comment]
用0.0.0.0:8888

**Comment by yetao-git** [comment]
niubi

**Comment by yetao-git** [comment]
> 用0.0.0.0:8888
启动成功了，显示：run:76 - Serving on http://0.0.0.0:8844。

但是一个新的问题：我是用postman， http://机器ip:8844/api/xxx，连接是不通的，Could not send request
请问大佬这是什么清空
