### ISSUE TITLE
请问大佬：使用 docker 部署 cloud模式，加上PANDORA_CLOUD 变量，启动后为什么还是命令行模式呢？

### ISSUE THREAD

**Issue by yetao-git** [zhile-io/pandora#326]
请问我使用命令：docker run -it --rm -e PANDORA_CLOUD -e PANDORA_ACCESS_TOKEN="xx" pengzhile/pandora，部署cloud，为什么还是命令行模式呢？
![1698659237487](https://github.com/zhile-io/pandora/assets/52268477/0848c3c2-c303-43fb-906b-a2997430eec3)

**Comment by geoferrywu** [comment]
端口没设？
docker run  -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:9999 -p 9999:9999 -d pengzhile/pandora

**Comment by yetao-git** [comment]
> 端口没设？ docker run -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:9999 -p 9999:9999 -d pengzhile/pandora

哇！原来是这样，我开wiki里面没说要这样。。 还是年轻了  谢谢谢谢大佬！
