### ISSUE TITLE
请问使用 docker cloud 启动的方式 为啥访问被拒绝呢？

### ISSUE THREAD

**Issue by Chao-Sky** [zhile-io/pandora#329]
![image](https://github.com/zhile-io/pandora/assets/45475000/b7de987b-9c99-43df-849c-61dee5703bbd)

![image](https://github.com/zhile-io/pandora/assets/45475000/4499b86b-7327-4b39-aaf6-a22d59f486b8)

**Comment by EdwinOlders11** [comment]
试试地址换0.0.0.0？

**Comment by unights** [comment]
`PANDORA_SERVER`指定的地址是`127.0.0.1:12111`，但这里是容器内地址，容器本身和物理机是隔离的，物理机无法访问到运行在容器内本地端口上的服务。首先要改成`0.0.0.0:12111`，让服务暴露出来，然后再指定`docker`端口映射，将容器的12111端口映射到物理机的某个端口上，再通过web访问物理机的地址。

**Comment by Chao-Sky** [comment]
> `PANDORA_SERVER`指定的地址是`127.0.0.1:12111`，但这里是容器内地址，容器本身和物理机是隔离的，物理机无法访问到运行在容器内本地端口上的服务。首先要改成`0.0.0.0:12111`，让服务暴露出来，然后再指定`docker`端口映射，将容器的12111端口映射到物理机的某个端口上，再通过web访问物理机的地址。

请问具体怎么操作呢，对 docker 不太熟悉，能否提供一段启动命令并且知道端口跟映射端口呢？

**Comment by Chao-Sky** [comment]
> `PANDORA_SERVER`指定的地址是`127.0.0.1:12111`，但这里是容器内地址，容器本身和物理机是隔离的，物理机无法访问到运行在容器内本地端口上的服务。首先要改成`0.0.0.0:12111`，让服务暴露出来，然后再指定`docker`端口映射，将容器的12111端口映射到物理机的某个端口上，再通过web访问物理机的地址。

麻烦帮忙纠错：docker run -it --name mylocalgtp -p 12111:12111 -e PANDORA_CLOUD=cloud PANDORA_SERVER=0.0.0.0:12111 --rm pengzhile/pandora

**Comment by Chao-Sky** [comment]
> `PANDORA_SERVER`指定的地址是`127.0.0.1:12111`，但这里是容器内地址，容器本身和物理机是隔离的，物理机无法访问到运行在容器内本地端口上的服务。首先要改成`0.0.0.0:12111`，让服务暴露出来，然后再指定`docker`端口映射，将容器的12111端口映射到物理机的某个端口上，再通过web访问物理机的地址。

搞好了，感谢大佬指点：docker run -it --rm --name mylocalgtp -p 12111:12111 -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:12111 pengzhile/pandora
