### ISSUE TITLE
如何做到像https://chat.zhile.io一样需要输入账号密码才能登录

### ISSUE THREAD

**Issue by jacksplwxy** [zhile-io/pandora#34]
我是参考Docker Hub运行文档并执行以下命令行
docker pull pengzhile/pandora
docker run  \
--rm  \
--name pandora \
-e PANDORA_ACCESS_TOKEN=我的token  \
-e PANDORA_SERVER=0.0.0.0:8080  \
-p 8080:8080  \
-d pengzhile/pandora
确实能够通过ip+端口访问到网页。
但是有个问题是这个网页地址自带token，任何人都可以访问并调用我账号的chatgpt，请问如何做到像 https://chat.zhile.io 一样需要输入账号密码登录后才能调用chatgpt呢？ 我尝试过不配置PANDORA_ACCESS_TOKEN，但是无法启动容器

**Comment by shuaiplus** [comment]
你用的是pandotra，你要的是pandora-cloud

**Comment by junlongzzz** [comment]
需要以cloud方式运行，加入环境变量 `PANDORA_CLOUD=cloud` 就会有类似chatgpt的网页界面

**Comment by jacksplwxy** [comment]
可以了 感谢哈~
