### ISSUE TITLE
账号密码无法正常登录了，出现以下提示：

### ISSUE THREAD

**Issue by NIUKEGE** [zhile-io/pandora#343]
{"detail":"invalid login token"}
![image](https://github.com/zhile-io/pandora/assets/131988156/5154a8d4-3400-42dd-967a-2e0c6d615eef)

**Comment by NIUKEGE** [comment]
请大佬尽快修复

**Comment by LaiBaoYuan** [comment]
> 请大佬尽快修复

大佬是你谁啊
