### ISSUE TITLE
大佬，现在通过API查询share token的用度信息，没有了usage内容了

### ISSUE THREAD

**Issue by JerryWesler** [zhile-io/pandora#347]
[查询 share token 的接口](https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#1-tokeninfoshare-token)，现在返回的信息只有这些内容：
{"email":"----","expire_at":----,"user_id":"----"}
以前是能看到usage的，麻烦大佬有空修复下，感谢。

**Comment by zhile-io** [comment]
<img width="902" alt="image" src="https://github.com/zhile-io/pandora/assets/144572553/1ef9e29c-bc80-46b4-9cb2-3f72299d276d">
