### ISSUE TITLE
accessToken是只有两个星期吗？

### ISSUE THREAD

**Issue by wyoo6** [zhile-io/pandora#349]
大佬们，accessToken是有两个星期不需要挂vpn就可以直接访问的功能。然后过了两个星期后就得挂vpn才能访问？还是accessToken只有两个星期，两个星期后就不可以使用了？

**Comment by lnts2015** [comment]
![image](https://github.com/zhile-io/pandora/assets/6037915/b4130ec0-4f03-4a59-886e-22809e2b3e03)

使用前先认真看遍文档。

**Comment by mycurjerry** [comment]
意思是Pandora通过accesstoken无门槛使用对话，只要accesstoken有效就可以对话。有两种获取方式：ai.fakeopen.com/auth1无门槛获取，但有时获取不成功，还有一种方式https://github.com/zhile-io/pandora/issues/325#issuecomment-1784650656，有门槛。从获取成功开始计时，accesstoken有效期14天，过期acc tk报废，重新获取即可

**Comment by monkey-sking** [comment]
我这里有个现象是，多地点登陆，会失效
新地点登陆后失效，而不是两周

只保留一个不会

**Comment by amerina** [comment]
多点登录可能导致token刷新了

**Comment by wyoo6** [comment]
感谢感谢

**Comment by wyoo6** [comment]
感谢感谢
