### ISSUE TITLE
请修复chat.zhile.io的"Regenerate"按钮导致的额外刷新问题

### ISSUE THREAD

**Issue by daishuge** [zhile-io/pandora#35]
🐛 问题描述

在使用chat.zhile.io与GPT-4进行交流时，我注意到一个小问题。当GPT-4正在生成回答的过程中，界面上仍然显示"Regenerate"按钮。由于这个设计，我多次误点击了"Regenerate"，导致回答被不必要地重新生成。

🕒 影响

这个问题浪费了我的GPT-4使用次数，同时也影响了用户体验。

🛠️ 预期行为

当GPT-4正在生成内容的时候，"Regenerate"按钮应该改为生成中。

🙏 请求

希望开发团队能尽快修复这个小问题，以优化用户体验和资源使用。

我不确定这是我个人操作的问题还是网页的失误.
感谢您的时间和努力！期待这个问题能够得到解决。

**Comment by zhile-io** [comment]
我也很希望修复这个问题，但我并没有前端的源码，要从被压缩混淆的源码修复这一点非常困难。
