### ISSUE TITLE
账号被别人访问了？

### ISSUE THREAD

**Issue by congyong** [zhile-io/pandora#359]
突然冒出来 一堆别人的问答记录, 
发生了什么--
![image](https://github.com/zhile-io/pandora/assets/32157609/65a80179-eb3a-4651-86d2-3e67bde6bfef)

**Comment by zhile-io** [comment]
server模式启动吗？

**Comment by congyong** [comment]
> server模式启动吗？

是的  -e PANDORA_SERVER=0.0.0.0:8888 -p 8888:8888    -it --rm pengzhile/pandora

**Comment by zhile-io** [comment]
server模式打开就用，不要毫无保护地暴露在官网上。可以设置nginx basic auth保护一下。

**Comment by zhile-io** [comment]
对，这使用网络安全空间搜索引擎很容易找到。

**Comment by congyong** [comment]
> 对，这使用网络安全空间搜索引擎很容易找到。

我试了一下 nginx  basic auth, 以及 端口转发,原因是 docker 只能映射端口转发,我的服务器python 版本问题，不方便serverless 部署--- 
所以思路是 屏蔽端口的A的入站访问,  用端口B转发 

server {
    listen       8888;
    server_name  localhost;

    location /{
        auth_basic "Input the password";
        auth_basic_user_file "/root/auth_basic_user_file";
        proxy_pass  http://localhost:65535;
        proxy_set_header   Host  $host;
        proxy_set_header   X-Real-IP   $remote_addr;
        proxy_set_header   X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto    $scheme;

        access_log  /root/ng.log ;
    }

}

发现 只要经过端口转发是刷不出来 chatgpt的历史 也不能问答---  

仅做记录.
