### ISSUE TITLE
纯交流，这个包的实现原理是什么？

### ISSUE THREAD

**Issue by jefferyjob** [zhile-io/pandora#41]
为什么这个包不借助VPN就可以实现直接访问 openai 的接口？

是否作者自己搭建了一个服务器环境，最终这个包走的先是作者的服务器环境，然后作者的服务器转发到 openai 的接口上面？？

**Comment by tomhup** [comment]
文件 openai ，api.py 文件。 默认发到openfake

**Comment by sjlleo** [comment]
作者对外提供了一个 API 接口服务，你的流量实际上是先通过 ai.fakeopen.com 然后再到达 OpenAI 上的，

这样有利有弊，好处是不用在自己维护一个 Proxy Backend，这个后端还自带破 Cloudflare 5s 墙，
坏处是如果你需要在一个内网环境下搭建一个完整的服务，就会很不方便，这种情况只能着手自己实现这个后端，
不过网上也有开源的轮子，效果差异都比较大，需要自己多去尝试就是了

**Comment by jefferyjob** [comment]
感谢各位告知
