### ISSUE TITLE
如何实现统一入口地址，根据不同人的share_token来进行会话隔离对话

### ISSUE THREAD

**Issue by taxueqinyin** [zhile-io/pandora#46]
想给家人朋友用，看了文档似乎可以通过先保存tokens_file，再访问时携带query参数 ?token=tokenName 的方法曲线完成，有没有一种比较直接的方式，起服务时不需要选择tokens文件与token，访问地址时需要输入share_token进入自己的对话，直接完成我这个目的？

**Comment by undefinedcodezhong** [comment]
pandora-cloud应该能满足你

**Comment by zhile-io** [comment]
置顶issue有关于share token的介绍。
