### ISSUE TITLE
本地启动输入账号和密码，出现这个的原因是什么，昨天还是好用的

### ISSUE THREAD

**Issue by HappyPot** [zhile-io/pandora#51]
![微信图片_20230919224714](https://github.com/zhile-io/pandora/assets/22255025/ca037635-b8e9-4ec9-958c-a94245bf6c3f)

**Comment by HappyPot** [comment]
> [#14 (comment)](https://github.com/zhile-io/pandora/issues/14#issue-1894160042) 检查你的电脑时间

感谢，确实这个原因，我同步了电脑的时间就可以了，不过时间只相差了几分钟，这样就不能用了，好严格

**Comment by Vulcan-W** [comment]
改了时间还是不行啊，试了北京时间和美国时间

**Comment by undefinedcodezhong** [comment]
@Vulcan-W 
现在出了新的问题：https://github.com/zhile-io/pandora/issues/84#issuecomment-1734734145
