### ISSUE TITLE
探讨一下：使用pandora，登录IP是本机，还是搭建pandora的机子ip

### ISSUE THREAD

**Issue by sw586** [zhile-io/pandora#54]
如题

**Comment by zhile-io** [comment]
取决于你的登录相关环境变量，具体请看文档。

**Comment by sw586** [comment]
> 取决于你的登录相关环境变量，具体请看文档。
docker run -e PANDORA_ACCESS_TOKEN=11111111 -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora
和
docker run -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora
两种分别登录ip是哪个
