### ISSUE TITLE
pandora无法使用，无论是密码登录还是token的方式

### ISSUE THREAD

**Issue by xjy198903** [zhile-io/pandora#55]
如题

**Comment by xaswq** [comment]
是的，泪目

**Comment by XiaoQi-W** [comment]
我也是

**Comment by mactrash** [comment]
</head>
<body>
<p>你所访问的页面出错了！</p>
<p>可前往本站<a href="https://status.fakeopen.com" 
target="_blank">服务状态页面</a>查看更多服务状态。</p>
<p><div class="cf-error-details cf-error-522">
  <h1>Connection timed out</h1>
  <p>The initial connection between Cloudflare's network and the origin web 
server timed out. As a result, the web page can not be displayed.</p>

**Comment by tchivs** [comment]
登陆不上，显示Error request preauth.

**Comment by xjy198903** [comment]
可能就是上游出错了，我现在登录gpt官方是可以用的

**Comment by XiaoQi-W** [comment]
![image](https://github.com/zhile-io/pandora/assets/43028441/1a518cce-8b4e-43d2-a2bb-4eddb59c9ef5)

**Comment by buggzd** [comment]
加一：
Get preauth cookie failed.

**Comment by jianxianglisir** [comment]
![image](https://github.com/zhile-io/pandora/assets/63116117/ebbe5084-ba09-4001-b708-f64fcc610cbd)
![image](https://github.com/zhile-io/pandora/assets/63116117/0151025e-f807-44bd-a5cc-0a7a095c6d02)
部分服务出现故障

**Comment by cndaqiang** [comment]
<img width="412" alt="image" src="https://github.com/zhile-io/pandora/assets/26620270/8dd82e92-8f99-44bd-81d0-764105c3f4e4">
{"detail":"error request login url"}

**Comment by mactrash** [comment]
chatgpt site can login

**Comment by dao-zero** [comment]
感觉是作者的代理挂掉了,现在好了

**Comment by xjy198903** [comment]
皆大欢喜
