### ISSUE TITLE
好像无法使用了

### ISSUE THREAD

**Issue by xaswq** [zhile-io/pandora#56]

**Comment by xaswq** [comment]
![image](https://github.com/zhile-io/pandora/assets/85377380/f10397ba-12c4-412b-b106-3316a72c7283)

**Comment by sw586** [comment]
就在这分钟好像全部挂了
![image](https://github.com/zhile-io/pandora/assets/24788222/ad99c91a-c28e-4c57-ae84-a3b49904ede0)

**Comment by KickCashew** [comment]
我也一样，不能用了

**Comment by Zhangyida987412365** [comment]
俺也一样

**Comment by r81892489** [comment]
一样，这个应该是官方api出问题了，之前是token 提示1h 重试，刚重新部署又出现同样问题

**Comment by kico0909** [comment]
同上

**Comment by Davidtian0905** [comment]
一样

**Comment by dao-zero** [comment]
快来看，作者大大修复了

**Comment by 315386775** [comment]
重新获取token就可以了

**Comment by xaswq** [comment]
恢复了！

> 快来看，作者大大修复了
