### ISSUE TITLE
欢迎归来！！

### ISSUE THREAD

**Issue by 315386775** [zhile-io/pandora#58]
手机端正常用，开心

**Comment by xaswq** [comment]
恢复了！！！

**Comment by kelvinlee** [comment]
为什么我的还不行?

**Comment by 315386775** [comment]
@kelvinlee 你重新获取一下token试试

**Comment by huaqiesf** [comment]
huifule

**Comment by kelvinlee** [comment]
@315386775 重新获取了 还行不行 docker 里还是报错 ```pandora.bots.server:__handle_error:99 - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.```
