### ISSUE TITLE
docker compose文件

### ISSUE THREAD

**Issue by liwuge** [zhile-io/pandora#59]
version: "3"
services:
  pandora-container:
    image: pengzhile/pandora
    restart: unless-stopped
    environment:
      - PANDORA_CLOUD=cloud
      - PANDORA_SERVER=0.0.0.0:8899
      - CHATGPT_API_PREFIX=https://ai.fakeopen.com/api/
    ports:
      - 8899:8899

这是报错信息
![image](https://github.com/zhile-io/pandora/assets/140242192/ae6421ca-d83c-4d58-bac3-2acc6e25fe73)

为什么运行不了

**Comment by zhile-io** [comment]
这是你docker本身的问题，应该是网络问题。

**Comment by liwuge** [comment]
> 这是你docker本身的问题，应该是网络问题。

那我的配置文件应该怎么写
网络问题的话我开了代理
