### ISSUE TITLE
正确的指定ACCESS_TOKEN方式是什么

### ISSUE THREAD

**Issue by sw586** [zhile-io/pandora#60]
docker run  -e PANDORA_ACCESS_TOKEN=56495464645646adasdasdadsadsasdasdasfafasfasfasfa -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora

我用上面的方式启动页面是这样的：
![image](https://github.com/zhile-io/pandora/assets/24788222/22a65799-18fd-492d-9369-9a0e0f09adbe)

如果使用docker run  -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d pengzhile/pandora
使用ACCESS_TOKEN登录又正常

大佬们指点一下 谢谢！想实现免登录，至于安不安全的先不说

**Comment by zhile-io** [comment]
第一种你应该是nginx做了反代，然后一些诸如host之类的headers没有设置正确。

**Comment by sw586** [comment]
> 第一种你应该是nginx做了反代，然后一些诸如host之类的headers没有设置正确。

确实是这样，发现用第一种不开反向代理确实不需要登录，但是界面就不一样了，带上PANDORA_CLOUD=cloud 可以免登录吗，发现带了PANDORA_CLOUD=cloud就启动不了

**Comment by stkroot** [comment]
奇怪，我也遇到了。 PANDORA_SERVER 模式，使用反向代理就不正常，和楼主一样，只可以ip访问。
PANDORA_CLOUD 模式就一切正常，反向代理也正常。

**Comment by qingshengwen** [comment]
我也发现了这个问题，貌似是使用反代，并且前端是以https访问的时候就会出现，
打开F12看网络请求，会发现获取历史聊天记录的那个接口用的是http访问，就导致请求被浏览器block了

**Comment by zhile-io** [comment]
> 我也发现了这个问题，貌似是使用反代，并且前端是以https访问的时候就会出现， 打开F12看网络请求，会发现获取历史聊天记录的那个接口用的是http访问，就导致请求被浏览器block了

你反代的一些header没配置好。

**Comment by qingshengwen** [comment]
> > 我也发现了这个问题，貌似是使用反代，并且前端是以https访问的时候就会出现， 打开F12看网络请求，会发现获取历史聊天记录的那个接口用的是http访问，就导致请求被浏览器block了
> 
> 你反代的一些header没配置好。

大佬，目前nginx的反代配置是这样：
`proxy_pass http://192.168.123.4:20005;
proxy_set_header Host $http_host;
proxy_buffering off;

proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`

查看网络请求，只有这2个接口是http的，其他的都没问题
http://chat.xxx.link/api/models
http://chat.xxx.link/api/conversations?offset=0&limit=20

**Comment by qingshengwen** [comment]
已搞定，感谢代码，问了下gpt，原来还要设置一个属性
`
proxy_set_header X-Forwarded-Proto $scheme;
`
