### ISSUE TITLE
无法使用代码解释器

### ISSUE THREAD

**Issue by zwz211123** [zhile-io/pandora#61]
GPT4的代码解释器，不管怎么样，就是上传不了文件

**Comment by zhile-io** [comment]
截图看看

**Comment by zwz211123** [comment]
![Screenshot_2023-09-20-19-40-34-36_439a3fec0400f8974d35eed09a31f914](https://github.com/zhile-io/pandora/assets/139982393/86390396-3791-498c-8725-80b25a827646)

**Comment by zhile-io** [comment]
你这个地址我不认识，而且连标都给抹了。

**Comment by zwz211123** [comment]
内核还是你的，只不过外面多加了一层
