### ISSUE TITLE
share token 并发问题

### ISSUE THREAD

**Issue by doveppp** [zhile-io/pandora#64]
我的Pool Token中只有两个share token，但却可以两个以上问题同时回答。
不知道是不是openai更新了？

**Comment by wushig** [comment]
请问老哥是怎么弄的  我是用了两个不同的账号的accesstoken，然后生成两个share_token，在合并成一个pooltoken，然而并不能实现两个人同时回答

**Comment by wushig** [comment]
你调用的是哪个接口？

**Comment by doveppp** [comment]
我在官网测了下好像一个账号可以同时多个对话了

**Comment by wushig** [comment]
我在使用pool token的时候调用fakeopen接口也要收到同一个IP的限流的限制吗

**Comment by zhile-io** [comment]
> 我的Pool Token中只有两个share token，但却可以两个以上问题同时回答。
> 不知道是不是openai更新了？

确实更新了，可以并发，不过还是收到小时和天的消息条数限制。
