### ISSUE TITLE
http服务方式启动，这个不懂怎么启动，请大佬解释一下。

### ISSUE THREAD

**Issue by digitalboy** [zhile-io/pandora#67]
http服务方式启动，这个不懂怎么启动，请大佬解释一下。

**Comment by undefinedcodezhong** [comment]
就是启动的时候加-s ip:port参数
比如：`pandora -s localhost:8888`
更多的参数使用规则参考文档：https://github.com/zhile-io/pandora/blob/master/doc/wiki.md#%E7%A8%8B%E5%BA%8F%E5%8F%82%E6%95%B0

**Comment by digitalboy** [comment]
> 就是启动的时候加-s ip:port参数 比如：`pandora -s localhost:8888` 更多的参数使用规则参考文档：https://github.com/zhile-io/pandora/blob/master/doc/wiki.md#%E7%A8%8B%E5%BA%8F%E5%8F%82%E6%95%B0

非常感谢啊！
