### ISSUE TITLE
想通过ip+端口?token=token_name的方式，进入到潘多拉GPT的使用界面

### ISSUE THREAD

**Issue by eternaling** [zhile-io/pandora#72]
我用的是源码启动方式
pandora-cloud --tokens_file /opt/gpt/pandora/token.json -v
token.json中存放了
{
"token_name":"token"
}
但是我通过 域名?token=token_name 的方式还是停留在了登录界面
在文档和其他issus苦寻无果
大佬可以帮我解谜一下么，感谢大佬们

**Comment by eternaling** [comment]
或者说，有什么办法可以
拿着access-token，进入潘多拉GPT的使用界面
我尝试用PHP写了一个跳转潘多拉GPT携带cookie的方式，好像行不通

**Comment by yorunning** [comment]
PANDORA_CLOUD不能带token直接用，PANDORA_SERVER模式可以

**Comment by eternaling** [comment]
感谢大佬
