### ISSUE TITLE
rate limit咨询

### ISSUE THREAD

**Issue by undefinedcodezhong** [zhile-io/pandora#73]
使用dashboard相关功能（https://ai.fakeopen.com/auth/platform/login 和 /dashboard/billing/subscription）的时候报错：
share token failed: {"detail":"rate limited."}
能问下，这是OpenAI的限制还是fakeopen的限制吗？我晾了一个小时没用，再查询还是报这个错。

**Comment by zero-one-dance** [comment]
我的也是

**Comment by walkskyer** [comment]
同问

**Comment by mycurjerry** [comment]
我隔了一天可以了

**Comment by undefinedcodezhong** [comment]
> 我隔了一天可以了

不是时间问题，之前是作者处理openai登录接口的问题，现在作者陆续修复了。
