### ISSUE TITLE
配一下url：openai.api_base = "https://ai.fakeopen.com/v1/"

### ISSUE THREAD

**Issue by xiatian12345** [zhile-io/pandora#74]
配一下url：openai.api_base = "https://ai.fakeopen.com/v1/"
如果用官方的api_key，会扣额度，如果用pandora turbo模拟的key，则免费

_Originally posted by @undefinedcodezhong in https://github.com/zhile-io/pandora/issues/20#issuecomment-1718774405_
      
试了下，还是不行啊
 405 {'error': {'message': 'Only POST requests are accepted.', 'type': 'invalid_request_error', 'param': None, 'code': 'method_not_supported'}} {'Date': 'Fri, 22 Sep 2023 18:11:34 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '183', 'Connection': 'keep-alive', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=haUWHvWVr2Ev5%2FuhOz3y8k2LjxC%2FgYCw%2FN%2F6fYNpNtYXefBbn9mugI1wCGpberzpXtaojfOJ3V%2FubqaZhG5dOaJ%2FFWal6k5619uG7dD08Jx0Udlbxjxa51ThB210elbsew%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '80ac82dbbe115168-HKG', 'alt-svc': 'h3=":443"; ma=86400'}

**Comment by undefinedcodezhong** [comment]
你是否开了代理？

**Comment by nxuu** [comment]
请问pandora turbo官方文档在哪儿呢? 我也想配置api

> ```
>           配一下url：openai.api_base = "https://ai.fakeopen.com/v1/"
> ```
> 
> 如果用官方的api_key，会扣额度，如果用pandora turbo模拟的key，则免费
> 
> _Originally posted by @undefinedcodezhong in [#20 (comment)](https://github.com/zhile-io/pandora/issues/20#issuecomment-1718774405)_
> 
> 试了下，还是不行啊 405 {'error': {'message': 'Only POST requests are accepted.', 'type': 'invalid_request_error', 'param': None, 'code': 'method_not_supported'}} {'Date': 'Fri, 22 Sep 2023 18:11:34 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '183', 'Connection': 'keep-alive', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=haUWHvWVr2Ev5%2FuhOz3y8k2LjxC%2FgYCw%2FN%2F6fYNpNtYXefBbn9mugI1wCGpberzpXtaojfOJ3V%2FubqaZhG5dOaJ%2FFWal6k5619uG7dD08Jx0Udlbxjxa51ThB210elbsew%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '80ac82dbbe115168-HKG', 'alt-svc': 'h3=":443"; ma=86400'}

请问pandora turbo官方文档在哪儿呢? 我也想配置api

**Comment by undefinedcodezhong** [comment]
https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md
还有其他文档你可以在项目的doc文件夹里找到：
![image](https://github.com/zhile-io/pandora/assets/40236765/27160020-27ea-4a0f-b757-38b3de3943e1)

**Comment by nxuu** [comment]
> https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md 还有其他文档你可以在项目的doc文件夹里找到： ![image](https://user-images.githubusercontent.com/40236765/270149728-27160020-27ea-4a0f-b757-38b3de3943e1.png)

有没有办法 可以开启chatgpt 的plus 然后用来当作open api呢?
chatgpt 3.5确实有时候回复比较傻.

**Comment by undefinedcodezhong** [comment]
@nxuu pandora只是提供一种反代方式，不会、也无法对账号本身的性质进行修改，所以得你的账号是plus账号，用turbo模拟的api才会有plus的能力

**Comment by nxuu** [comment]
> @nxuu pandora只是提供一种反代方式，不会、也无法对账号本身的性质进行修改，所以得你的账号是plus账号，用turbo模拟的api才会有plus的能力

如果我升级了plus账号 是不是接口就都开始用4.0了 就开始受到openai 官方几小时多少个问题的限制

**Comment by undefinedcodezhong** [comment]
你可以设置提问的model，plus账号也是可以使用更快但是更笨的3.5进行回复的

**Comment by nxuu** [comment]
> 你可以设置提问的model，plus账号也是可以使用更快但是更笨的3.5进行回复的

弄好了 感谢 已经在网站上用上gpt4了 原来gpt4是2022年1月的数据 我还一直以为是gpt4能够更新到现在的数据呢...

**Comment by undefinedcodezhong** [comment]
> > 你可以设置提问的model，plus账号也是可以使用更快但是更笨的3.5进行回复的
> 
> 弄好了 感谢 已经在网站上用上gpt4了 原来gpt4是2022年1月的数据 我还一直以为是gpt4能够更新到现在的数据呢...

其实是21年1月哦哈哈，因为清洗数据集也是一件很花精力和money的事情，openai在21年的数据上训练了gpt3.5和gpt4，只是4发布的时间晚一些。如果openai不清洗数据直接用最新网络数据训练，很快它就会被垃圾信息所污染了。
