### ISSUE TITLE
纯新手想请教一下大家，Pool token能否搭配Chatgpt Next web或其他项目使用？

### ISSUE THREAD

**Issue by walkchen9** [zhile-io/pandora#76]
请教一下大家
Pool token能否搭配Chatgpt Next web或其他项目使用？

或者说Pool token如何使用

以及如何进行自动化续期Pooltoken?

**Comment by undefinedcodezhong** [comment]
1. 可以 2. 可以用脚本更新

**Comment by walkchen9** [comment]
> 1. 可以 2. 可以用脚本更新

可否简单告知一下如果搭配Next web使用，以及更新的脚本   或相关文档
非常感谢

**Comment by undefinedcodezhong** [comment]
端点设置为https://ai.fakeopen.com/v1，就可以使用pool token
运行更新脚本需要代理环境：https://github.com/zhile-io/pandora/issues/66#issuecomment-1729441430

**Comment by walkchen9** [comment]
> 端点设置为[https://ai.fakeopen.com/v1，就可以使用pool](https://ai.fakeopen.com/v1%EF%BC%8C%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8pool) token 运行更新脚本需要代理环境：[#66 (comment)](https://github.com/zhile-io/pandora/issues/66#issuecomment-1729441430)

docker run -d -p 3000:3000 -e BASE_URL=https://ai.fakeopen.com/ -e OPENAI_API_KEY=pk-*** yidadaa/chatgpt-next-web

非常感谢，已经调通，实际测试目前 BASE_URL=https://ai.fakeopen.com/即可。

**Comment by longxingdeng** [comment]
请问有没有人知道 open interpreter 的api 接口地址在哪？能换成https://ai.fakeopen.com/ 吗？

**Comment by undefinedcodezhong** [comment]
> 请问有没有人知道 open interpreter 的api 接口地址在哪？能换成https://ai.fakeopen.com/ 吗？

当然是可以的，可以用指令参数，当然更推荐使用系统配置文件的方式，用-h的方法可以看看都可以使用什么指令参数
![image](https://github.com/zhile-io/pandora/assets/40236765/235eef76-2146-4d5e-ba1b-5f54b2298804)

**Comment by zhile-io** [comment]
可以的。

**Comment by complexly** [comment]
> > 请问有没有人知道 open interpreter 的api 接口地址在哪？能换成https://ai.fakeopen.com/ 吗？
> 
> 当然是可以的，可以用指令参数，当然更推荐使用系统配置文件的方式，用-h的方法可以看看都可以使用什么指令参数 ![image](https://user-images.githubusercontent.com/40236765/273383947-235eef76-2146-4d5e-ba1b-5f54b2298804.png)

fakeopen套壳api不支持function call，只能自己运行代码吧

**Comment by 14790897** [comment]
open interpreter 是什么

**Comment by undefinedcodezhong** [comment]
> open interpreter 是什么

github搜一下就知道了，不提供支持function calling模型的api的话，就相当于一个可以在终端会话、不带fq的pandora。

**Comment by 14790897** [comment]
> > open interpreter 是什么
> 
> github搜一下就知道了，不提供支持function calling模型的api的话，就相当于一个可以在终端会话、不带fq的pandora。

大佬，那么autogpt能用fakeopen吗？

**Comment by HartleyLau** [comment]
Chatgpt Next web 中使用报错，docker中部署的，部署命令为：docker run -d -p 3000:3000 -e 
BASE_URL=https://ai.fakeopen.com/ -e OPENAI_API_KEY=fk-*** yidadaa/chatgpt-next-web
使用的是pool token，应用中报错，提示"message": "Unauthorized - Access token is missing",
![Snipaste_2023-11-02_12-37-54](https://github.com/zhile-io/pandora/assets/7857624/884725de-c29d-4d84-96c1-ce6b7e381f7d)

**Comment by undefinedcodezhong** [comment]
> Chatgpt Next web 中使用报错，docker中部署的，部署命令为：docker run -d -p 3000:3000 -e BASE_URL=https://ai.fakeopen.com/ -e OPENAI_API_KEY=fk-*** yidadaa/chatgpt-next-web 使用的是pool token，应用中报错，提示"message": "Unauthorized - Access token is missing", ![Snipaste_2023-11-02_12-37-54](https://user-images.githubusercontent.com/7857624/279867849-884725de-c29d-4d84-96c1-ce6b7e381f7d.png)

那你可能要去问问nextweb docker部署的问题了，直接设置key和url是能用的
![image](https://github.com/zhile-io/pandora/assets/40236765/2eb551bb-7a17-472f-9401-167494863b30)

![image](https://github.com/zhile-io/pandora/assets/40236765/8398b389-a6a3-4763-a61d-b72407298d10)

**Comment by HartleyLau** [comment]
@undefinedcodezhong 刚刚按照你的方法测试了一下，发现share token可以使用，pool token无法使用

**Comment by undefinedcodezhong** [comment]
> @undefinedcodezhong 刚刚按照你的方法测试了一下，发现share token可以使用，pool token无法使用

注意看，我用的就是pool token，如果你pool token用不了，那需要检查下pool token的有效性
