### ISSUE TITLE
按回车就直接发送了

### ISSUE THREAD

**Issue by XY303** [zhile-io/pandora#78]
目前只在我的电脑上出现这种情况,只要输入了内容,按下回车就会直接发送而不能换行.
仅出现在新信息发送,修改旧信息不会发生这个问题.
在教室电脑上可以回车换行.
有一些报错不知道有没有关系:
![image](https://github.com/zhile-io/pandora/assets/76906627/d1c55b16-129a-45ca-92f5-7756b1228d57)
注意到在输入任意字符后发送按钮就会变成激活状态,此时按回车就会发送信息.
![image](https://github.com/zhile-io/pandora/assets/76906627/e029b830-71f0-48d8-aaa1-44b0f02fd288)
需要我提供任何信息我会尽力满足

**Comment by undefinedcodezhong** [comment]
如果你想换行而不是直接发送，你可以尝试使用“Shift+Enter”的组合，Enter表发送是大部分浏览器文本框的默认设置行为

**Comment by XY303** [comment]
补充:在打开开发者工具使页面大小变小直到左侧的功能区关闭后就不会出现此问题

**Comment by XY303** [comment]
哦谢谢
