### ISSUE TITLE
http模式启动后该如何在其他软件中使用api？

### ISSUE THREAD

**Issue by Joackk** [zhile-io/pandora#8]
这里我用服务模式启动后，访问api文档中的那个向gpt提问的接口，看记录里返回了个404
![image](https://github.com/zhile-io/pandora/assets/45162558/82eb6f05-762f-4390-ac3b-126faf651014)
看了下api文档感觉在其它软件里用的话应该是直接用这个api吧？？求大佬指点一下

**Comment by Joackk** [comment]
直接在其他软件中使用/api/conversation/talk这个接口我得到了如下报错
<img width="853" alt="9b711584df3399769dd6777edddce1ac" src="https://github.com/zhile-io/pandora/assets/45162558/382ad060-60c1-45b2-87bc-17f726cb77f4">

**Comment by zhile-io** [comment]
你访问 http://127.0.0.1:8008 ，打开浏览器调试工具，发一条消息就知道该怎么调用了。

**Comment by Joackk** [comment]
> 你访问 http://127.0.0.1:8008 ，打开浏览器调试工具，发一条消息就知道该怎么调用了。

控制台调用的就是http://127.0.0.1:8008/api/conversation/talk这个地址啊，但是在其他软体里调用就出现了上面的报错哇

**Comment by zhile-io** [comment]
这是一个非标接口，用作编程作用，不能直接用在其他软件中。 #13 应该能满足你的需求。

**Comment by Joackk** [comment]
> 这是一个非标接口，用作编程作用，不能直接用在其他软件中。 #13 应该能满足你的需求。

大佬按着文档里说的，那我用-s参数启动潘多拉后，我请求的地址该写成https://ai.fakeopen.com  来用吗？那key的话要填写token吗？还是空着就行了

**Comment by zhile-io** [comment]
> > 这是一个非标接口，用作编程作用，不能直接用在其他软件中。 #13 应该能满足你的需求。
> 
> 大佬按着文档里说的，那我用-s参数启动潘多拉后，我请求的地址该写成https://ai.fakeopen.com 来用吗？那key的话要填写token吗？还是空着就行了

这种api都是历史级别的了。 建议直接使用 https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#1-v1chatcompletions 各种软件均兼容。

**Comment by Joackk** [comment]
> > > 这是一个非标接口，用作编程作用，不能直接用在其他软件中。 #13 应该能满足你的需求。
> > 
> > 
> > 大佬按着文档里说的，那我用-s参数启动潘多拉后，我请求的地址该写成https://ai.fakeopen.com 来用吗？那key的话要填写token吗？还是空着就行了
> 
> 这种api都是历史级别的了。 建议直接使用 https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#1-v1chatcompletions 各种软件均兼容。

不是大佬，如果按这里说的，我似乎不需要启动潘多拉，直接去fakeopen请求个token，然后走他的模拟接口就行了，那是不是只用这个的话就不需要潘多拉了？这种模拟的接口可以免魔法吗？

**Comment by zhile-io** [comment]
> > > > 这是一个非标接口，用作编程作用，不能直接用在其他软件中。 #13 应该能满足你的需求。
> > > 
> > > 
> > > 大佬按着文档里说的，那我用-s参数启动潘多拉后，我请求的地址该写成https://ai.fakeopen.com 来用吗？那key的话要填写token吗？还是空着就行了
> > 
> > 
> > 这种api都是历史级别的了。 建议直接使用 https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#1-v1chatcompletions 各种软件均兼容。
> 
> 不是大佬，如果按这里说的，我似乎不需要启动潘多拉，直接去fakeopen请求个token，然后走他的模拟接口就行了，那是不是只用这个的话就不需要潘多拉了？这种模拟的接口可以免魔法吗？

你的理解是完全正确的，这个是很古早的接口方式了。现在已经不需要这么做。 你可以看一个例子： https://chat.geekgpt.org 这里填充的api地址和api key。

**Comment by Joackk** [comment]
> > > > > 这是一个非标接口，用作编程作用，不能直接用在其他软件中。 #13 应该能满足你的需求。
> > > > 
> > > > 
> > > > 大佬按着文档里说的，那我用-s参数启动潘多拉后，我请求的地址该写成https://ai.fakeopen.com 来用吗？那key的话要填写token吗？还是空着就行了
> > > 
> > > 
> > > 这种api都是历史级别的了。 建议直接使用 https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#1-v1chatcompletions 各种软件均兼容。
> > 
> > 
> > 不是大佬，如果按这里说的，我似乎不需要启动潘多拉，直接去fakeopen请求个token，然后走他的模拟接口就行了，那是不是只用这个的话就不需要潘多拉了？这种模拟的接口可以免魔法吗？
> 
> 你的理解是完全正确的，这个是很古早的接口方式了。现在已经不需要这么做。 你可以看一个例子： https://chat.geekgpt.org 这里填充的api地址和api key。

了解了，感谢大佬

**Comment by zhile-io** [comment]
> > > > > > 这是一个非标接口，用作编程作用，不能直接用在其他软件中。 #13 应该能满足你的需求。
> > > > > 
> > > > > 
> > > > > 大佬按着文档里说的，那我用-s参数启动潘多拉后，我请求的地址该写成https://ai.fakeopen.com 来用吗？那key的话要填写token吗？还是空着就行了
> > > > 
> > > > 
> > > > 这种api都是历史级别的了。 建议直接使用 https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#1-v1chatcompletions 各种软件均兼容。
> > > 
> > > 
> > > 不是大佬，如果按这里说的，我似乎不需要启动潘多拉，直接去fakeopen请求个token，然后走他的模拟接口就行了，那是不是只用这个的话就不需要潘多拉了？这种模拟的接口可以免魔法吗？
> > 
> > 
> > 你的理解是完全正确的，这个是很古早的接口方式了。现在已经不需要这么做。 你可以看一个例子： https://chat.geekgpt.org 这里填充的api地址和api key。
> 
> 了解了，感谢大佬

不客气。你可以把免费账号包成3.5使用，也可以把plus包成gpt-4使用（不需要解决arkose打码之类的问题）

**Comment by Joackk** [comment]
> > > > > > > 这是一个非标接口，用作编程作用，不能直接用在其他软件中。 #13 应该能满足你的需求。
> > > > > > 
> > > > > > 
> > > > > > 大佬按着文档里说的，那我用-s参数启动潘多拉后，我请求的地址该写成https://ai.fakeopen.com 来用吗？那key的话要填写token吗？还是空着就行了
> > > > > 
> > > > > 
> > > > > 这种api都是历史级别的了。 建议直接使用 https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#1-v1chatcompletions 各种软件均兼容。
> > > > 
> > > > 
> > > > 不是大佬，如果按这里说的，我似乎不需要启动潘多拉，直接去fakeopen请求个token，然后走他的模拟接口就行了，那是不是只用这个的话就不需要潘多拉了？这种模拟的接口可以免魔法吗？
> > > 
> > > 
> > > 你的理解是完全正确的，这个是很古早的接口方式了。现在已经不需要这么做。 你可以看一个例子： https://chat.geekgpt.org 这里填充的api地址和api key。
> > 
> > 
> > 了解了，感谢大佬
> 
> 不客气。你可以把免费账号包成3.5使用，也可以把plus包成gpt-4使用（不需要解决arkose打码之类的问题）

非常感谢大佬的解惑，我就个人需求，也就用3.5，主要是拿来给翻译软件和一些其他应用调用，

**Comment by zhile-io** [comment]
> > > > > > > > 这是一个非标接口，用作编程作用，不能直接用在其他软件中。 #13 应该能满足你的需求。
> > > > > > > 
> > > > > > > 
> > > > > > > 大佬按着文档里说的，那我用-s参数启动潘多拉后，我请求的地址该写成https://ai.fakeopen.com 来用吗？那key的话要填写token吗？还是空着就行了
> > > > > > 
> > > > > > 
> > > > > > 这种api都是历史级别的了。 建议直接使用 https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#1-v1chatcompletions 各种软件均兼容。
> > > > > 
> > > > > 
> > > > > 不是大佬，如果按这里说的，我似乎不需要启动潘多拉，直接去fakeopen请求个token，然后走他的模拟接口就行了，那是不是只用这个的话就不需要潘多拉了？这种模拟的接口可以免魔法吗？
> > > > 
> > > > 
> > > > 你的理解是完全正确的，这个是很古早的接口方式了。现在已经不需要这么做。 你可以看一个例子： https://chat.geekgpt.org 这里填充的api地址和api key。
> > > 
> > > 
> > > 了解了，感谢大佬
> > 
> > 
> > 不客气。你可以把免费账号包成3.5使用，也可以把plus包成gpt-4使用（不需要解决arkose打码之类的问题）
> 
> 非常感谢大佬的解惑，我就个人需求，也就用3.5，主要是拿来给翻译软件和一些其他应用调用，

由于ChatGPT一个账号同时只能一个并发问答，翻译软件或其他应用场景未必能很好地工作，你可能需要建立号池去实现。 至于翻译，可以试试我部署的 deeplx，在 status.fakeopen.com 里可以找到对应地址以及查看服务状态。

**Comment by Joackk** [comment]
> > > > > > > > > 这是一个非标接口，用作编程作用，不能直接用在其他软件中。 #13 应该能满足你的需求。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 大佬按着文档里说的，那我用-s参数启动潘多拉后，我请求的地址该写成https://ai.fakeopen.com 来用吗？那key的话要填写token吗？还是空着就行了
> > > > > > > 
> > > > > > > 
> > > > > > > 这种api都是历史级别的了。 建议直接使用 https://github.com/zhile-io/pandora/blob/master/doc/fakeopen.md#1-v1chatcompletions 各种软件均兼容。
> > > > > > 
> > > > > > 
> > > > > > 不是大佬，如果按这里说的，我似乎不需要启动潘多拉，直接去fakeopen请求个token，然后走他的模拟接口就行了，那是不是只用这个的话就不需要潘多拉了？这种模拟的接口可以免魔法吗？
> > > > > 
> > > > > 
> > > > > 你的理解是完全正确的，这个是很古早的接口方式了。现在已经不需要这么做。 你可以看一个例子： https://chat.geekgpt.org 这里填充的api地址和api key。
> > > > 
> > > > 
> > > > 了解了，感谢大佬
> > > 
> > > 
> > > 不客气。你可以把免费账号包成3.5使用，也可以把plus包成gpt-4使用（不需要解决arkose打码之类的问题）
> > 
> > 
> > 非常感谢大佬的解惑，我就个人需求，也就用3.5，主要是拿来给翻译软件和一些其他应用调用，
> 
> 由于ChatGPT一个账号同时只能一个并发问答，翻译软件或其他应用场景未必能很好地工作，你可能需要建立号池去实现。 至于翻译，可以试试我部署的 deeplx，在 status.fakeopen.com 里可以找到对应地址以及查看服务状态。

哈哈其实我用的没那么高级，我只是用来推游戏时候啃生肉时候给翻译gal的软件用一下，因为比那些网页翻译效果要好很多
