### ISSUE TITLE
请问CHATGPT_API_PREFIX这个能走内网么？

### ISSUE THREAD

**Issue by MrLiuGangQiang** [zhile-io/pandora#80]
我设置CHATGPT_API_PREFIX这个地址，填写的是内网地址。当我在内网访问时正常，但是我从外网访问发现无法访问，映射成外网地址后正常，但是我不想我自己这个代理暴露到外网上去

**Comment by zhile-io** [comment]
你又不想暴露到外网，又想从外网访问？
