### ISSUE TITLE
安装完后没有命令

### ISSUE THREAD

**Issue by yuwanOvO** [zhile-io/pandora#82]
pip安装完pandora-chatgpt[cloud]后，运行pandora和pandora-cloud都显示没有命令

**Comment by undefinedcodezhong** [comment]
是windows系统？不建议直接在系统的python上使用，因为我有时候也是这个情况，显示没有命令，大概和环境变量有关。
用anaconda或者miniconda创建虚拟环境就不会遇到这个问题，使用也更加安全。
