### ISSUE TITLE
串台了，别人的提问都跑到我的会话记录里了。

### ISSUE THREAD

**Issue by digitalboy** [zhile-io/pandora#83]
请各位大佬看看是哪里出问题了，我是用我的账号\我的token登录的。

**Comment by yayaQAQ** [comment]
有没有可能，卖给你号的人，也把这个号卖给过其他人？

**Comment by undefinedcodezhong** [comment]
开个对话，问他是谁，是不是被卖号的用共享号坑了😂

**Comment by zhheo** [comment]
那个不是“你的回话记录”而是“你的账号的会话记录”
所以说如果是共享号，这很合理，如果是私有号，那么去改密码

**Comment by zhile-io** [comment]
如果你是server模式，那么你不应该无保护地暴露在公网。

**Comment by digitalboy** [comment]
> 如果你是server模式，那么你不应该无保护地暴露在公网。

也许是没加上 ssl?

**Comment by digitalboy** [comment]
> 有没有可能，卖给你号的人，也把这个号卖给过其他人？



> 开个对话，问他是谁，是不是被卖号的用共享号坑了😂

我是自己的账号没有分享给别人，我每个月都还得交钱呢。
