### ISSUE TITLE
{"detail":"invalid callback url"}

### ISSUE THREAD

**Issue by lhg-vv** [zhile-io/pandora#84]
![image](https://github.com/zhile-io/pandora/assets/75786042/632ff1c9-32b2-488d-b442-f62bf560a76e)
登入时回调异常，需要怎么处理？

**Comment by geekotaku** [comment]
+1

**Comment by hongchenvpn** [comment]
+1

**Comment by lntutony** [comment]
有大佬解决了吗

**Comment by hongchenvpn** [comment]
我还有一个用了自己的代理，自己搭建的，也是出问题了，应该不是pandora的问题，是openai的接口哪里调整了。。。看大佬能解决么

**Comment by lntutony** [comment]
token能不能登录

**Comment by kwokzito** [comment]
一样的错误

**Comment by lntutony** [comment]
> token能不能登录

可以

**Comment by MrLiuGangQiang** [comment]
+1 自己搞的代理也不行 应该是官方改了啥

**Comment by delicacyyy** [comment]
我这边也不行了 一样的错误

**Comment by zhile-io** [comment]
官方搞事情，在登录的时候加了验证码。

**Comment by achirand** [comment]
> 官方搞事情，在登录的时候加了验证码。

有办法解决吗？  或者能显示这个验证码界面吗？

**Comment by AlwaysZmx** [comment]
+1

**Comment by zhile-io** [comment]
> > 官方搞事情，在登录的时候加了验证码。
> 
> 有办法解决吗？ 或者能显示这个验证码界面吗？

https://ai.fakeopen.com/auth 用这个先顶一顶吧。

**Comment by leonqiu888** [comment]
+1  还以为部署出错了

**Comment by sunzongjian** [comment]
+1，对于token过期的怎么办？

**Comment by C-GY** [comment]
+1

**Comment by xxhh1112** [comment]
d

**Comment by achirand** [comment]
https://chat.zhile.io/
这里输入自己的帐号，和密码 就可以直接使用，挺流畅。   没有invalid callback url报错。

chat.zhile.io网站可以做到。 自已在vercel部署的网站却出问题，问题出在那。 还求zhile大佬指导。

**Comment by Peterzion89** [comment]
> > > > 官方搞事情，在登录的时候加了验证码。
> > > 
> > > 
> > > 有办法解决吗？或者能显示这个验证码界面吗？
> > 
> > 
> > https://ai.fakeopen.com/auth用这个先顶一顶吧。
> 
> 大佬有计划什么时候修复么

就用大佬说的那个方案  key登录 还方便一点，至少还能用。

**Comment by MrLiuGangQiang** [comment]
> Peterzion89

只能先用着了，我看作者的示例网站已经修复了，不知道啥时候提交代码，现在感觉没了gpt工作效率低一半

**Comment by francly** [comment]
请问access token拿到了，命名正确吗？以为没有侦测到

~/.config/Pandora-ChatGPT$
ls
accesstoken.dat

**Comment by francly** [comment]
> > 请问access token拿到了，命名正确吗？的、还是没有侦测到
> > ~/.config/Pandora-ChatGPT$ ls accesstoken.dat
> 
> 有人可以提供一下吗

可以了

pandora -t accesstoken.dat 一次就行了
