### ISSUE TITLE
fakeopen.com被墙了，该如何更换自己搭的域名呢

### ISSUE THREAD

**Issue by qq1997** [zhile-io/pandora#86]
不知道该怎末改成自己的域名

**Comment by shuaiplus** [comment]
没被墙，估计是被打了

**Comment by qq1997** [comment]
> 没被墙，估计是被打了

我已经被墙快2周了，挂梯子才能用

**Comment by shuaiplus** [comment]
> > 没被墙，估计是被打了
> 
> 我已经被墙快2周了，挂梯子才能用

![image](https://github.com/zhile-io/pandora/assets/100134295/4ac914d5-6f7d-437c-a418-4d6e5bf45ee3)
没错，你是一个人

**Comment by zhile-io** [comment]
文档上有

**Comment by qq1997** [comment]
文档上说的很模糊，docker拉取的不知道如何改
