### ISSUE TITLE
手机登录失败，返回提示detail:invalid callback url 

### ISSUE THREAD

**Issue by excavate** [zhile-io/pandora#87]
如图，电脑登录可以，手机登录不行
![810ec5ef162223125d283d584dba77e](https://github.com/zhile-io/pandora/assets/48313294/094f4f33-b71a-475f-8379-8d9f2548a69e)

**Comment by zhile-io** [comment]
把电脑上的access token在手机上粘贴进去。

**Comment by excavate** [comment]
> 把电脑上的access token在手机上粘贴进去。

我用的是密码登录，之前手机通过这种方式是可以的

**Comment by neosun100** [comment]
密码登陆失败，同样的
问题

**Comment by rxinyiduo** [comment]
俺也一样

**Comment by chansanya** [comment]
俺也一样,上午还好好的

**Comment by MDDTGitHub** [comment]
<img width="493" alt="image" src="https://github.com/zhile-io/pandora/assets/38212384/a464ff0d-c61b-4569-8762-7fe77a1e2b2d">
同样的错误

**Comment by zhile-io** [comment]
#84
