### ISSUE TITLE
修改Dockerfile重新build之后报错

### ISSUE THREAD

**Issue by huangbh1024** [zhile-io/pandora#9]
在Dockerfile里面添加了两个环境变量，build之后启动报错
![image](https://github.com/zhile-io/pandora/assets/72372968/1c95439a-9fcb-4853-a842-86bb6744353d)
![image](https://github.com/zhile-io/pandora/assets/72372968/087fb970-e4d5-44b0-a3a9-56e727f0e483)

**Comment by zhile-io** [comment]
ENV PANDORA_SERVER=0.0.0.0:5501
