### ISSUE TITLE
vps上搭建之后，登录使用的吐字速度还是和官网一样很慢

### ISSUE THREAD

**Issue by ZDY321** [zhile-io/pandora#90]
vps上搭建之后，登录使用的吐字速度还是和官网一样很慢。Debian11，使用的最新docker版的Pandora

**Comment by leonqiu888** [comment]
我的很快的 系统centos7 美国IP

**Comment by ZDY321** [comment]
> 我的快速系统centos7美国IP
已下载就全出来吗？我的也是美国ip，Debian11

**Comment by zhile-io** [comment]
可能是你网络问题。
