### ISSUE TITLE
{"detail":"rate limited."} Continu

### ISSUE THREAD

**Issue by lntutony** [zhile-io/pandora#91]
更新完之后登录这个报错
![image](https://github.com/zhile-io/pandora/assets/128949418/f64dd144-0cf3-411a-98cc-97dde0f12d8a)

**Comment by hanhan3344** [comment]
+1

**Comment by aaronyang1122** [comment]
+1

**Comment by faea726** [comment]
+1

**Comment by JasonChoiCn** [comment]
me too

**Comment by dedadeda26** [comment]
+1

**Comment by xiaotianxt** [comment]
+1

**Comment by dingtianlu** [comment]
+1

**Comment by dingtianlu** [comment]
+1 大佬麻烦看看啥问题

**Comment by isslii** [comment]
+1

**Comment by spb512** [comment]
我也是+1

**Comment by chux1995** [comment]
+1

**Comment by lrteaegg** [comment]
+1

**Comment by bravekingzhang** [comment]
+1，已经一天了

**Comment by sandycs-protoss** [comment]
+1
Rate limited

**Comment by sugar1688** [comment]
+1

**Comment by xiaomengxin123** [comment]
+1
Rate limited

**Comment by chxgzs** [comment]
还没有解决办法吗 ?

**Comment by chxgzs** [comment]
不能用账号密码登入了 只能选择Access Token模式了.

**Comment by ellicoo** [comment]
> Token

这个咋操作呢

**Comment by CodeZhangBorui** [comment]
+1

**Comment by xzy103** [comment]
+1

**Comment by chxgzs** [comment]
![image](https://github.com/zhile-io/pandora/assets/47893401/fc0570ad-2f7f-422e-87a4-f9f847407752)
这个啊.里面有中文的教程.

**Comment by ludashi2020** [comment]
+1
Rate limited

**Comment by MackeyLao** [comment]
https://chat.zhile.io/
也是使用Pandora，使用账号登录是没问题的。
我使用docker部署的却有问题，已经重新pull了，也是这样，难道是docker的版本太旧了。

**Comment by lanyirenjg** [comment]
+1，更新了最新的镜像还是不可以，但作者的https://chat.zhile.io/是可以的

**Comment by duyajun** [comment]
+1，今天早上又重新pull了一遍，还是报这个错哦~

**Comment by bravekingzhang** [comment]
看起来是 cf 的问题 ，作者的 zhile 多半是写死了某一个中间链接，或者维持了 cf的监测状态
