### ISSUE TITLE
我看chat.zhile.io已经能登录了，大佬啥时候同步发一下docker

### ISSUE THREAD

**Issue by MrLiuGangQiang** [zhile-io/pandora#92]

**Comment by leonqiu888** [comment]
我也看过了  演示的确实可以了  好像大佬代码没更新   同求~~~~~

**Comment by kaigege66** [comment]
+1

**Comment by chinggirltube** [comment]
求大佬更新..我也不能用帐号密码登陆..

**Comment by Davidtian0905** [comment]
+1

**Comment by achirand** [comment]
**chat.zhile.io  也不能登录了**


![image](https://github.com/zhile-io/pandora/assets/19645588/17d5fa65-1d1b-4962-a271-9cf000616e1b)

**Comment by zhile-io** [comment]
已修复。

**Comment by kaigege66** [comment]
docker版本页已经同步发布了，你重新配置一下就行了

发自我的 iPhone

在 2023年10月11日，11:19，zhile.io ***@***.***> 写道：

﻿

已修复。
