### ISSUE TITLE
pandora项目不能在Vercel上部署了吗？

### ISSUE THREAD

**Issue by sugar1688** [zhile-io/pandora#94]
pandora项目不能在Vercel上部署了吗？只能用dock部署吗，有没什么免费容器可以在上面部署的

**Comment by undefinedcodezhong** [comment]
可以啊，你用Python启动呗

**Comment by sugar1688** [comment]
> 可以啊，你用Python启动呗

不行啊，怎么操作，我看作文文档也没写怎么在Vercel上部署了

**Comment by undefinedcodezhong** [comment]
https://github.com/zhile-io/pandora-cloud-serverless
