### ISSUE TITLE
咨询大家部署环境的事情

### ISSUE THREAD

**Issue by fgott** [zhile-io/pandora#96]
大家都是用什么环境部署的pandora呢？
本人尝试了下centos7，还没搞定，在头疼哪里有问题呢。

**Comment by MrLiuGangQiang** [comment]
#!/bin/bash
image_name=pengzhile/pandora

echo  "\e[31m停止镜像->删除容器->删除镜像\e[0m"
docker ps -a | grep ${image_name} | awk '{print $1}' | xargs -L1 docker stop
docker ps -a | grep ${image_name} | awk '{print $1}' | xargs -L1 docker rm
docker images | grep ${image_name} | awk '{print $3}' | xargs -L1 docker rmi

echo  "\e[32m拉取最新镜像[${image_name}]\e[0m"
docker pull ${image_name}:latest
update_time=$(docker image inspect --format='{{.Created}}' ${image_name}:latest | xargs -I {} date -d {} '+%Y-%m-%d %H:%M:%S')
echo  "\e[33m镜像更新时间为：[${update_time}]\e[0m"

echo  "\e[32m部署容器并设置开机自启动\e[0m"
docker run -d \
--name=pandora \
--restart=always \
-v /etc/localtime:/etc/localtime \
-e PANDORA_CLOUD=cloud \
-e PANDORA_SERVER=0.0.0.0:3000 \
-e PANDORA_THREADS=8 \
-p 3000:3000 \
${image_name}

**Comment by fgott** [comment]
> #!/bin/bash image_name=pengzhile/pandora
> 
> echo "\e[31m停止镜像->删除容器->删除镜像\e[0m" docker ps -a | grep ${image_name} | awk '{print $1}' | xargs -L1 docker stop docker ps -a | grep ${image_name} | awk '{print $1}' | xargs -L1 docker rm docker images | grep ${image_name} | awk '{print $3}' | xargs -L1 docker rmi
> 
> echo "\e[32m拉取最新镜像[${image_name}]\e[0m" docker pull ${image_name}:latest update_time=$(docker image inspect --format='{{.Created}}' ${image_name}:latest | xargs -I {} date -d {} '+%Y-%m-%d %H:%M:%S') echo "\e[33m镜像更新时间为：[${update_time}]\e[0m"
> 
> echo "\e[32m部署容器并设置开机自启动\e[0m" docker run -d --name=pandora --restart=always -v /etc/localtime:/etc/localtime -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:3000 -e PANDORA_THREADS=8 -p 3000:3000 ${image_name}

我拉取镜像会提示 ： missing signature key

**Comment by MrLiuGangQiang** [comment]
> missing signature key

这你自己环境的问题

**Comment by undefinedcodezhong** [comment]
用python跑起来，或者部署这个：https://github.com/zhile-io/pandora-cloud-serverless
