### ISSUE TITLE
是否可以用账号密码而不是AccessToken的方式登陆，如果可以环境变量如何配置？

### ISSUE THREAD

**Issue by Nexchard** [zhile-io/pandora#97]
系统：centos7
环境：docker
服务器有代理工具，可以访问openai、chatgpt
目的：能够不用考虑token过期，即时过期，直接输入账号密码就能登陆，而不用再去抓token

**Comment by MrLiuGangQiang** [comment]
> 系统：centos7 环境：docker 服务器有代理工具，可以访问openai、chatgpt 目的：能够不用考虑token过期，即时过期，直接输入账号密码就能登陆，而不用再去抓token

#!/bin/bash
image_name=pengzhile/pandora

echo  "\e[31m停止镜像->删除容器->删除镜像\e[0m"
docker ps -a | grep ${image_name} | awk '{print $1}' | xargs -L1 docker stop
docker ps -a | grep ${image_name} | awk '{print $1}' | xargs -L1 docker rm
docker images | grep ${image_name} | awk '{print $3}' | xargs -L1 docker rmi

echo  "\e[32m拉取最新镜像[${image_name}]\e[0m"
docker pull ${image_name}:latest
update_time=$(docker image inspect --format='{{.Created}}' ${image_name}:latest | xargs -I {} date -d {} '+%Y-%m-%d %H:%M:%S')
echo  "\e[33m镜像更新时间为：[${update_time}]\e[0m"

echo  "\e[32m部署容器并设置开机自启动\e[0m"
docker run -d \
--name=pandora \
--restart=always \
-v /etc/localtime:/etc/localtime \
-e PANDORA_CLOUD=cloud \
-e PANDORA_SERVER=0.0.0.0:3000 \
-e PANDORA_THREADS=8 \
-e PANDORA_LOGIN_LOCAL=1 \
-e CHATGPT_API_PREFIX=自己搭建的代理地址 \
-p 3000:3000 \
${image_name}

**Comment by Nexchard** [comment]
> > 系统：centos7 环境：docker 服务器有代理工具，可以访问openai、chatgpt 目的：能够不用考虑token过期，即时过期，直接输入账号密码就能登陆，而不用再去抓token
> 
> #!/bin/bash image_name=pengzhile/pandora
> 
> echo "\e[31m停止镜像->删除容器->删除镜像\e[0m" docker ps -a | grep ${image_name} | awk '{print $1}' | xargs -L1 docker stop docker ps -a | grep ${image_name} | awk '{print $1}' | xargs -L1 docker rm docker images | grep ${image_name} | awk '{print $3}' | xargs -L1 docker rmi
> 
> echo "\e[32m拉取最新镜像[${image_name}]\e[0m" docker pull ${image_name}:latest update_time=$(docker image inspect --format='{{.Created}}' ${image_name}:latest | xargs -I {} date -d {} '+%Y-%m-%d %H:%M:%S') echo "\e[33m镜像更新时间为：[${update_time}]\e[0m"
> 
> echo "\e[32m部署容器并设置开机自启动\e[0m" docker run -d --name=pandora --restart=always -v /etc/localtime:/etc/localtime -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:3000 -e PANDORA_THREADS=8 -e PANDORA_LOGIN_LOCAL=1 -e CHATGPT_API_PREFIX=自己搭建的代理地址 -p 3000:3000 ${image_name}

没有别的设置了么？请问代理格式怎么写？

**Comment by Nexchard** [comment]
> > 系统：centos7 环境：docker 服务器有代理工具，可以访问openai、chatgpt 目的：能够不用考虑token过期，即时过期，直接输入账号密码就能登陆，而不用再去抓token
> 
> #!/bin/bash image_name=pengzhile/pandora
> 
> echo "\e[31m停止镜像->删除容器->删除镜像\e[0m" docker ps -a | grep ${image_name} | awk '{print $1}' | xargs -L1 docker stop docker ps -a | grep ${image_name} | awk '{print $1}' | xargs -L1 docker rm docker images | grep ${image_name} | awk '{print $3}' | xargs -L1 docker rmi
> 
> echo "\e[32m拉取最新镜像[${image_name}]\e[0m" docker pull ${image_name}:latest update_time=$(docker image inspect --format='{{.Created}}' ${image_name}:latest | xargs -I {} date -d {} '+%Y-%m-%d %H:%M:%S') echo "\e[33m镜像更新时间为：[${update_time}]\e[0m"
> 
> echo "\e[32m部署容器并设置开机自启动\e[0m" docker run -d --name=pandora --restart=always -v /etc/localtime:/etc/localtime -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:3000 -e PANDORA_THREADS=8 -e PANDORA_LOGIN_LOCAL=1 -e CHATGPT_API_PREFIX=自己搭建的代理地址 -p 3000:3000 ${image_name}

测试了一下，提示：{"detail":"rate limited."}

**Comment by sugar1688** [comment]
是啊，以前可以用账号密码登录的，现在这么不行了，提示：{"detail":"rate limited."}，求解决方案

**Comment by MrLiuGangQiang** [comment]
> 是啊，以前可以用账号密码登录的，现在这么不行了，提示：{"detail":"rate limited."}，求解决方案

看其他问题吧 这两天官方搞事情新代码作者还没传上来 走token模式就行

**Comment by NIUKEGE** [comment]
{"detail":"rate limited."}

**Comment by licongguan** [comment]
token模式怎么走呢

**Comment by Nexchard** [comment]
-e PANDORA_CLOUD=cloud
-e PANDORA_SERVER=0.0.0.0:3000
-p 3000:3000
这几个参数应该足够了

**Comment by sw586** [comment]
> -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:3000 -p 3000:3000 这几个参数应该足够了
怎么带上token实现免登录
